### ISSUE TITLE
Update local Pangolin to the latest lineages version

### ISSUE THREAD

**Issue by godtao2** [cov-lineages/pangolin#105]
Hi,
I've been running a local installation of pangolin via the command line. Recently I found that the current lineage scheme was updated to 2020-08-28 (https://github.com/cov-lineages/assignment). However, when i update the lineage release, it can only updated to 05-19. I wonder that the pangolin whether could assign an input sequence to a new lineage assignment (08-28)? My command lines are shown as below:

pip install git+https://github.com/cov-lineages/lineages.git --upgrade

Results:

Successfully built lineages
Installing collected packages: lineages
  Found existing installation: lineages 2020-05-19
    Uninstalling lineages-2020-05-19:
      Successfully uninstalled lineages-2020-05-19
Successfully installed lineages-2020-05-19

Thanks.

**Comment by aineniamh** [comment]
As of pangolin 2.0, the pangoLEARN repo is the one with the update on it (the lineages repo is no longer being updated!). 

You can update using the same command you ran above but just to pangoLEARN:
```
pip install git+https://github.com/cov-lineages/pangoLEARN --upgrade
```
There's some extra documentation about the difference between pangolin 1.0 and 2.0 [here](https://cov-lineages.org/pangolin.html). You may also need to update pangolin itself with the update to the pangoLEARN repo. 

To check the update worked you can type 
```
pangolin -pv
```
which checks the version of pangoLEARN.
