### ISSUE TITLE
Job execution failed (pangolin v2.0.8, pangoLEARN 2020-10-30)

### ISSUE THREAD

**Issue by godtao2** [cov-lineages/pangolin#106]
Hi!
    I updated Pangolin to the latest version and was getting two errors on the execution.
    First, when i use the pangolin to predict sequence EPI_ISL_525495 , I got this error on the execution:

**_[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 3
Error in rule datafunk_trim_and_pad:
    jobid: 4
    output: /tmp/tmppzcs3ura/post_qc_query.aligned.fasta
    shell:
        datafunk sam_2_fasta           -s /tmp/tmppzcs3ura/reference_mapped.sam           -r /envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.8-py3.6.egg/pangolin/data/reference.fasta           -o /tmp/tmppzcs3ura/post_qc_query.aligned.fasta           -t [265:29674]           --pad           --log-inserts
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Exiting because a job execution failed. Look above for error message_**

     Second, when i use the pangolin to predict sequence EPI_ISL_410543 , I got this error on the execution:

**_UnboundLocalError: local variable 'seqid' referenced before assignment
[Tue Nov 24 15:47:18 2020]
Error in rule pangolearn:
    jobid: 2
    output: /tmp/tmp8qckqzr9/lineage_report.pass_qc.csv
    shell:

        pangolearn.py --header-file /envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.8-py3.6.egg/pangolin/data/reference.fasta --fasta /tmp/tmp8qckqzr9/post_qc_query.aligned.fasta -o /tmp/tmp8qckqzr9/lineage_report.pass_qc.csv

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message_**

These two sequences failed to be predicted in pangolin version 2.0.8 , but it got success in version 1.0. Are there any bugs in version 2.0.8? Or the quality of these sequences?

Thanks.

**Comment by aineniamh** [comment]
Hi @godtao2 have you updated the conda environment as well as pangolin?

**Comment by godtao2** [comment]
> Hi @godtao2 have you updated the conda environment as well as pangolin?

Yes, I have updated the conda environment using the following command: 
 _conda env update -f environment.yml_
I found these two sequences were failed to be predicted even using pangolin web.

**Comment by aineniamh** [comment]
Hi @godtao2, can you provide the sequences and I will get to the bottom of the issue!

**Comment by aineniamh** [comment]
Hi @godtao2 if you try updating the environment and pangolin to the latest versions, does this solve your issue?

**Comment by godtao2** [comment]
> Hi @godtao2 if you try updating the environment and pangolin to the latest versions, does this solve your issue?

No, the problem was not solved even after updating the environment and pangolin. I can provide two sequences' accession IDs, but can not provide fasta information, given that they are stored in GISAID database. 

ID: EPI_ISL_525495
ID: EPI_ISL_410543

**Comment by aineniamh** [comment]
Hi @godtao2, we have automated tests now running on this repo so we're certain pangolin installs and runs successfully on linux and mac-osx systems. I suggest you remove the environment and try building it again!

**Comment by godtao2** [comment]
OK. Thank you.

**Comment by aineniamh** [comment]
I'm going to close this issue as hopefully a new install has resolved the problem for you!
