### ISSUE TITLE
update pangolin instructions in README

### ISSUE THREAD

**Issue by tpall** [cov-lineages/pangolin#110]
Hi, in light of new uk strain, I tried to update my pangolin installation from 2.08 to 2.1.1 according to instructions in README and noted that it worked for me when I run

```bash
conda env update -f environment.yml
```

before 

```bash
python setup.py install
```

Conda environment update updated also pangolearn.
Please check updating instruction in README.

**Comment by aineniamh** [comment]
It doesn't matter which order you run them in. pangoLEARN is part of the environment and is hosted as a separate repo- often the pangolin software also needs to be updated, so I still recommend running both commands.
