### ISSUE TITLE
Error in rule minimap2_check_distance

### ISSUE THREAD

**Issue by junghoon-kwon** [cov-lineages/pangolin#120]
Hello Sir,

I'm trying to install and use Pangolin on my Linux computer.
But following error occured when I try to analyze my fasta file.
Could you please let me know how can I fix it?

[Python version: 3.8]
[snakemake version: 5.32.0]

Data files found
Trained model:	/home/junghoon/miniconda3/lib/python3.8/site-packages/pangoLEARN/data/decisionTree_v1.joblib
Header file:	/home/junghoon/miniconda3/lib/python3.8/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
Lineages csv:	/home/junghoon/miniconda3/lib/python3.8/site-packages/pangoLEARN/data/lineages.metadata.csv
Job counts:
	count	jobs
	1	add_failed_seqs
	1	all
	1	datafunk_trim_and_pad
	1	minimap2_check_distance
	1	minimap2_to_reference
	1	overwrite
	1	pangolearn
	1	parse_paf
	1	type_variants_b117
	1	type_variants_b1351
	1	type_variants_p1
	1	type_variants_p2
	12

        minimap2 -x asm5 -t 1 /home/junghoon/miniconda3/lib/python3.8/site-packages/pangolin-2.1.7-py3.8.egg/pangolin/data/reference.fasta /tmp/tmpvi3hhlmo/query.post_qc.fasta -o /tmp/tmpvi3hhlmo/reference_mapped.paf &> /tmp/tmpvi3hhlmo/logs/minimap2_check.log
        
[Tue Jan 19 17:47:41 2021]
Error in rule minimap2_check_distance:
    jobid: 7
    output: /tmp/tmpvi3hhlmo/reference_mapped.paf
    log: /tmp/tmpvi3hhlmo/logs/minimap2_check.log (check log file(s) for error message)
    shell:
        
        minimap2 -x asm5 -t 1 /home/junghoon/miniconda3/lib/python3.8/site-packages/pangolin-2.1.7-py3.8.egg/pangolin/data/reference.fasta /tmp/tmpvi3hhlmo/query.post_qc.fasta -o /tmp/tmpvi3hhlmo/reference_mapped.paf &> /tmp/tmpvi3hhlmo/logs/minimap2_check.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by aineniamh** [comment]
Hi @junghoon-kwon, how many sequences are you running at once? 
It looks like minimap2 may have exited due to a lack of memory available. If you try with fewer sequences at a time, this may resolve your issue.

**Comment by aineniamh** [comment]
Hi @junghoon-kwon, I didn't hear back from you if your issue was resolved running fewer sequences. I'm going to close this issue but if it persists I can reopen. In the meantime as well, feel free to use the web app version [here](https://pangolin.cog-uk.io/) for your data.

**Comment by junghoon-kwon** [comment]
Hi @aineniamh, 
Sorry for late response,
I tried with fewer sequences, and just one sequence, but it still showed same error.
Do you have any other idea?
I will try to re-install all related programs and let you know again.

Regards,
