### ISSUE TITLE
Please, provide genomic coordinates

### ISSUE THREAD

**Issue by nekrut** [cov-lineages/pangolin#126]
Thank you very much for fantastic resource! The only issue that is somewhat annoying is the use of gene based (local) coordinates. Would it be possible to provide genomic (global) coordinates (0-based in `NC_045512.2`) along with the local ones. Something along these lines -> https://virological.org/t/genomic-coordinates-for-b-1-1-7-p-1-and-b-1-351/606

**Comment by aineniamh** [comment]
No longer host any coordinates on this repo!
