### ISSUE TITLE
Docker output differs from web app output

### ISSUE THREAD

**Issue by mcrone** [cov-lineages/pangolin#128]
Hey everyone

I've used the docker file to run some of my data through the pipeline. I get the lineage assigned as B1.1, however, I get B1.1.7 using the web app. Is there any reason why the outputs of these would differ? I've tried adding the -p tag without any success.

**Comment by aineniamh** [comment]
There could be a version difference issue- I tagged a new release yesterday in pangolin that is more strict about reference alleles being present, but the web-app may not be updated yet. Do you have the sequence to hand? I'll have a look and see what the change may be.

**Comment by aineniamh** [comment]
Going to close this issue now as I think it will have been resolved by recent updates.
