### ISSUE TITLE
--update broken?

### ISSUE THREAD

**Issue by elliotluab** [cov-lineages/pangolin#129]
I initially installed pangolin yesterday (1/28/21) on a Mac. Following installation I ran pangolin --update, and it worked fine. Today, when I try the same, it complains that there is no query:

(pangolin) elliot@Genome-Calvin 012821 % pangolin --update     
usage: pangolin <query> [options]
pangolin: error: the following arguments are required: query
(pangolin) elliot@Genome-Calvin 012821 % pangolin -v      
pangolin 2.1.7
(pangolin) elliot@Genome-Calvin 012821 % pangolin -lv
lineages 2020-05-19
(pangolin) elliot@Genome-Calvin 012821 % pangolin -pv
pangoLEARN 2021-01-22
(pangolin) elliot@Genome-Calvin 012821 %

**Comment by elliotluab** [comment]
I reinstalled, and now --update appears to be working.

**Comment by aineniamh** [comment]
Great! Thanks for following up. If stuck, you can always follow the original update guidelines on the website too!
