### ISSUE TITLE
Get nucleotide vcf corresponding to lineage

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#134]
Hi,

is it possible to get a vcf or a list of corresponding nucleotide mutations  (in addition to amino acid changes) corresponding to a specific lineage ? Like the ones here >> https://github.com/jts/ncov-watch/tree/master/ncov_watch/watchlists.

For example, we found a B.1.429 in our consensus using pangolin, but we want to confirm it with https://github.com/jts/ncov-watch. 

Regards
Eric Fournier

**Comment by EricFournier3** [comment]
Ok, i found a way to do it with covidcg

**Comment by MrOlm** [comment]
Hello @EricFournier3 - I am looking for something similar (SNV lineage definitions). Would you mind sharing how you got this information?

Thanks,
Matt

**Comment by EricFournier3** [comment]
Hi @MrOlm , see the attached image
![covidcg_nt](https://user-images.githubusercontent.com/15850682/113643800-2ad43600-9651-11eb-9d7f-a2b5e3fa7437.PNG)
