### ISSUE TITLE
running pangolin with pangoLEARN data files at alternative location - pangoLEARN_version does not reflect the used data files

### ISSUE THREAD

**Issue by thsyd** [cov-lineages/pangolin#135]
Hi. working on HPC that has pangolin installed as a module.
I do not have rigths to update to latest version (eg by running 
`pip install git+https://github.com/cov-lineages/pangoLEARN.git --upgrade`

I tried downloading the (at that time) most recent files (__version__= "2021-02-01" in https://github.com/cov-lineages/pangoLEARN/tree/master/pangoLEARN and referencing the location using the --data flag.
However the pangoLEARN_version (date) in the resulting .csv file does not reflect the referenced data, but the version available at the time of installation of pangolin on the HPC (2021-01-22).
As the alternative data folder is referenced in the output in the terminal, I presume the correct data was used. But it is not reflected in the result files.

I did:

`pangolin all.newhead.fasta --data pangodata/data/ --threads 4 --outfile all.newhead.fasta.pangolin.20210206_1.csv
`
Outtake of output to terminal:
```
Looking in pangodata/data/ for data files...

Data files found
Trained model:	pangodata/data/decisionTree_v1.joblib
Header file:	pangodata/data/decisionTreeHeaders_v1.joblib
Lineages csv:	pangodata/data/lineages.metadata.csv


``` 
first row of result file:

taxon | lineage | probability | pangoLEARN_version | status | note
-- | -- | -- | -- | -- | --
<strain_name> | B.1.221 | 1.0 | 22-01-2021 | passed_qc |  

Expected:

taxon | lineage | probability | pangoLEARN_version | status | note
-- | -- | -- | -- | -- | --
<strain_name> | B.1.221 | 1.0 | 01-02-2021 | passed_qc |  

edit20210207: corrected spelling

**Comment by aineniamh** [comment]
Hi, you're completely correct as we currently pull the pangoLEARN_version from the installed version as part of the environment. I've just pushed a commit to pangolin that if --datadir is used, it looks within that directory for a __init__.py file with the version number specified. If it finds it it then uses that, if not prints as Unknown. Thanks for pointing this out!
