### ISSUE TITLE
No longer specify number of threads?

### ISSUE THREAD

**Issue by charlesfoster** [cov-lineages/pangolin#136]
Hi,

Thanks for the great tool. 

Just one quick issue: after updating to pangolin v2.2.1, a script I maintain broke at the pangolin lineage assignment step. I looked into it, and it's the command line argument specifying the number of threads for pangolin (e.g., `-t 10`) that causes the script to error out. Using `pangolin -h` no longer shows `-t` or `--threads` as an option, but the README still lists both of those as possible command line arguments.

Can I confirm that there is no longer a need to specify the number of threads going forwards?

Thanks,
Charles

**Comment by aineniamh** [comment]
Okay, sorry for that! Threading isn't currently supported- but I've added the flag back in to catch use in pipelines as it seems to be causing issues. A warning is printed now that the `-t` option isn't currently in use, but using it won't break. We'll add multithreading support back in again in the future, but the current setup doesn't easily support it. 
https://github.com/cov-lineages/pangolin/releases/tag/v2.2.2
