### ISSUE TITLE
experiment: UShER as pangolin inference engine?

### ISSUE THREAD

**Issue by AngieHinrichs** [cov-lineages/pangolin#137]
Dear pangolin team,

First, thank you so much for providing pangolin and making it so easy to install and run.

Your README.md says "the pipeline has been written so that as more complex models are developed, the user will be able to choose which model to use to assign their lineages."  You may already be aware of [UShER](https://github.com/yatisht/usher), which can be used first to build a mutation-annotated tree data structure from Newick and VCF inputs and save it as a compact binary file (protobuf), and then to load in a previously saved protobuf and rapidly place one or more new sequences in the tree in well under one second per new sequence even for trees with hundreds of thousands of samples.  Of course it's even faster with smaller trees.  :)

I've been wondering about the possibility of using UShER as an alternative inference engine in Pangolin, and UShER author @yatisht is interested as well.  I imagine that might work as follows:

1. With pangoLEARN's lineages.metadata.csv and a mutation-annotated tree protobuf file as inputs, we find the node of the mutation-annotated tree that best corresponds to each lineage's set of training samples (ideally as a recent common ancestor).

2. We can drastically prune the mutation-annotated tree to keep only the nodes that correspond to lineages.  That's the new model.

3. Pangolin feeds the variants in new sequences to UShER with the little tree of lineage nodes; UShER's node placement is the lineage assignment.

The reality will be somewhat messier, but we think it's worth a try.

If we get something like that to work, do you have any suggestions for the best way to compare results in terms of speed, accuracy, RAM/disk etc?  

Angie, @yatisht and @russcd

**Comment by aineniamh** [comment]
Dear Angie, @yatisht and @russcd,

This sounds amazing! I saw Yatish present UShER at the COVID-19 Dynamics & Evolution meeting last October and thought it sounded like a really great tool! We had originally in pangolin 1.0 been using a phylo-placement approach using maximum likelihood with iqtree but it didn't scale well with the increase in number of sequences/ lineages. 

It would be straightforward to include a flag specifying assignment method that could use either UShER or the pangoLEARN decision tree. It sounds like UShER could be a cool alternative approach that might help overcome the scaling issue we had previously. 

I'd be very keen to discuss this further (@rambaut too!) and we can figure out the logistics of testing etc.

**Comment by AngieHinrichs** [comment]
Delighted to hear that you're interested!  I'll email about setting up a meeting.

**Comment by AngieHinrichs** [comment]
We are trying out step 1 with our own global trees ([one](https://hgwdev.gi.ucsc.edu/~angie/UShER_SARS-CoV-2/2021/02/01/) of fully public i.e. GenBank + COG-UK + CNCB sequences, [another](https://hgwdev.gi.ucsc.edu/~angie/public-2021-01-29.plusGisaid.nwk) with public + GISAID-only sequences, both constructed by starting with the final public release of [sarscov2phylo (13-11-20)](https://github.com/roblanf/sarscov2phylo/releases/tag/13-11-20) and adding newer sequences using UShER).  

We're also trying it out with the latest [COG-UK public tree](https://cog-uk.s3.climb.ac.uk/phylogenetics/latest/cog_global_tree.newick) and we assumed that would be pretty close to the tree that you're using - but that tree seems to have only ~145k of the ~172k sequences in lineages.metadata.csv .  (Still, 870 of the 873 lineages in our copy of lineages.metadata.csv are represented.  Our public tree has only 664.)

Just wanted to sanity-check -- the COG-UK public tree is not the tree that you're working with when you find samples to define a new lineage?  Is it a downsampled version, or independent?  (Either way it's still a useful point of comparison for ours.)

**Comment by aineniamh** [comment]
Delighted to close this issue! UShER now available with the `--usher` flag! Thanks so much @AngieHinrichs! Available with [pangolin 3.0](https://github.com/cov-lineages/pangolin/releases/tag/v3.0)

**Comment by AngieHinrichs** [comment]
Thank you so much for all your work on this @aineniamh and @rmcolq!  :)  🎉
