### ISSUE TITLE
P.2 Lineage SNVs

### ISSUE THREAD

**Issue by sishirsubedi** [cov-lineages/pangolin#138]
From the reference paper for P.2  (https://www.medrxiv.org/content/10.1101/2020.12.23.20248598v1 ), the following are lineage defining SNVs-
'C100T':'5UTR',
'C28253T':'ORF8-F120F',
'G28628T':'N-A119S', 
'G28975T':'N-M234I',
'C29754T':'3UTR'

Pangolin seems to be using the following SNVs-
aa:orf1ab:L3468V
aa:orf1ab:L3930F
aa:S:E484K
aa:S:V1176F
aa:N:A119S

Only 'N-A119S' is common between these two groups. 

Where can we find a list of lineage defining SNVs for P.2 used by Pangolin?

Thanks.

**Comment by aineniamh** [comment]
The full set of defining mutations we have are:
```
ORF1ab:
synC100T
L3468V
synC11824T
L3930F
spike:
E484K
V1176F
ORF3a:
C28253T
N:
A119S
```
We just use amino acid substitutions in coding regions as defining sites because many of the sequencing and assembly errors seem to occur at the ends of the genome. Hope that helps!

**Comment by sishirsubedi** [comment]
Thank you very much for the prompt reply.
