### ISSUE TITLE
pangolin uses too many threads

### ISSUE THREAD

**Issue by erinyoung** [cov-lineages/pangolin#139]
It looks like now that pangolin does not support the `--threads` option anymore, it automatically detects how many cores a system has and goes from there. My system has 48 cores, but I cannot always devote all 48 cores to running pangolin because I am also running other things. Thus, I cannot get pangolin to work anymore.

Here's the top of my error message.

```
Job counts:
	count	jobs
	1	add_failed_seqs
	1	all
	1	datafunk_trim_and_pad
	1	minimap2_check_distance
	1	minimap2_to_reference
	1	overwrite
	1	pangolearn
	1	parse_paf
	1	type_variants_b117
	1	type_variants_b1351
	1	type_variants_p1
	1	type_variants_p2
	12
Job counts:
	count	jobs
	1	parse_paf
	1
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030876 max
```

**Comment by aineniamh** [comment]
Hi @erinyoung , 
Thanks for posting! This is unusual behaviour, with the recent change in threads effectively nothing has changed in the inner workings of pangolin in relation to threads, the threads flag hasn't been operational for a while (noted in #99 a while ago). I removed the flag, but realised that was breaking some pipelines (#136). In our latest release the flag is back but pangolin just prints a warning that it's just using 1 thread. 

I don't recognise the library printing that error, pangolin does just run one thread now. Chatting to @emilyscher who wrote the pangolearn.py module, she doesn't recognise it either. We found a couple of issues relating to this library [here](https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable
) and [here](https://github.com/xianyi/OpenBLAS/issues/1668). 
It may be something related to numpy or pandas. 

I suggest doing a full rebuild of the conda environment to see if that fixes what I can assume is a versioning issue?

**Comment by kapsakcj** [comment]
@erinyoung are you experiencing this error with one of the StaPH-B docker images for Pangolin? (I assume yes, but just want to be sure)

If so - I'd like to adjust the docker image(s) to prevent this error. 

I've heard about strikingly similar OpenBLAS errors with `medaka` recently too....which is also python based and uses numpy so I wouldn't be surprised if that's the root cause of the issue.

Thanks for the info and links, @aineniamh . And of course a huge thank you to you, Emily, and all others involved for your hard work into developing and maintaining this tool!
