### ISSUE TITLE
pangolearn github is not responding

### ISSUE THREAD

**Issue by igortru** [cov-lineages/pangolin#140]
may be you know answer :
could you ,please, explain how exactly decision_tree_rules.txt was built?

**Comment by aineniamh** [comment]
Hi, all our source code for the training of the pangoLEARN model and creation of output files is available in [pangoLEARN-training](https://github.com/cov-lineages/pangoLEARN-training). Previously we had it hosted (and it's still hosted) as a packaged script in [cov-support](https://github.com/cov-lineages/cov-support) but thought for transparency to separate it into its own repository too.

**Comment by igortru** [comment]
Thank you, I can go deeper into  details myself , I see almost everything I need.

but I have  some short questions for you.

1) position which you print in reformatRule 
Is it real position on reference  or positions after alignment 
and need special adjustments ?  which reference you are using ? MN908947.3?

def reformatRule(sign, name, threshold):
	position = name.split("_")[0]
	letter = name.split("_")[1]

	symbol = "=="
	if sign == "<=":
		symbol = "!="
	return position + symbol + "'" + letter + "'"
	
2) which positions in reference genomes used for classification
I don't see it as open source : indiciesToKeep

	
def encodeSeq(seq, indiciesToKeep):
	dataLine = []
	for i in indiciesToKeep:
		if i < len(seq):
			dataLine.extend(clean(seq[i], i))

	return dataLine
	
Anyway, thank you!

**Comment by aineniamh** [comment]
I'm going to assign this issue to @emilyscher as she wrote that particular code you're talking about!

**Comment by emilyscher** [comment]
The position in the script you're referencing comes from the model headers, which are generated based on the sequence alignment in the model training script. You can check that out [here](https://github.com/cov-lineages/cov-support/blob/master/cov_support/scripts/pangoLEARNDecisionTree_v1.py) to see how they're generated.

**Comment by igortru** [comment]
look...
we are talking about your tree
not my tree and my alignment.
I want to see your complete alignment 
or just aligned reference genome 
from it ,
IF complete alignment can not be published according your agreement with GISAID.

**Comment by aineniamh** [comment]
As you're probably aware we can't share sequences because of the gisaid user agreement. This includes alignments and bam files etc. We have an [anonymised reference sequence](https://github.com/cov-lineages/pangolin/blob/master/pangolin/data/reference.fasta) used as part of pangolin and this is what our alignment is based off of.

**Comment by igortru** [comment]
are you serious?how I can trust your results?
if you can’t provide location of gaps
on anonymised reference sequence?
or  this sequence don’t have gaps in your alignement
or it is secret as well?
secret gaps positions... very intriguing situation,right?

**Comment by aineniamh** [comment]
Not so intriguing, you can get the sequences from GISAID and then run the exact scripts on the data, minimap2, gofasta. All our code is open source for you to replicate our results at your leisure!

**Comment by igortru** [comment]
sorry, I can't get data from GISAID.

**Comment by aineniamh** [comment]
Anyone can, as far as I know you just need to register for an account. But not my field of expertise, i suggest contacting them. Everything we are permitted to share is through this organisation on github. Best of luck!
