### ISSUE TITLE
How close for two lineages?

### ISSUE THREAD

**Issue by Shaokang123** [cov-lineages/pangolin#141]
Hi, 
May I ask how many lineages in Pangolin so far? Are there any SNP distance threshold between two lineages? Thanks.
Regards,
Shaokang

**Comment by aineniamh** [comment]
Hi @Shaokang123, we report that information here with every lineage designation release: https://github.com/cov-lineages/pango-designation/releases/tag/v1.0.5

Currently 880 different lineages in the pango lineage system. 
There's currently only 1 SNP required but the cluster should be associated with an epidemiological event (like an introduction to a distinct geographic area for instance).

Hope that helps!

**Comment by Shaokang123** [comment]
@aineniamh great, that's very helpful. Thanks.
