### ISSUE TITLE
Possible issue with 2.2.3

### ISSUE THREAD

**Issue by krepsen** [cov-lineages/pangolin#144]
Not sure what is the issue, but we are getting an error with the new 2.2.3 update, see below.
Could it be a problem with the minimap2 version?
We have not experienced problems with Pangolin before.
Downgrading to 2.2.2 solved the issue.

```
Error in rule align_to_reference:
    jobid: 9
    output: /media/data/Oppsett62A/Grid36/Oppsett62A/Oppsett62A_summaries/fasta/sequences.aln.fasta
    log: /media/data/Oppsett62A/Grid36/Oppsett62A/Oppsett62A_summaries/fasta/logs/minimap2_sam.log (check log file(s) for error message)
    shell:
        
        minimap2 -a -x asm5 -t 1 /home/ngs2/anaconda2/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta /tmp/tmpkr6z6dvh/mappable.fasta |         gofasta sam toMultiAlign             --reference /home/ngs2/anaconda2/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta             --trimstart 265             --trimend 29674             --pad > /media/data/Oppsett62A/Grid36/Oppsett62A/Oppsett62A_summaries/fasta/sequences.aln.fasta
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message
```

**Comment by aineniamh** [comment]
Hi, I think this isn't the full error message, but did you try updating the conda environment with
```
conda env update -f environment.yml
```
It may be you need to install gofasta!
We've got full updating docs here:
https://cov-lineages.org/pangolin_docs/updating.html

Let me know if that solves the problem, if not we can revisit!

**Comment by krepsen** [comment]
Thanks, that fixed the issue and it seems to be working
I think the issue was that we used "pangolin --update" from 2.2.2 to 2.2.3
This only updates the pangolin and pangolearn, not gofasta (and snakemake - see other issue posted today)...

**Comment by aineniamh** [comment]
Hi @krepsen, glad it's working for you now! Yes, the --update flag only updates minor releases, we've actually updated from 2.2.2 to 2.3, so it's a more significant release tag requiring an environment update! I've added that information to the update docs on the website here: https://cov-lineages.org/pangolin_docs/updating.html
