### ISSUE TITLE
The pangolin don´t work with my .fasta files

### ISSUE THREAD

**Issue by afmarti** [cov-lineages/pangolin#147]
When I do the upload of my files, the software return this information:

FAILED: Sequence unable to be processed with Pangolin (unknown error)

I have already verified the files, and they are ok. It happens with 5 specific files, probably associate with P1 lineage, according to with mutations found. With the other 30 files, the process was ok.

**Comment by aineniamh** [comment]
I think this issue should be resolved now with the latest updates, going to close it now!
