### ISSUE TITLE
QC issues - pangolin prep for llama

### ISSUE THREAD

**Issue by beauschaeffer** [cov-lineages/pangolin#148]
Hello Áine and team,

I am interested in getting LLAMA up and running on my system for contextualizing healthcare worker and patient sampled SARS-CoV-2 sequences. If I am understanding the documentation correctly, LLAMA needs a directory of data containing the following files: `global.tree`, `alignment.fasta`, and `metadata.csv` (associated metadata with minimally the name of the sequences in the tree/ alignment and a lineage designation). I have downloaded the Audacity tree from GISAID and associated metadata along with the MSA masked alignment per Rob Lanfear's [guide](https://github.com/roblanf/sarscov2phylo). This associated metadata does not include lineage designations so I am attempting to use PANGOLIN to generate lineage designations for the MSA masked alignment, however, `no query sequences have passed the qc` for reason `sequence too short`. I am also receiving the same error message for my set of clinical samples.

Do you have any idea why I may be receiving these error messages?
Additionally, if the above pipeline I have described sounds like I am misunderstanding any of the steps please let me know.

Thank you for your dedication to these programs! Cheers.

**Comment by aineniamh** [comment]
Hi @beauschaeffer, by default pangolin has a threshold of 10,000 bases minimum for assignment (this can also be configured) as it's designed for whole-genome alignments. 

If it's just the lineage assignments you're looking for they're hosted for each GISAID sequence daily: Assignments: [here](https://github.com/cov-lineages/lineages-website/blob/master/_data/lineages.metadata.csv) and designations [here](https://github.com/cov-lineages/pango-designation). The designations are the curated lineages, whereas the assignments are the pangolin-assigned lineages. 

Hope that might be helpful for you! 

I realise the setup for llama is quite involved, but we're hoping to move to an graphical interface model that will make this much more straightforward.

**Comment by rmcolq** [comment]
Hi @beauschaeffer - I'm closing this issue as stale, but feel free to reopen or start a new issue if you want more help
