### ISSUE TITLE
--threads flag used, but threading not currently supported

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#151]
Hi,

I get the following message with version 2.3.2
--threads flag used, but threading not currently supported. Continuing with one thread.

I didn't have this problem with previous version

Regards
Eric
 *******************************************************************************************************
(pangolin) [foueri01@inspq.qc.ca@slbio00d 2021-02-23]$ pangolin -h
usage: pangolin <query> [options]

pangolin: Phylogenetic Assignment of Named Global Outbreak LINeages

positional arguments:
  query                 Query fasta file of sequences to analyse.

optional arguments:
  -h, --help            show this help message and exit
  -o OUTDIR, --outdir OUTDIR
                        Output directory. Default: current working directory
  --outfile OUTFILE     Optional output file name. Default: lineage_report.csv
  --alignment           Optional alignment output.
  -d DATADIR, --datadir DATADIR
                        Data directory minimally containing a fasta alignment
                        and guide tree
  --tempdir TEMPDIR     Specify where you want the temp stuff to go. Default:
                        $TMPDIR
  --no-temp             Output all intermediate files, for dev purposes.
  --decompress-model    Permanently decompress the model file to save time
                        running pangolin.
  --max-ambig MAXAMBIG  Maximum proportion of Ns allowed for pangolin to
                        attempt assignment. Default: 0.5
  --min-length MINLEN   Minimum query length allowed for pangolin to attempt
                        assignment. Default: 10000
  --panGUIlin           Run web-app version of pangolin
  --verbose             Print lots of stuff to screen
  -t THREADS, --threads THREADS
                        Number of threads
  -v, --version         show program's version number and exit
  -pv, --pangoLEARN-version
                        show pangoLEARN's version number and exit
  --update              Automatically updates to latest release of pangolin
                        and pangoLEARN, then exits

(pangolin) [condauser@slbio00d pangolin]$ pangolin -v;pangolin -lv;pangolin -pv
pangolin 2.3.2
usage: pangolin <query> [options]
pangolin: error: unrecognized arguments: -lv
pangoLEARN 2021-02-21

**Comment by aineniamh** [comment]
Yes, we no longer support threading in pangolin but have the flag in as its removal broke some users pipelines (previous issues #136 and #99).
