### ISSUE TITLE
Error massage after upgrade

### ISSUE THREAD

**Issue by steinbrl** [cov-lineages/pangolin#153]
Hey,

I got this error massage after an pangolin upgrade. Before it was working flawless...

(pangolin) lars@helmut:~/Desktop/SARS-CoV-2/Run_16/pangolin$ pangolin Run16_align.fasta
Found the snakefile
The query file is:/home/lars/Desktop/SARS-CoV-2/Run_16/pangolin/Run16_align.fasta
Looking in /home/lars/NGS/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data for data files...

Data files found
Trained model:	/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/decisionTree_v1.joblib
Header file:	/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
Lineages csv:	/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/lineages.metadata.csv
Job counts:
	count	jobs
	1	add_failed_seqs
	1	align_to_reference
	1	all
	1	minimap2_check_distance
	1	overwrite
	1	pangolearn
	1	parse_paf
	1	type_variants_b117
	1	type_variants_b1351
	1	type_variants_p1
	1	type_variants_p2
	11
Job counts:
	count	jobs
	1	parse_paf
	1
/bin/bash: gofasta: command not found
[M::mm_idx_gen::0.004*1.39] collected minimizers
[M::mm_idx_gen::0.006*1.24] sorted minimizers
[M::main::0.006*1.24] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.006*1.22] mid_occ = 100
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.007*1.21] distinct minimizers: 2952 (100.00% are singletons); average occurrences: 1.000; average spacing: 10.130
[Wed Feb 24 15:26:55 2021]
Error in rule align_to_reference:
    jobid: 9
    output: /tmp/tmp45g2jcgk/sequences.aln.fasta
    log: /home/lars/Desktop/SARS-CoV-2/Run_16/pangolin/logs/minimap2_sam.log (check log file(s) for error message)
    shell:
        
        minimap2 -a -x asm5 -t 1 /home/lars/NGS/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta /tmp/tmp45g2jcgk/mappable.fasta |         gofasta sam toMultiAlign             --reference /home/lars/NGS/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta             --trimstart 265             --trimend 29674             --pad > /tmp/tmp45g2jcgk/sequences.aln.fasta
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by domenico-simone** [comment]
The error is that `gofasta` is missing in the update. I have had the same error and I've sorted it out by installing it in my conda environment with:

```bash
conda install -c bioconda gofasta
```

**Comment by steinbrl** [comment]
Thank you! I solved the problem by deleting the environment and reinstall from GIT. Now it works again.
