### ISSUE TITLE
Incorrect classification for B.1.429

### ISSUE THREAD

**Issue by SVN-PhD** [cov-lineages/pangolin#156]
I was checking some older sequences in pangolin 2.3.2. The software calls these sequences as B.1 although they share all the characteristic mutations for B.1.429. Their GISAID accessions are EPI_ISL_804942 and EPI_ISL_804943. Thanks!

**Comment by aineniamh** [comment]
Hi @SVN-PhD thanks for messaging, I will look into this today!

**Comment by davidrasm** [comment]
I'm also still seeing the same issue using v. 2.3.2 and pangoLearn_version 2021-02-21. All GISAID samples previously assigned to B.1.427 or B.1.429 using PLv 2021-02-12 are now assigned to lineage B.1.

**Comment by aineniamh** [comment]
We've just done a major overhaul of pango lineages (has taken quite a long time as we've manually curated the entire gisaid + cogUK combined dataset). The latest designations are now available at https://github.com/cov-lineages/pango-designation. The pangolin model is being trained now to include these updates but with the update to the model to include more recent diversity we will hopefully see a significant increase in assignment accuracy.

**Comment by SVN-PhD** [comment]
It looks like the update fixed the issue, go raibh maith agat.
