### ISSUE TITLE
Pangolin website issue

### ISSUE THREAD

**Issue by ZohrehFattahi** [cov-lineages/pangolin#158]
Hi.
I am using the Pangolin website to assign lineages.
I have some Fasta files with only D138Y mutation and no other mutations of the P.1 variant.
Unfortunately, the website assigns the P.1 variant for those while I am sure that these are not the P.1 variant sequences.
Would you please kindly help me in this matter.
I am trying to install the Linux version of Pangolin to see if the lineage designation changes or not, however I have not been successful so far.
Is the website version of Pangolin accurate enough?
Do we have to use the Linux version?

**Comment by aineniamh** [comment]
Hi @ZohrehFattahi, could you share the sequence with me and I will test it (feel free to anonymise if needed)? 
The web and command line versions should give the same result, but the web app may lag a little with updating versions.

**Comment by ZohrehFattahi** [comment]
Sure, I will now email some of them to you.
This email is OK? aine.otoole@ed.ac.uk

**Comment by aineniamh** [comment]
Hi @ZohrehFattahi, sorry I missed this that's the correct email!

**Comment by ZohrehFattahi** [comment]
Dear @aineniamh, I am using the website version and it cannot assign to some Fasta files.
Mostly uses B.1.1 or B.1, even for Fasta files that I have previously checked and already assigned the correct lineage using the webiste.
Is this because of the new update or is the website still not updated and the issue is because of that?
