### ISSUE TITLE
version number in __init__.py

### ISSUE THREAD

**Issue by luenling** [cov-lineages/pangolin#159]
Dear Áine,

Thanks for providing this amazing tool - we use it to classify all our incoming sequences.
Just a minor thing - I think the version number in ``__init__.py`` is set to 2.2.3 instead of 2.3.2 :)

All the best and thanks again for your great work,
Lukas

**Comment by aineniamh** [comment]
Ha, that's my fault. I'll fix it now, thanks for pointing it out!
