### ISSUE TITLE
Official Docker image?

### ISSUE THREAD

**Issue by philiptzou** [cov-lineages/pangolin#160]
Hello,

Is this your official Docker image: https://hub.docker.com/r/covlineages/pangolin? If yes, will it be updated timely? Thanks!

**Comment by marchoeppner** [comment]
Since there hasn't been a reply - Pangolin is part of Bioconda and through this gets regular updates on biocontainers https://quay.io/repository/biocontainers/pangolin?tag=latest&tab=tags

These are Docker containers using this url format: docker://quay.io/biocontainers/pangolin:2.3.2--py_0

**Comment by kapsakcj** [comment]
Definitely unofficial and not maintained or supported by the pangolin dev team, but I'm helping to maintain docker images that have pangolin and pangoLEARN https://hub.docker.com/r/staphb/pangolin You can find the dockerfiles in the linked GitHub repo: https://github.com/StaPH-B/docker-builds/tree/master/pangolin

We have a GitHub actions workflow that automatically creates a new dockerfile & pushes new docker images to dockerhub when there is a new pangolin or pangoLEARN version released, so it should stay up to date.

**Comment by aineniamh** [comment]
Hi @philiptzou, I missed this! We have github actions setup ([here](https://github.com/cov-lineages/pangolin/blob/master/.github/workflows/push_dockerhub.yml)) that should automatically maintain the docker image when a new release is tagged. 

I'm not personally a docker user, but between that and the image @kapsakcj maintains (thanks for that too!) there should always be an up-to-date docker image available!
