### ISSUE TITLE
Wuhan-Hu-1 is recognized as lineage B

### ISSUE THREAD

**Issue by philiptzou** [cov-lineages/pangolin#161]
Shouldn't it be A?

![](https://user-images.githubusercontent.com/809865/110583181-25530100-8122-11eb-89ad-35d0ed86e091.png)

**Comment by rambaut** [comment]
Lineages A and B represent the two haplotypes first sequenced in Wuhan. Lineage A is 2 SNPs closer to the closest non-human virus, RaTG13 suggesting it may be the more ancestral lineage.

**Comment by philiptzou** [comment]
@rambaut Thanks!
