### ISSUE TITLE
Use of PANGO strain names on Wikidata and Wikipedia

### ISSUE THREAD

**Issue by lubianat** [cov-lineages/pangolin#162]
Hello, 

I manage part of the WikiProject COVID-19 on Wikidata and I am working towards improving linked open data on SARS-CoV-2 strains. I see a nice table on https://github.com/cov-lineages/lineages  but I could not find an updated table with the main lineages and their PANGO names. Could you help me with that?

Of course, all information would cite the source and improve the visibility of your great project :) 

Best, 

Tiago

**Comment by aineniamh** [comment]
Hi Tiago, 

We're hosting the latest lineages with descriptions and designations here at [pango-designation](https://github.com/cov-lineages/pango-designation). 

Hope that helps! 

Áine
