### ISSUE TITLE
Suggestion for more verbose lineage definitions

### ISSUE THREAD

**Issue by taboadae** [cov-lineages/pangolin#163]
Hi folks,

I love the lineage assignment tool and know some of the issues with implementing a hierarchical nomenclature. Having had to do a similar thing before, one suggestion that I have would be to consider an additional version of lineage names that is more verbose and that sorts the hierarchical nature of the lineages properly. To do this, consider adding leading zeroes to each step in the hierarchy and consider filling empty steps of the hierarchy as well, as per these examples:
B.1.88.1 --> B.01.088.001
B.1.526 --> B.01.526.000
B.1.9 --> B.01.009.000
A.1 --> A.01.000.000
A --> A.00.000.000

In doing this, each lineage ends up with an identical format that also sorts properly. I've done the suggested format for all unique lineages as per today's (2020-03-16) GISAID metadata table. 

[Pangolin_lineages.txt](https://github.com/cov-lineages/pangolin/files/6151961/Pangolin_lineages.txt)

Certainly, the two names are functionally equivalent and the original name is short and sweet, but the new version is more machine-friendly.

All the best and keep up the great work!

Ed

**Comment by aineniamh** [comment]
Hi @taboadae, this is something that @oliverpybus and @rambaut could perhaps discuss, but my initial thoughts are that the difficulty with the system you suggest is that you're explicitly assuming how many 0's will be needed. For example, B.1.526 -->B.01.526.000 works, but what about B.1.1234.1? Do all lineage names then need to be modified when we require greater numbers of digits? 

I have some code that I use to sort lineage names if that's helpful: [here](https://github.com/cov-lineages/grinch/blob/7652c7b232a124cb22676e5104d45c3135460789/grinch/scripts/update_website.py#L197).

**Comment by oliverpybus** [comment]
Hi @taboadae
Thanks for your idea. I think the correct solution is better sorting scripts rather than changing lineage names. In addition to Áine's important point we (1) want to keep lineage name changes to a minimum, (2) make the names as simple as possible, (3) make them as unambiguous as possible (i.e. we don't want two versions of each name, with and without zeroes). There's also the issue of ".000" pre-empting a descendant that hasn't yet been observed, and may never occur.
If like me you love MS Excel  ;-)  then replace the dots with tabs, import as CSV, then custom sort: alphabetical sort column 1 then numerical sort column 2, and so on. 
Oli

**Comment by taboadae** [comment]
Hi,

This is a valid concern. The way to future-proof the more verbose lineage
designation is to provide ample room within each hierarchical layer based
on what you already know from the more than 750,000 genomes on GISAID, by
looking at the existing lineage calls, the rate of new lineages generated,
and how they are accommodated within each level of the hierarchy as
lineages split. Because the proposed verbose designation (Pangolin.v2) is
not for rapid human consumption, it can incur the overhead of extra digits
if necessary so that the lineages have a more regularized syntax.

You can still keep the current form of lineage names for rapid
communication (Pangolin.v1). You'll be shocked to find out that most
working epidemiologists dealing with the real-life implications of variants
of concern are deeply stuck in the world of Excel, sad to say!!! And the
current lineage designations sort poorly in a standard spreadsheet.
Assuming that "clouds" of related lineages may be important to track as
they diversify when the virus spreads, the verbose designation makes this
task a little easier.

Best,

Ed

**Comment by oliverpybus** [comment]
Thanks. There are advantages and disadvantages to any proposed change. In this instance I don't think the benefits of improved sortability in Excel outweigh the costs (which include potentially breaking existing workflows ). We aim to balance human- and machine-readability (lineage aliasing is one example of this compromise). If this is a very common problem we could look into creating an Excel macro to aid sorting.
