### ISSUE TITLE
incorrect version being reported again?

### ISSUE THREAD

**Issue by russellsmithies** [cov-lineages/pangolin#164]
When I checkout the latest 2.3.2 release, `pangolin -v` reports version `pangolin 2.3.3`
Not sure how this happens as it looks correct in `pangolin/__init__.py` on Github.

**Comment by aineniamh** [comment]
Hi @russellsmithies, the version number seems to be printing correctly for me (v2.3.7 now). Where are you downloading pangolin from?

**Comment by russellsmithies** [comment]
> 
> 
> Hi @russellsmithies, the version number seems to be printing correctly for me (v2.3.7 now). Where are you downloading pangolin from?

This was in release 2.3.2. With the frequency of version updates of pangolin I'd expect it to be fixed now :-)
Perhaps some basic testing is in order to check that the version number being returned is the same as that specified in the release? It's not the first time this has happened, and given that pangolin is key in the curent COVID workflows it's esential that it be correct to ensure reproducibility in future.
