### ISSUE TITLE
error minimap2 after update 

### ISSUE THREAD

**Issue by genomicsurveillance** [cov-lineages/pangolin#166]
After upgrading to version 2.3.4, minimap2 is experiencing problems.. is there anyone who is exhibiting the same problem?
MacOs
```
Error in rule align_to_reference:
    jobid: 10
    output: /tmp/tmplz3k8usw/sequences.aln.fasta
    log: ./logs/logs/minimap2_sam.log (check log file(s) for error message)
    shell:
        
        minimap2 -a -x asm5 -t 1 /miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta /tmp/tmplz3k8usw/mappable.fasta |         gofasta sam toMultiAlign             --reference /miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta             --trimstart 265             --trimend 29674             --pad > /tmp/tmplz3k8usw/sequences.aln.fasta
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message
```

**Comment by dabadgarcia** [comment]
Same here, using CentOS.

**Comment by AngieHinrichs** [comment]
@genomicsurveillance @dabadgarcia what happens if you run this sequence of commands?:

```
conda activate pangolin
which minimap2
which gofasta
```
If the last command complains that gofasta is not found, then it means `pangolin --update` wasn't quite sufficient and you need to run a more complete update manually as described in the README's [Updating pangolin](https://github.com/cov-lineages/pangolin#updating-pangolin).  (The `conda env update -f environment.yml` step will install gofasta.)

**Comment by aineniamh** [comment]
Hi all, in the latest push to pangolin I now explictly check for dependencies `gofasta`, `snakemake-minimal` and `minimap2`. If they're not in your environment pangolin will now exit out with an informative message. 

The `--update` flag only updates pangolin and pangoLEARN, which for most releases is enough. However recently we had a major release to pangolin, which required an update to the conda environment as well. It's described in the [release notes](https://github.com/cov-lineages/pangolin/releases/tag/v2.3.0), but I realise there are so many releases it's unlikely people will read these! 

The explicit check for dependencies will hopefully clear that up now though (pangolin version 2.3.7 onwards) and help for any future updates.
