### ISSUE TITLE
Update README to reflect deletion of -lv?

### ISSUE THREAD

**Issue by GodloveD** [cov-lineages/pangolin#170]
The readme suggests 3 tests following installation to ensure that the installation proceeded properly.  Of these it seems that the third (`-lv`) has been removed?  Is this correct?  Can the README.md be updated to reflect this change?  

And also, is there a different way to check the lineage version that I should run?  Thanks!

**Comment by aineniamh** [comment]
Thanks for pointing this out- I'd updated the website previously but not the GitHub, have amended this now. 
Full docs are available here: https://cov-lineages.org/pangolin_docs/installation.html

Lineages have been replaced now by pangoLEARN. Latest releases of pangolin don't need a lineages version, just the pangoLEARN model, which is now on release [2021-04-01](https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-04-01).
