### ISSUE TITLE
P.3 

### ISSUE THREAD

**Issue by alantsangmb** [cov-lineages/pangolin#171]
Might I know which reference sequences are used for config_p.3.csv?
Since I cannot find aa:N:P80R mutation from the preprint:
https://www.medrxiv.org/content/10.1101/2021.03.03.21252812v2

Thank you.

**Comment by aineniamh** [comment]
Hi @alantsangmb, all the sequences that have been designated are posted up on the [pango-designation](https://github.com/cov-lineages/pango-designation) repository. Descriptions are in the lineage_notes.txt file and individual sequence names are in lineages.csv.

**Comment by alantsangmb** [comment]
I see there is "Áine" in the example sequence.
What is the meaning of "Áine".
Thank you.

**Comment by aineniamh** [comment]
Hi @alantsangmb, if you're referring to the curation notes file: 
```
Lineage	Rough number of SNPs	Example sequence	Active/ Unobserved/ Inactive	Designator	Size (roughly)	Description
A	0			Wuhan/WH04/2020		Active				Áine		4403		Root of the pandemic lies within lineage A. 
```
Áine refers to the Designator (it's my name), the example sequence is Wuhan/WH04/2020 for this first line.
