### ISSUE TITLE
B.1.1.316 and S:E484K

### ISSUE THREAD

**Issue by peich69** [cov-lineages/pangolin#174]
Hi,
Today we use PangoLEARN (v.2021-04-21) to classify some fasta files and we retrieve the lineage B.1.1.316.
Looking at the documentation https://cov-lineages.org/lineages/lineage_B.1.1.316.html in the “Description” field says “International lineage with E484K mutation”.
Our sequence doesn’t have the S:E484K variant. Trying to understand why it happened, I’ve found two closed issues [#17](https://github.com/cov-lineages/pango-designation/issues/17), [#18](https://github.com/cov-lineages/pango-designation/issues/18).
Considering these issues, lineage R.1 and R.2 have S:E484K.
So, all of three lineages, B.1.1.316, R1 and R2 should have the S:E484K.
I can't understand why my sequence is assigned to this lineage if is lacking that variant.
Moreover, I have download the 763 sequences assigned to B.1.1.316 at GISAID and only one has the S:E484K variation.
I would appreciate any comment that helps me to understand what I'm doing wrong.
Thanks

**Comment by peich69** [comment]
Hello,
I would appreciate to know if some advance has been done with this issue. I am wondering if you need some extra data or something.
Thanks

**Comment by aineniamh** [comment]
Hi @peich69, we answer lineage designation requests and queries at the pango-designation repository: https://github.com/cov-lineages/pango-designation/issueshttps://github.com/cov-lineages/pango-designation/issues

Could you please post your issue in that repository as this is the repo for software bugs and requests and to maintain transparency we want to have lineage issues record in the designation repo. Thanks for your understanding.

**Comment by peich69** [comment]
> 
> 
> Hi @peich69, we answer lineage designation requests and queries at the pango-designation repository: https://github.com/cov-lineages/pango-designation/issueshttps://github.com/cov-lineages/pango-designation/issues
> 
> Could you please post your issue in that repository as this is the repo for software bugs and requests and to maintain transparency we want to have lineage issues record in the designation repo. Thanks for your understanding.

Oops, sorry for any inconvenience.

**Comment by aineniamh** [comment]
No worries, thanks for understanding! I'm also looking into this issue for you, but we just need to have the record at the other repository!
