### ISSUE TITLE
Two different variants are given the same lineages

### ISSUE THREAD

**Issue by vaddanki69** [cov-lineages/pangolin#178]
Hi,

I have identified several new variants.

I tried to upload two (2) distinct variants:

(1) Variant with the following mutations in the spike protein: H69-/V70- | Y144- | N501Y | A570- | -572D | D614G | P681H | T716I | S982A | D1118H | D1199V (GISAID IDs: EPI_ISL_1607999, EPI_ISL_1608028) which occurred in the last month, primarily in Belgium. 

(2) Variant with the following mutations in the spike protein: H69-/V70- | Y144- | N148T | N501Y | A570- | -572D | D614G | Q677H | P681H | T716I | S982A | D1118H (GISAID IDs: EPI_ISL_1615940, EPI_ISL_1631373 which occurred in the last month, primarily in United Kingdom. 

I tried to upload proper FASTA files into the Pangolin tool (https://pangolin.cog-uk.io/) for both these distinct variants. However, it is giving me the lineage as B.1.1.7, which has different set of mutations in the Spike protein.

Can you please review and let me know if you notice any issues. Also, please let me know how to get new lineages for each distinct variant. Is there any API, I could use to submit new distinct variant fasts and receive the new lineage names?

Regards

[EPI_ISL_1607999 - Copy.txt](https://github.com/cov-lineages/pangolin/files/6402300/EPI_ISL_1607999.-.Copy.txt)
[EPI_ISL_1615940 - Copy.txt](https://github.com/cov-lineages/pangolin/files/6402301/EPI_ISL_1615940.-.Copy.txt)

**Comment by rambaut** [comment]
The spike mutations in these are indicative of these being in the `B.1.1.7` lineage. Plus they have N: D3L and ORF8: Q27stop and the NSP6 deletion.
