### ISSUE TITLE
Discrepancy in version reporting

### ISSUE THREAD

**Issue by olsonanl** [cov-lineages/pangolin#179]
Hi - I just build pangolin 2.4 from the github release; I see there is a discrepancy in version reporting:

```
$ /scratch/olson/xbuild/bin/pangolin -v
pangolin 2.4
$ /scratch/olson/xbuild/bin/pangolin -pv
pangoLEARN 2021-04-28
```

But

```
$ cat lineage_report.csv
taxon,lineage,conflict,pangoLEARN_version,pango_version,status,note
SRR11587603,B.1,0.0,2021-04-28,v1.1.23,passed_qc,
```

Command line shows 2.4 (as I expected), but the pango_version field in the generated data file is v1.1.23.

thanks,
Bob

**Comment by aineniamh** [comment]
Hi Bob, that number refers to the pango-designation version that describes the input data used to train the model, found here: https://github.com/cov-lineages/pango-designation.
