### ISSUE TITLE
Lineage P.1 has 17 SNPs in note field, but only 16 in csv output

### ISSUE THREAD

**Issue by pmenzel** [cov-lineages/pangolin#180]
Hi,

the file `variants_p1.csv` has 16 columns with SNPs for the P.1 variant:
```
query,ref_count,alt_count,other_count,fraction_alt,aa:orf1ab:S1188L,aa:orf1ab:K1795Q,del:11288:9,aa:S:L18F,aa:S:T20N,aa:S:P26S,aa:S:D138Y,aa:S:R190S,aa:S:K417T,aa:S:E484K,aa:S:N501Y,aa:S:H655Y,aa:S:T1027I,aa:orf3a:G174C,aa:orf8:E92K,aa:N:P80R
```

whereas the `note` column in the `report.csv` shows `x/17` detected SNPs for this lineage, probably because of the hard-coded `17` here:
https://github.com/cov-lineages/pangolin/blob/8bdd9350695bde9b04f8a90f3efd2b5182a087dc/pangolin/scripts/pangolearn.smk#L307

**Comment by aineniamh** [comment]
Hi @pmenzel, thanks for catching that! I've updated it in the master now and the next release will have the changes incorporated.

**Comment by whottel** [comment]
Similar to the issue originally mentioned here. 
pangolearn.smk sets the denominator for P.1 to 16 even though there are only 15 listed in config_p.1.csv
