### ISSUE TITLE
Pangolin output missing failed qc samples

### ISSUE THREAD

**Issue by santoshe1** [cov-lineages/pangolin#181]
Hi,

Versions - **pangolin v2.4 and pangoLEARN 2021-04-28**

I observe in the final pangolin output csv file, it is missing to report the actual failed qc samples and its showing redundant results such as:

barcode90,B.1,0.0,2021-04-28,v1.1.23,passed_qc,
barcode90,None,0,2021-04-28,v1.1.23,fail,failed_to_map
barcode90,None,0,2021-04-28,v1.1.23,fail,failed_to_map
barcode90,None,0,2021-04-28,v1.1.23,fail,failed_to_map
barcode90,None,0,2021-04-28,v1.1.23,fail,failed_to_map
barcode90,None,0,2021-04-28,v1.1.23,fail,failed_to_map

Whereas the failed were other barcodes and its not reported in the csv. This looks a possible bug, Could you fix the issue?

**Comment by aineniamh** [comment]
Hi @santoshe1, I've just tracked down the bug and pushed the changes to the master branch, and will be included in the next release later today. Thanks so much for spotting it!
