### ISSUE TITLE
New issue with pangolin v2.3.8

### ISSUE THREAD

**Issue by ZohrehFattahi** [cov-lineages/pangolin#183]
Dear @aineniamh, 
I am using the pangolin website v2.3.8 and it cannot assign the correct lineage to some Fasta files I use.
It assigns mostly B.1.1 or B.1. to them.
I also checked some other similar (but previously assigned correctly) Fasta files and again got the B.1.1 or B.1 record instead of the correct lineage like B.1.1.28 (which was previously assigned by V2.3.2).
Is this an issue of the new update or is the website still not updated and the issue is because of that?

**Comment by aineniamh** [comment]
The latest version of pangolin is [v2.4.2](https://github.com/cov-lineages/pangolin/releases/tag/v.2.4.2), the website often has a short lag between the updates. If the fasta files are on GISAID, you could file an issue on https://github.com/cov-lineages/pango-designation and they can then get included in the training set, ensuring that they get correctly assigned in future.
