### ISSUE TITLE
Pangolin 2.1.4 does not output pango_version in case of a failed sequence

### ISSUE THREAD

**Issue by aknijn** [cov-lineages/pangolin#184]
In the v2.1.4 the column pango_version was added to the output file. However, in case the sequence in input fails quality control, the pango_version value is not present and the third column is still named probability instead of the new name conflict.

**Comment by aineniamh** [comment]
Hi @aknijn, thanks for pointing this out- I hadn't caught the case when no sequences input pass the quality control. That's fixed now in release [v2.4.2](https://github.com/cov-lineages/pangolin/releases/tag/v.2.4.2).

**Comment by aknijn** [comment]
Thank you @aineniamh
