### ISSUE TITLE
P.1 orf3a:G174C

### ISSUE THREAD

**Issue by kristyhoran** [cov-lineages/pangolin#187]
I have been looking at the variants which define the VOC P.1 and there seems to be only 16 in `config_p.1.csv` (not 17, which is listed in the output), in addition there is a variant listed `orf3a:G174C` which does not seem to be a variant defining P.1 (which likely explains the max 15/17 result returned by pangolin for P.1). Can you shed some light on what I might be missing with the variants for P.1?

**Comment by victormaricato** [comment]
> there seems to be only 16 in config_p.1.csv (not 17, which is listed in the output)

https://github.com/cov-lineages/pangolin/issues/180 already mapped this issue and if you update to current version `2.4.2` it should be solved.

> variant listed orf3a:G174C which does not seem to be a variant defining P.1 (which likely explains the max 15/17 result returned by pangolin for P.1).

Just adding that we can refer to the mutations defining P.1 at the [Supplementary Material (Table S.1)](https://science.sciencemag.org/content/sci/suppl/2021/04/13/science.abh2644.DC1/abh2644-Faria-SM.pdf) of [this paper](https://science.sciencemag.org/content/early/2021/04/13/science.abh2644).

**Comment by victormaricato** [comment]
@aineniamh https://github.com/cov-lineages/pangolin/pull/196 solves it.

**Comment by aineniamh** [comment]
We've got a new branch almost ready to merge in that'll fix it too, but in the meantime this helps. Thank you!
