### ISSUE TITLE
Issue in asignment of A.28 sequences in v2.4.2

### ISSUE THREAD

**Issue by Simon-LoriereLab** [cov-lineages/pangolin#189]
Dear colleagues,
we have noted that sequences belonging to Pango lineage A.28 (confirmed in ML phylogenies and pattern of mutations) are not detected as such in pangolin v2.4.2 (v2.3.8 on the webserver does a bit better, but only for some sequences). They are instead detected as B.1.160, which is in a different clade.
I attach 4 example sequences.
[Sequences_A.28.fas.txt](https://github.com/cov-lineages/pangolin/files/6450582/Sequences_A.28.fas.txt)
Many thanks in advance if you can look into this!

**Comment by AngieHinrichs** [comment]
> I wonder if there is a training sample that is labeled as B.1.160 when perhaps it should be labeled A.28. I will see if I can find something like that by intersecting the sequences on the affected branch with pango-designation/lineages.csv.

To the contrary, when I intersected sequence names from that branch with pango-designation/lineages.csv, I did not find any labeled as B.1.160 (which is good); one is labeled as just A (ah, the noisy one with 84 substitutions relative to NC_045512) and 13 are labeled as A.28:

```
France/BFC-IPP00711/2021,A
Switzerland/GE-32961532/2021,A.28
France/IDF-IPP02562/2021,A.28
France/un-21022020122/2021,A.28
France/un-21022020123/2021,A.28
France/IDF-IPP01096/2021,A.28
France/IDF-IPP01102/2021,A.28
France/IDF-IPP01099/2021,A.28
USA/NY-Wadsworth-21004943-01/2020,A.28
Jordan/PHBC4/2021,A.28
France/OCC-244/2021,A.28
Egypt/CUNCI-HGC11I007/2021,A.28
France/IDF-IPP01111/2021,A.28
France/un-21022020124/2021,A.28
```
France/un-21022020122/2021, despite being a training sample for A.28, is assigned to B.1.160.  Ditto for France/IDF-IPP01096/2021, France/IDF-IPP01111/2021, and France/un-21022020124/2021.

[That doesn't exclude the possibility of B.1.160 having a misassigned training sample that is throwing it off; I have not looked at mutations in all the B.1.160 training samples (there are 10417 of them!).  There simply wasn't an easy-to-find sample from that little branch in the UCSC tree.]

@emilyscher any idea how B.1.160 ends up in the middle of some A.28 rules that are very nearly identical?  (Of these 3 lines from pangoLEARN/pangoLEARN/data/decision_tree_rules.txt, the first ends with "7850!='A'" while the second two have "7850=='A'"; the second line ends with "10155!='G'" while the third line ends with "10155!='G'".  Those are the only differences.)
```
A.28       24505=='G',18423=='-',26800!='C',28882!='A',16888=='-',25504!='C',12877=='-',24075!='A',8046=='A',14407=='A',17857!='C',2479=='-',6309!='-',8781!='A',14804!='G',26087=='A',16393=='A',23603!='C',6039!='G',28143=='A',11416!='G',12819!='C',24046=='C',23063!='-',6540!='A',25903=='G',520!='C',15719!='G',7828=='C',3364!='G',13355!='G',29567!='A',7850!='A'
B.1.160    24505=='G',18423=='-',26800!='C',28882!='A',16888=='-',25504!='C',12877=='-',24075!='A',8046=='A',14407=='A',17857!='C',2479=='-',6309!='-',8781!='A',14804!='G',26087=='A',16393=='A',23603!='C',6039!='G',28143=='A',11416!='G',12819!='C',24046=='C',23063!='-',6540!='A',25903=='G',520!='C',15719!='G',7828=='C',3364!='G',13355!='G',29567!='A',7850=='A',10155!='G'
A.28       24505=='G',18423=='-',26800!='C',28882!='A',16888=='-',25504!='C',12877=='-',24075!='A',8046=='A',14407=='A',17857!='C',2479=='-',6309!='-',8781!='A',14804!='G',26087=='A',16393=='A',23603!='C',6039!='G',28143=='A',11416!='G',12819!='C',24046=='C',23063!='-',6540!='A',25903=='G',520!='C',15719!='G',7828=='C',3364!='G',13355!='G',29567!='A',7850=='A',10155=='G'
```

**Comment by aineniamh** [comment]
Hi both, the model corresponding to release (pango v1.2)[https://github.com/cov-lineages/pango-designation/releases/tag/1.2] has just finished training and I'm re-running GISAID on it now. This was a rather large scale change that removed any sequences with more than 5% ambiguities in the coding region. Prior to this, we had only ever explicitly checked for N. 

I have a hunch that any B->A mis-assignments could be down to ambiguities (either in the training or query data) at key sites and this causes the discrepancy. 

I've just tagged the new model release here: https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-05-10 and will be working on checking it against some of these mis-assignment issues today!

**Comment by aineniamh** [comment]
@AngieHinrichs, I am so keen to get that PR merged in- just getting the PB that we can distribute with the pangoLEARN data together (@rmcolq is working hard on putting Usher to use for everything)!

**Comment by AngieHinrichs** [comment]
Thanks @aineniamh and @rmcolq!  Please let me know if there is any way I can help -- I've had some practice running usher and matUtils.  :)

I just pulled down the latest pangoLEARN from github (commit 0007d8511), and I still see a B.1.160 rule right in the midst of some A.28 rules, only slightly changed from before:

```
A.28    24505!='C',18423=='-',26800!='C',28882!='A',16888!='C',25504!='C',24075!='A',8046!='G',12877=='-',14407=='A',17857=='-',2479!='C',6309!='-',8781=='G',14804=='A',26087=='A',23603!='C',6039=='A',28143=='A',11416=='C',24046!='-',12819=='-',28376!='A',6540!='A',480=='C',27944!='G',15823!='G',13355=='A',7828!='-',3364=='A',10641=='C',7850!='G',10155!='A'
B.1.160 24505!='C',18423=='-',26800!='C',28882!='A',16888!='C',25504!='C',24075!='A',8046!='G',12877=='-',14407=='A',17857=='-',2479!='C',6309!='-',8781=='G',14804=='A',26087=='A',23603!='C',6039=='A',28143=='A',11416=='C',24046!='-',12819=='-',28376!='A',6540!='A',480=='C',27944!='G',15823!='G',13355=='A',7828!='-',3364=='A',10641=='C',7850!='G',10155=='A'
A.28    24505!='C',18423=='-',26800!='C',28882!='A',16888!='C',25504!='C',24075!='A',8046!='G',12877=='-',14407=='A',17857=='-',2479!='C',6309!='-',8781=='G',14804=='A',26087=='A',23603!='C',6039=='A',28143=='A',11416=='C',24046!='-',12819=='-',28376!='A',6540!='A',480=='C',27944!='G',15823!='G',13355=='A',7828!='-',3364=='A',10641=='C',7850=='G'
```

I don't claim to fully understand pangoLEARN's model, but I have a strong opinion that a phylogenetic model has to be more robust, especially at this stage of the pandemic when there have been [>150 million confirmed cases worldwide](https://ourworldindata.org/grapher/cumulative-covid-cases-region).  With a genome of <30k bases, we can be sure that every possible single-nucleotide substitution has been tried multiple times, and recurring mutations are becoming the norm.  Meanwhile, we have 1.5 million genome sequences (unevenly sampled, but still!).  We can build a good-enough global phylogenetic trees, examine (subtrees of) it with our favorite viewers, and reason about lineages as branches of the tree.  pangoLEARN was a brilliant solution in earlier stages of the pandemic when there were too many sequences for iqtree, and not so many mutations.  But I believe the deluge of cases and mutations has moved the domain of the problem beyond the point where pangoLEARN can scale, no matter how much QC you do on its inputs.  :(  I hate to be saying all this downer stuff -- but pangolin is too important not to.

**Comment by aineniamh** [comment]
Thanks Angie for your feedback. We are aware there are limitations with the current approach, and agree UShER is going to be a really useful addition and hopefully scale more robustly with new data. There is also value in continuing the pangoLEARN model, particularly as we begin to see more recombinants a tree-independent approach will be very useful. My opinion is we should do both, and also have some VOCs assigned using SNPs. Both myself and Rachel are working on approving your PR today.

**Comment by aineniamh** [comment]
@Simon-LoriereLab I think I've identified the sequence causing the issue:

```
A.28 Switzerland/BE-ETHZ-470066/2021
	 ['N:A35V', 'N:D128Y', 'N:S202N', 'ORF1ab:A3529T', 'ORF1ab:A3529T', 'ORF1ab:A5376V', 'ORF1ab:D5584Y', 'ORF1ab:M920I', 'ORF1ab:M920I', 'ORF1ab:V86F', 'ORF1ab:V86F', 'S:H655Y', 'S:N501T', 'synSNP:A27489G', 'synSNP:A481G', 'synSNP:A481G', 'synSNP:C12469T', 'synSNP:C12469T', 'synSNP:C2197T', 'synSNP:C2197T', 'synSNP:C2536T', 'synSNP:C2536T', 'synSNP:C27294T', 'synSNP:G16236A', 'synSNP:G22468T']

B.1.160 France/HDF-IPP00737/2021
	 ['N:A35V', 'N:S202N', 'ORF1ab:A3529T', 'ORF1ab:A3529T', 'ORF1ab:A5376V', 'ORF1ab:D5584Y', 'ORF1ab:V86F', 'ORF1ab:V86F', 'ORF3a:S171L', 'S:H655Y', 'S:N501T', 'synSNP:A27489G', 'synSNP:A481G', 'synSNP:A481G', 'synSNP:C12469T', 'synSNP:C12469T', 'synSNP:C2197T', 'synSNP:C2197T', 'synSNP:C27294T', 'synSNP:C6541T', 'synSNP:C6541T', 'synSNP:C9988T', 'synSNP:C9988T', 'synSNP:G22468T']
```
I'll remove France/HDF-IPP00737/2021 from the designation file and that should hopefully resolve the conflict.

**Comment by aineniamh** [comment]
Change commited to pango-designations: https://github.com/cov-lineages/pango-designation/commit/26b7359e34a0b2f122215332b6495fea97ff3fe7

**Comment by aineniamh** [comment]
Release tagged at: https://github.com/cov-lineages/pango-designation/releases/tag/1.2.2- will retrain the model now and this should hopefully rectify the problem.
