### ISSUE TITLE
Lineage Definition

### ISSUE THREAD

**Issue by afmarti** [cov-lineages/pangolin#193]
Dear,

I have one sample with five P. 1.2  lineage-defining mutations (D762G, T1820I, D155Y, C1912T, C28789) 
[101_LABRESIS.txt](https://github.com/cov-lineages/pangolin/files/6489709/101_LABRESIS.txt)
but it was classified as P.1. Is the database actualized?

Thanks,

Andreza

**Comment by aineniamh** [comment]
Hi @afmarti, pangolin currently doesn't assign sub-lineages to P.1 or B.1.1.7 as we use explicit post-hoc tests for these lineages. We're working on a new branch that will do this but also provide a SNP-based assignments in tandem as a separate column using [scorpio](https://github.com/cov-lineages/scorpio). 
We aim to have the new branch released on Monday coming as we're currently running tests and updating documentation to reflect the changes prior to the release of pangolin 3.0. If you want to try it out in the meantime, it's found [here](https://github.com/cov-lineages/pangolin/tree/newscoring).

**Comment by aineniamh** [comment]
Hi @afmarti, this should be resolved in the latest pangolin release (https://github.com/cov-lineages/pangolin/releases/tag/v3.0).
