### ISSUE TITLE
B.1.617.2 being called as B.1.153 in some instances

### ISSUE THREAD

**Issue by jeremydratcliff** [cov-lineages/pangolin#194]
Apologies that I don't quite have the computational background to provide enough detail in this issue. I was investigating the lineage-specific mutations for B.1.617.1 and B.1.617.2 and noted that approximately 25% of B.1.153 samples on GISAID also consistently contained these mutations. A quick look revealed at least 43 samples classified as B.1.153 that contain all of the characteristic spike mutations for B.1.617.2 if they have coverage over that site (T19R, L452R, T478K, D614G, P681R, D950N), but there are likely more as my search was quick and dirty. Csv below with the accession IDs that I noted.

[B.1.153_accession_IDs.csv](https://github.com/cov-lineages/pangolin/files/6495982/B.1.153_accession_IDs.csv)

**Comment by AngieHinrichs** [comment]
Thank you for identifying those sequences, @jeremydratcliff.  I think India/TG-CCMB-BJ145/2021 is an exception: it has S:T19R and S:E484K but does not have L452R, T478K, P681R, or D950N, so it doesn't look like a B.1.617 to me.

The other 41 sequences in your list do look to me like they belong to B.1.617.2 ([UShER](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) places them on the branch for B.1.617.2).  

@aineniamh does this need a new [pango-designation issue](https://github.com/cov-lineages/pango-designation/issues)?  If you approve, I can add those 41 sequences to lineages.csv as new B.1.617.2 representatives.

**Comment by aineniamh** [comment]
Hi Angie, this sounds like an issue for pango-designation alright! Thanks @jeremydratcliff for posting.

**Comment by jeremydratcliff** [comment]
Thank you both!
