### ISSUE TITLE
Incorrect assignment of lineages to B.1.153 instead of ?B.1.617.2?

### ISSUE THREAD

**Issue by charlesfoster** [cov-lineages/pangolin#195]
Hi,

A few sequences we generated have a bunch of mutations that would suggest they belong to B.1.617.2, or a similar lineage, and this would make sense from travel details. However, our analysis with pangolin (v2.4.2, pangoLEARN 2021-05-12, pango_version 1.2.2) designates the sequences as B.1.153. I tried also using the branch of pangolin that implements usher, and the sequences were instead called as B.1.108.

As a test/example, I took one of our samples that has been ?mistakenly called as B.1.153 (EPI_ISL_2107499), one of ours that was correctly called as B.1.617.2 recently (EPI_ISL_1911191), and one sample from GISAID that was called as B.1.153 (EPI_ISL_457156). I chose the latter sample randomly as a B.1.153 representative by looking in https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv. I ran the three seqs through CoVsurver (https://corona.bii.a-star.edu.sg/cgi-bin/coronamapBlast.pl). Here's a comparison of the inferred amino acid substitutions, using the CoVsurver terminology:

![image](https://user-images.githubusercontent.com/11418858/118746125-f92ecb80-b89a-11eb-9c0f-2e48e6bdf56f.png)

First column = our sample called as B.1.153, but suspected to not actually be that lineage. The yellow cells are mutations in common between our 'B.1.153' sample, and our B.1.617.2 sample. There are many of them. 

Do you know what might be going on here? The issue also affects the following seqs from the same run:

EPI_ISL_2107499
EPI_ISL_2107500
EPI_ISL_2107501
EPI_ISL_2107506

Thanks!

Edit: I can also add that putting the sequence corresponding to EPI_ISL_2107499  through usher on  https://genome.ucsc.edu/cgi-bin/hgPhyloPlace leads to something like this:

![image](https://user-images.githubusercontent.com/11418858/118747802-08634880-b89e-11eb-8fc6-87270774f87e.png)

All of the closest sequences in that subtree are B.1.617.2.

**Comment by aineniamh** [comment]
Hi @charlesfoster, this has been noted at [pango-designation](https://github.com/cov-lineages/pango-designation/issues/83), which is the forum for discussing lineage designations. 
This repo is in general for reporting bugs or issues with the software, rather than lineage designations themselves. @AngieHinrichs has addressed the issue reporting these sequences, these designations will feed into a new model training and will be updated in the next pangoLEARN data release. 
Thanks for flagging though!
