### ISSUE TITLE
Lineage P.1 has denominator set to 16 in note field, but only 15 listed in P.1 config file

### ISSUE THREAD

**Issue by whottel** [cov-lineages/pangolin#198]
Similar to issue #180 
pangolearn.smk sets the denominator for P.1 to 16 even though there are only 15 listed in config_p.1.csv

**Comment by aineniamh** [comment]
Will be fixed in [pangolin 3.0](https://github.com/cov-lineages/pangolin/releases/tag/v3.0) as VOC/VUI calls are defined by scorpio constellation files! Thanks!
