### ISSUE TITLE
Incorrect assignment?

### ISSUE THREAD

**Issue by rakulase** [cov-lineages/pangolin#199]
hello,

One of the sequences in was assigned B.1.551 . however it has the hallmarks of B.1.617.2.
Happy to send you the original consensus fasta if required.

SNPs: C3037T, G4181T, T5517G, C7124T, C7851T, C8986T, G9053T, C10647T, A11201G, A11332G, A12959T, G15451A, C16466T, C21017T, T22917G, C22995A, A23403G, C23604G, G24410A, A24551G, C25469T, T26767C, T27638C, C27874T, A28461G, G28881T, G29402T
nsp3: A488S, V933G/V, P1469S, A1711V
nsp4: V167L
nsp5: T198I
nsp6: T77A
nsp9: K92K/*
nsp12: G671S
nsp13: P77L
nsp16: T120T/I
S: L452R, T478K, D614G, P681R, D950N, I997V
ORF 3a: S26L
M: I82T
ORF 7a: V82A
ORF 7b: T40I
N: D63G, R203M, D377Y
codon-aligned deletion in ORF 8: codons 119-120

I'm running v2.4.2. thanks.
[B.1.617.2_B.1.551.txt](https://github.com/cov-lineages/pangolin/files/6547457/B.1.617.2_B.1.551.txt)

**Comment by aineniamh** [comment]
Similar to issues number #216 and #226, we have a VOC/VUI being assigned a sister B.1.? sublineage. 

In pangolin 3.0 onwards, we're now outputting a scorpio call- which replaces the previous 'post-hoc' explicit SNP checking we had been running previously. 

If scorpio outputs one of these assignments as B.1.617.2, B.1.617.1 or indeed any other constellation of mutations that are defined in the constellation repo (https://github.com/cov-lineages/constellations/tree/main/constellations/definitions), you can believe this call and treat it as the lineage assignment. 

If the pangolin call doesn't match the scorpio call, the vast majority of the time this is down to missing data. pangoLEARN as an inference engine isn't handling missing data particularly effectively and if certain defining SNPs are missing, this may lead to mis-assignment. In these cases, just go with the scorpio call. We are now outputting both calls in an effort to provide a more complete view of the assignment process. 

Another suggestion would be to try out the new `--usher` mode, which uses fast parsimony placement in a large tree to estimate the most parsimonious lineage. 

Finally, the other reason for these misassignments could be down to the input training data of pangoLEARN. We build a model based on pango-designations (https://github.com/cov-lineages/pango-designation) and is sensitive to the input data, as this determines what the structure of the decision tree will be. The accuracy of pangoLEARN also declines as it encounters sequences very unlike those it has been trained on (we hope `--usher` mode will be more robust to new diversity), but the solution to this is to provide those sequences to the model so it can learn to include that diversity in its inference. We have a 5% ambiguous sequence cut-off for designation, but if the sequences you're encountering pass threshold and are on GISAID please submit a pango-designation request through GitHub issues and we can add them to our model to maintain the diversity! 

Submit an issue through here: https://github.com/cov-lineages/pango-designation/issues
These requests don't need to be for novel lineages, they can be for cases such as these too!

**Comment by rmcolq** [comment]
This issue is resolved for this example in the latest release which assigns it B.1.617.2 on the basis of the scorpio call, so I'm going to close this issue
