### ISSUE TITLE
 2 genomes without any SNPs with each other got two different pangolin assignments

### ISSUE THREAD

**Issue by Shaokang123** [cov-lineages/pangolin#200]
Hi,

For pangolin, we have 2 genomes without any SNPs with each other (attached), and the only difference is that "control13_sequenced.fasta" has higher ambiguity "N" than "control13_standard.fasta" (6 single base “N” bases + a few large "N" region). However, pangolin gave 2 different lineage types on the two genomes (control13_sequenced.fasta got B.1.411 and control13_standard.fasta got B.1.12), which doesn't make sense since they are identical except "ambiguity" region. 

May I ask why this would happen? Are they any plans to further optimize this? Thanks so much.

Regards,
Shaokang

[two_genomes.zip](https://github.com/cov-lineages/pangolin/files/6547915/two_genomes.zip)

**Comment by aineniamh** [comment]
Hi @Shaokang123, we impute missing data to the reference allele during training and assignment. This means that if key SNPs are missing it can result in incorrect assignments. 

We're working on pangolin 3.0 that has a parsimony assignment option through the use of UShER and also calls particular lineages (such as variants of concern) with a more explicit approach using exact SNP matching.

Unfortunately there's no simple way around missing data with the current approach as lack of a defining SNP may prevent the sequence to fit into the correct category.

**Comment by Shaokang123** [comment]
@aineniamh OK, I see, thanks for your reply. Do you think it makes sense to lower the reported resolution (e.g. here when pangolin can't tell B.1.12 or B.1.411, it can report to B.1)? Glad to hear that there are plans to optimize in 3.0, look forward to it.

**Comment by aineniamh** [comment]
We currently don't know external to the model that pangolin can't tell if it's B.1.12 or B.1.411 as the missing data doesn't cause a conflict, only a different signal. Have tagged release [pangolin 3.0](https://github.com/cov-lineages/pangolin/releases/tag/v3.0) now, and will continue to develop these methods. I think these issues lie at the designation stage as the model is sensitive to the quality of data that goes into it.

**Comment by Shaokang123** [comment]
great, thanks @aineniamh
