### ISSUE TITLE
Error in pangolearn

### ISSUE THREAD

**Issue by manjumoorthy95** [cov-lineages/pangolin#203]
I have a multifasta file containing 3 whole genome sequences of 3 samples of SARS-Cov-2 + an outgroup (BetaCoV.Wuhan.IPBCAMS-WH-05.2020), + the reference, for assigning the lineage. When I use the following command from either as a part of shell script or via direct command line : 

`pangolin SARS-CoV-2_consensus_ref_OG.fasta -o pango-results --outfile pango-out.csv --no-temp`

the command fails and gives me the following error : 

`processing block of 3 sequences 05/27/2021, 11:25:59
Traceback (most recent call last):
  File "/srv/tools/miniconda3/envs/pangolin/bin/pangolearn.py", line 141, in <module>
    d = np.array(rows, np.uint8)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
[Thu May 27 11:25:59 2021]
Error in rule pangolearn:
    jobid: 8
    output: /srv/ngs_rohdaten/fastqs/fastqs_SARS-CoV-2/test_DD/data/CONSENSI_artic_20210524_11h_q20_t0.9_m10/pango-results_20210527_11h/lineage_report.pass_qc.csv
    shell:

        pangolearn.py --header-file /srv/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /srv/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /srv/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta --fasta /srv/ngs_rohdaten/fastqs/fastqs_SARS-CoV-2/test_DD/data/CONSENSI_artic_20210524_11h_q20_t0.9_m10/pango-results_20210527_11h/sequences.aln.fasta -o /srv/ngs_rohdaten/fastqs/fastqs_SARS-CoV-2/test_DD/data/CONSENSI_artic_20210524_11h_q20_t0.9_m10/pango-results_20210527_11h/lineage_report.pass_qc.csv

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message`

As you can though I have 5 sequences as input, only 3 are detected in the processing part after minimap alignment. 

But the same input fasta file if I process without any other arguments (like --outfile, -o and --no-temp), then I get the lineage.csv file alone without other files. May I know whats going wrong?

**Comment by aineniamh** [comment]
The 3 are okay as we're now assigning by sequence hash as well, so some can be processed by the hashing step prior to pangoLEARN. 

May I ask, is your reference sequence just called 'reference'? I think pangolin might be confused in this case. We have an internal reference within pangolin that's a specific length. Supplying your own reference would cause confusion internally and the model would error out. 

If run without no-temp, does pangolin run successfully? 

If possible, attaching an anonymised version of your fasta file would help debug.

**Comment by manjumoorthy95** [comment]
So even if total 5 sequences are there, some would be processed by hash and some would remain as such? Is it ? Does this mean that the rest 2 sequences are filtered out ? Because the same data when I execute from another system, Pangolin runs fine without any problems and prints in the terminal that "mapping 5 sequences". 

No my reference sequence is the Covid 19 reference sequence with header "MN908947.3". 

Yes when we run without no-temp the pangolin executes successfully, with providing just the lineage.csv. But I would require all the files created otherwise plus the sequence.aln file.  

If the error is in my data format or lets say the sequence length, pangolin should have thrown error in my other PC as well right? But in another PC it just runs fine both with/without no-temp option

**Comment by manjumoorthy95** [comment]
[Anonymised.fasta.txt](https://github.com/cov-lineages/pangolin/files/6567628/Anonymised.fasta.txt)
Here is the anonymised version of the input fasta file.
PS: I have added the .txt extension just to upload it into Github, otherwise the file just ends with .fasta

**Comment by aineniamh** [comment]
Hi @manjumoorthy95, I've run with and without the `-no-temp` flag on my system and it seems to run fine. 
I get 4 sequences mapping and 1 assigned with the designation hash, which is running okay. 

The error suggests something with how the model is processing the input file- and I'd suggest to do a full environment update and see if that resolves the issue (Follow the steps for major releases: https://cov-lineages.org/pangolin_docs/updating.html). 

Do you need to run with the no-temp flag or is it working for you otherwise? 

```
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
MN908947.3,B,,,,,,PANGO-v1.2.6,3.0.3,2021-05-27,v1.2.6,passed_qc,Assigned from designation hash.
BetaCoV.Wuhan.IPBCAMS-WH-05.2020.EPI_ISL_403928,B,0.0,1.0,,,,PLEARN-v1.2.6,3.0.3,2021-05-27,v1.2.6,passed_qc,
Sample1,B.1.1.317,0.0,1.0,,,,PLEARN-v1.2.6,3.0.3,2021-05-27,v1.2.6,passed_qc,
Sample2,B.1.617.1,0.0,1.0,cB.1.617.1,1.000000,0.000000,PLEARN-v1.2.6,3.0.3,2021-05-27,v1.2.6,passed_qc,scorpio call: Alt alleles 11; Ref alleles 0; Amb alleles 0
Sample3,B.1,0.0,1.0,,,,PLEARN-v1.2.6,3.0.3,2021-05-27,v1.2.6,passed_qc,
```

**Comment by rmcolq** [comment]
I'm closing this issue as stale - please feel free to reopen if you are still having problems with this!
