### ISSUE TITLE
README is gone

### ISSUE THREAD

**Issue by victormaricato** [cov-lineages/pangolin#208]
@aineniamh the latest update on pangolin deleted most of the README, was this intended? 🤔

**Comment by rmcolq** [comment]
Yes, it's all here https://cov-lineages.org/pangolin.html as linked in the README

**Comment by aineniamh** [comment]
Hi @victormaricato, just as Rachel said, I've updated the docs on the website and the readme links to that. All the same information (and more) is available there!
