### ISSUE TITLE
Rate Limit Exceeded?

### ISSUE THREAD

**Issue by bbimber** [cov-lineages/pangolin#209]
Hello,

We've been using pangolin 2.4 for nearly a year (whenever it became available) and just starting using pangolin 3.0.2. We're running it inside docker, and we run 'pangolin --update', followed by 'pangolin <FASTA>'. We run this on our slurm cluster, and typically submit jobs in batches of hundreds (one sequence run). Since updating to pangolin 3.x we began to see these errors. Have you seen these, and/or do you have ideas? I think it might be during the "--update". Thanks for any ideas.

```
docker run --rm=true -e SEQUENCEANALYSIS_MAX_THREADS -e SEQUENCEANALYSIS_MAX_RAM --memory=48g ghcr.io/bimberlabinternal/pangolin:latest /bin/bash -c 'pangolin --update && pangolin CV11324.lofreq.consensus.fasta'


Traceback (most   recent call last):
--
File "/opt/conda/envs/pangolin/bin/pangolin", line 8, in   &lt;module&gt;
sys.exit(main())
File   "/opt/conda/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py",   line 74, in main
update(__version__, pangoLEARN.__version__)
File   "/opt/conda/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py",   line 345, in update
latest_release = request.urlopen(
File   "/opt/conda/envs/pangolin/lib/python3.8/urllib/request.py", line   222, in urlopen
return opener.open(url, data, timeout)
File   "/opt/conda/envs/pangolin/lib/python3.8/urllib/request.py", line   531, in open
response = meth(req, response)
File   "/opt/conda/envs/pangolin/lib/python3.8/urllib/request.py", line   640, in http_response
response = self.parent.error(
File   "/opt/conda/envs/pangolin/lib/python3.8/urllib/request.py", line   569, in error
return self._call_chain(*args)
File   "/opt/conda/envs/pangolin/lib/python3.8/urllib/request.py", line   502, in _call_chain
result = func(*args)
File   "/opt/conda/envs/pangolin/lib/python3.8/urllib/request.py", line   649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403:   rate limit exceeded
+ echo 'Bash script complete'


```

**Comment by fmaguire** [comment]
Hmm, it does seem to be happening when pangolin is accessing the github API to get releases.  Currently (as constellations and scorpio haven't been added to `--update` yet) there shouldn't be any more API requests happening in version 3 than there was in 2.4 though.

I'm guessing you are hitting github's 5,000 requests per hour limit on the release API (for free accounts). With your set-up (including updating the container and testing pangolin v3 as well as any other things running on the cluster that make github API requests) would it be feasible that you may hit that limit?  Note: that by running each genome individually with `--update` you will be making 2 requests per genome. 

Easiest solution is likely to just concatenate the genomes into a single fasta file and run pangolin once on all of them (use `--datadir` and point to an updated set of databases outside the docker container).

**Comment by bbimber** [comment]
Note: i as a panoglin user, I would have found the docker image quite useful. it took a bit of work yesterday to figure out how to get conda/pangolin installing properly in docker and executing. if anyone reading this wants to either copy our Dockerfile or just pull our public image go for it:

```
docker pull ghcr.io/bimberlabinternal/pangolin:latest 
```

https://github.com/bimberlabinternal/DevOps/blob/master/containers/pangolin/Dockerfile

**Comment by fmaguire** [comment]
Fair enough, good to know that users are getting into that API limit range (especially if going up to 4 API requests per `--update`).

Worth noting that although it may have a little delay in updating there is an automatically created docker container for every [bioconda package](https://bioconda.github.io/recipes/pangolin/README.html) hosted on [quay.io](https://quay.io/repository/biocontainers/pangolin?tab=tags) and there are also singularity containers on [depot.galaxyproject.org](https://depot.galaxyproject.org/singularity/) for most tools.

**Comment by aineniamh** [comment]
This seems to be resolved and (phew!) it wasn't somthing I'd done! If it helps, we have a GitHub actions building a docker container every new release that gets tagged: https://hub.docker.com/r/covlineages/pangolin

https://github.com/cov-lineages/pangolin/blob/master/.github/workflows/push_dockerhub.yml

**Comment by bbimber** [comment]
Man, how'd I miss that yesterday. That would have saved me a lot of time
