### ISSUE TITLE
SNP in pango report

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#210]
Hi,

is it possible in version 3 to keep the proportion of SNPs in pangolin report (ex 15/17 B.1.1.7 SNPs (1 ref and 1 other))
We need this information for validation purpose.

Thanks
Eric

**Comment by rambaut** [comment]
This is currently reported in the notes column by Scorpio but this is going to be added as its own column called `scorpio_counts` or similar. This will have `alt_count|ref_count|amb_count` (i.e., the number of defining SNPs called as alternative, reference or ambiguous).

**Comment by rmcolq** [comment]
This information is now provided in the `note` column in the form e.g. `scorpio call: Alt alleles 13; Ref alleles 0; Amb 
alleles 0`. This SNP information is only provided for VOCs/VUIs through scorpio (it was only provided before for 3 lineages).
