### ISSUE TITLE
Error while running pangolin / scorpio error

### ISSUE THREAD

**Issue by steinbrl** [cov-lineages/pangolin#214]
Hey,

while executing pangolin, it stops with the following error massage. It ist the newest version.

Error in rule scorpio:
    jobid: 6
    output: /tmp/tmpnc598be4/VOC_report.scorpio.csv
    log: /tmp/tmpnc598be4/logs/scorpio.log (check log file(s) for error message)
    shell:
        
        scorpio classify         -i /tmp/tmpnc598be4/sequences.aln.fasta         -o /tmp/tmpnc598be4/VOC_report.scorpio.csv         -t 32         --long &> /tmp/tmpnc598be4/logs/scorpio.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /tmp/tmpnc598be4/.snakemake/log/2021-05-31T123617.667848.snakemake.log

pangolin --update also produces an error massage:

(pangolin) lars@helmut:~/Desktop/SARS-CoV-2/Run_32/Result$ pangolin --update
pangolin 3.0.3 v3.0.3
pangolin already latest release (v3.0.3)
pangoLEARN 2021-05-27 2021-05-27
pangoLEARN already latest release (2021-05-27)
constellations 2021-04-09 v0.0.2
Traceback (most recent call last):
  File "/home/lars/NGS/miniconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 83, in main
    update(__version__, pangoLEARN.__version__, constellations.__version__)
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 380, in update
    if version < latest_release:
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/home/lars/NGS/miniconda3/envs/pangolin/lib/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'

Greetings,

Lars

**Comment by fmaguire** [comment]
This seems the same situation that happened for in #202 

Update your conda environment and reinstall pangolin with the latest dependency versions using the instructions [documentation](https://cov-lineages.org/pangolin_docs/requirements.html) and the issue should be resolved.

**Comment by steinbrl** [comment]
Hey,

I deleted the environment and reinstalled pangolin. Now it works again. But in the last time, I had always issues after updating to an new pangolin version. Always I could only solve the problem with deleting the environment und an fresh install.

Best,

Lars

--
Lars Steinbrück
Medizinische Hochschule Hannover
Institut für Virologie OE 5230
AG Schulz/NGS/Genomics
Geb. I6, Ebene 6, Raum 2060
Carl-Neuberg-Straße 1
30625 Hannover
Tel.:  ++49 (0)511 532 4313
Fax.: ++49 (0)511 532 8736

Von: Finlay Maguire ***@***.***
Gesendet: Montag, 31. Mai 2021 13:00
An: cov-lineages/pangolin
Cc: Steinbrück, Lars; Author
Betreff: Re: [cov-lineages/pangolin] Error while running pangolin / scorpio error (#214)


This seems the same situation that happened for in #202<https://github.com/cov-lineages/pangolin/issues/202>

Update your conda environment and reinstall pangolin with the latest dependency versions using the instructions documentation<https://cov-lineages.org/pangolin_docs/requirements.html> and the issue should be resolved.

**Comment by aineniamh** [comment]
Glad to hear it works again! Sometimes conda can be a bit finickity on different systems. Good to know that a fresh install solves!
