### ISSUE TITLE
Variant Constellations

### ISSUE THREAD

**Issue by GorgonVZ** [cov-lineages/pangolin#215]
We sadly recognised that the variants_*_.csv files are missing in the new version. So far we used these files to report individual variants per sample. With the new Constellations-Files how can I backtrack from lineage to individual variants present in a sample?

**Comment by aineniamh** [comment]
If you run with the `--no-temp` flag, similar intermediate files for all [constellations](https://github.com/cov-lineages/constellations) called using [scorpio](https://github.com/cov-lineages/scorpio) are output.

**Comment by GorgonVZ** [comment]
Thanks for your quick reply!
Sorry, maybe I am missing something, but I do not get the files if I use the --no-temp flag.

pangolin version: 
3.0.3
Command I use:
pangolin --no-temp multifasta.fa
List of output files I get:
lineage_report.csv
logs
not_assigned.fasta
query.failed_qc.fasta
sequences.aln.fasta
hash_assigned.csv
lineage_report.pass_qc.csv
mapped.sam
pangolearn_assignments.csv
query.post_qc.fasta
VOC_report.scorpio.csv

**Comment by aineniamh** [comment]
Ah, I've just realised they don't- I will add the flag in to output this information!

**Comment by rmcolq** [comment]
I've added the change to dev branch - it will require scorpio to be update to release v0.3.1 as some constellation definition names are not file-name-friendly and this wasn't handled.

**Comment by rmcolq** [comment]
This will be in the next release
