### ISSUE TITLE
Weird assignment to B1.525 instead of B.617.2

### ISSUE THREAD

**Issue by pmenzel** [cov-lineages/pangolin#216]
Hi all,

The attached SARS-CoV2 genome sequence is assigned to B.1.525, whereas it should probably be assigned to B.1.617.2 instead.

I used pangolin 2.4.2 with pangoLEARN 2021-05-19. I also get the same assignment using the current online version 3.0.2 with pangoLEARN 2021-05-27.

The sequence has the B1.617.2 spike mutations T19R, G142D, EFR156G, L452R, T478K, D614G, P681R, D950N, but none of the B.1525 mutations like del69/70, del144, 484K, 52R, 67V, 677H, or 888L.

However it has C27752T (ORF7a: T120I).
Looking at the [decision tree rules](https://github.com/cov-lineages/pangoLEARN/blob/8cb465d28646ee32203eadefe45eaf19c854647f/pangoLEARN/data/decision_tree_rules.txt), there is a quite short line for B.1.525:
```
B.1.525	24505=='G',18423=='-',26800!='C',28882!='A',16888=='-',25504!='C',24075!='A',8046=='A',12877!='C',14407=='A',17857=='-',2479!='C',6309!='-',8781=='A',1439!='-',13729!='G',1396=='C',1514=='-',3036!='A',27751!='G',29401=='C',8370!='G',28853!='G',23402!='-',16259!='G',28886!='A',25036!='G',1170=='G',6729=='A',28278=='T'
```
with `27751!='G'`. So if the coordinates in that file are 0-based, that position would correspond to 27752, where the mutation occurs.

This position is listed in only one rule for B.1.617.2:
```
B.1.617.2	24505=='G',18423=='-',26800!='C',28882!='A',16888=='-',25504!='C',24075!='A',8046=='A',12877!='C',14407=='A',17857=='-',2479!='C',6309!='-',8781=='A',1439!='-',13729!='G',1396=='C',1514=='-',3036!='A',27751=='G'
```
with `27751=='G'`.

The wild-type at this position is a C though.

So maybe this position might be the culprit?

[I014.fa.gz](https://github.com/cov-lineages/pangolin/files/6570399/I014.fa.gz)

**Comment by aineniamh** [comment]
This seems similar to a previous issue- but thanks for looking into it. I believe this is a pango-designation issue, as the decision tree is majoritively unsupervised and will be solved by looking into the designations of these sequences. I'll file this in the designation repository!

**Comment by aineniamh** [comment]
Will address this in issue #199
