### ISSUE TITLE
Pangolin not calling lineage A.29 correctly

### ISSUE THREAD

**Issue by SVN-PhD** [cov-lineages/pangolin#218]
<ins>**Software versions**</ins>
Pangolin version: 3.0.3
PANGO version 1.2.6
pangoLEARN: 2021-05-27

<ins>**db versions**</ins>
PLEARN-v1.2.6
PUSHER-v1.2.6

I am getting incorrect lineage reports for sequences that were designated as A.29 or suspected to be A.29 in pangolin. I'm getting lineages A using the default mode and in one case, I was getting lineage A.17. For UShER, these examples were called as lineage B.

| virus_name | GISAID_accession |  	collected |  	lineage |
| ---- | ---- | ---- | ---- |
hCoV-19/England/ALDP-151204F/2021 |  	EPI_ISL_1718849 |  	2021-04-15 |  	A |
hCoV-19/Gambia/22139/2021 |  	EPI_ISL_1731557 |  	2021-01-12 |  	A |
hCoV-19/USA/DC-DFS-PHL-0487/2021 |  	EPI_ISL_2011688 |  	2021-04-22 |  	A |
hCoV-19/England/NORT-1BC1C18/2021 |  	EPI_ISL_2356191 |  	2021-05-18 |  	A |
hCoV-19/Canada/ON-PHL-21-04564/2021 |  	EPI_ISL_2364337 |  	2021-02 |  	A.17 |

Thank you!

**Comment by aineniamh** [comment]
Are your sequences particularly ambiguous? A more rootward assignment can often be due to missing SNPs?

**Comment by SVN-PhD** [comment]
Hi Áine, 

Doh, I only noticed that the latest version of pangoLEARN incorporated pango-designation 1.2.6 and A.29 was added into pango-designation 1.2.8 and 1.2.9. Thanks!

Cheers.
