### ISSUE TITLE
MN908947.3 and NC_045512.2 Being called as lineage B

### ISSUE THREAD

**Issue by mattheww95** [cov-lineages/pangolin#219]
I have recently upgraded to Pangolin v3.0.3 and both GenBank reference sequences (MN908947.3 and NC_045512.2) are being called as lineage B instead of being designated as the root lineage A. As confirmed by the Web App and a local installation of the Pangolin CLI.

Attached is a screenshot of the web app of the sequences being called, and the sequences used.

Note: the fasta files have been attached as .txt files to accommodate Github, but were processed in fasta format.

![Screenshot (94)](https://user-images.githubusercontent.com/76452933/120343580-73f5de80-c2be-11eb-951f-ea4ef07e99c3.png)

[NC_045512.2.txt](https://github.com/cov-lineages/pangolin/files/6577143/NC_045512.2.txt)
[MN908947.3.txt](https://github.com/cov-lineages/pangolin/files/6577150/MN908947.3.txt)

**Comment by rambaut** [comment]
MN908947.3 is a lineage B genome. Two lineages were present in Wuhan in 2019, A and B, and it is difficult to determine which one was ancestral.
