### ISSUE TITLE
Error from scorpio after updating to Pangolin 3.0.3

### ISSUE THREAD

**Issue by sbridgett** [cov-lineages/pangolin#221]
I've updated to Pangolin 3.0.3, but got an error about the constellations version, so I updated the latest to constellations version 0.0.3, and now received the error below about an "Error in rule scorpio".  Even when run locally (ie. not submitted to compute cluster) the output file "/tmp/tmpkbukhsl5/VOC_report.scorpio.csv" and log file "/tmp/tmpkbukhsl5/logs/scorpio.log" doesn't seem to be created, although I can write to that path myself okay, so I don't think it's a file permissions problem.

```
Job counts:
        count   jobs
        1       add_failed_seqs
        1       align_to_reference
        1       all
        1       generate_report
        1       hash_sequence_assign
        1       pangolearn
        1       scorpio
        7
[Tue Jun  1 21:40:46 2021]
Error in rule scorpio:
    jobid: 6
    output: /tmp/tmpkbukhsl5/VOC_report.scorpio.csv
    log: /tmp/tmpkbukhsl5/logs/scorpio.log (check log file(s) for error message)
    shell:

        scorpio classify         -i /tmp/tmpkbukhsl5/sequences.aln.fasta         -o /tmp/tmpkbukhsl5/VOC_report.scorpio.csv         -t 1         --long &> /tmp/tmpkbukhsl5/logs/scorpio.log

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
```

**Comment by aineniamh** [comment]
Hi @sbridgett, I think this issue should be resolved now, I'd recommend fully updating the environment described in the docs for major releases here: https://cov-lineages.org/pangolin_docs/updating.html. Hopefully that'll sort out this error, but if not we can look into it further.

**Comment by sbridgett** [comment]
Thank you for your fast reply, and link to the updating information. I've reinstalled pangolin (same 3.0.3 version) and it's working again okay now. 

I noticed this pangolin install is using constellations version 0.0.2, and when I checked the GitHub ( https://github.com/cov-lineages/constellations ) that is indeed the latest version of cov-lineages/constellations.

So I though I was mistaken about thinking I'd had updated to constellations version 0.0.3 (when the latest version is 0.02). However, I when I again run a "pip install -U constellations", it does updated to version 0.0.3 (as below), but it's a different constellations ( https://pypi.org/project/constellations/ ) which is a "a key-value store over a gossip protocol". When I run pangolin after this "pip install -U constellations", it again fails with the error given above.  

```
(pangolin) [****]$ pip install -U constellations
Processing /users/******/.cache/pip/wheels/be/c6/d3/9205a5188e6ad891eb9681b807b7fa12e0bdfd1ef99971c92a/constellations-0.0.3-cp38-none-any.whl
Installing collected packages: constellations
  Found existing installation: constellations 0.0.2
    Uninstalling constellations-0.0.2:
      Successfully uninstalled constellations-0.0.2
Successfully installed constellations-0.0.3
```

**Comment by aineniamh** [comment]
Hi @sbridgett, you're right, our cov-lineages constellations isn't on pypi! If you're going to pip install, use `pip install git+https://github.com/cov-lineages/constellations.git`, or just the environment file with pangolin.

**Comment by sbridgett** [comment]
Thank you for explaining this. I'll use the pangolin environment file in future. Which the "constellations" on pypi being version 0.0.3, and the "cov-lineages/constellations" being version 0.0.2, I hadn't realised until later that they were completely different packages, as updating from version 0.02 to 0.0.3 was what I had expected.
