### ISSUE TITLE
Default value for --max-ambig changed?

### ISSUE THREAD

**Issue by russellsmithies** [cov-lineages/pangolin#222]
I notice the default value for `--max-ambig` has changed from `0.5` to `0.3`, was this intentional? I didn't see it mentioned in the release notes. Caught us out with some being called in the 2.4.x releases but not in the latest.

**Comment by aineniamh** [comment]
Hi @russellsmithies, thanks for pointing it out. I've added it to the release notes now! You can always override the default if you'd prefer to get an estimation for lower quality sequences. 
https://github.com/cov-lineages/pangolin/releases/tag/v3.0
