### ISSUE TITLE
Error: Missing dependency `usher`.

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangolin#224]
pangolin 3.0.3 v3.0.3
pangolin already latest release (v3.0.3)
pangoLEARN 2021-05-27 2021-05-27
pangoLEARN already latest release (2021-05-27)
constellations v0.0.2 v0.0.2
constellations already latest release (v0.0.2)

If  run pangolin, I get this error message...

Error: Missing dependency `usher`.
Please update your pangolin environment (it is uptodate - se above), updated with pangolin --update

**Comment by AKWB** [comment]
I run pangolin like this:
conda activate pangolin
pangolin consensus.temp.filter --outfile lineage_pangolin_report.tsv

Thus, I do not request to use the "user" model

**Comment by fmaguire** [comment]
You will need to re-create the conda env using the supplied environment.yaml (follow the documentation instructions for details).

`pangolin --update` only updates frequently changing dependencies and doesn't manage the major version changes (e.g., doesn't install usher).

**Comment by AKWB** [comment]
Ok, thanks, thus I basically update pangolin in the very "old" style ;-)

**Comment by aineniamh** [comment]
For any major releases, I'd reccommend updating as described in the docs: https://cov-lineages.org/pangolin_docs/updating.html
Also check the release notes as it usually describes what the changes are in detail: https://github.com/cov-lineages/pangolin/releases
We've also got information about install and dependencies here: https://cov-lineages.org/pangolin_docs/installation.html
