### ISSUE TITLE
command option --panGUIlin missing since v3.0 update

### ISSUE THREAD

**Issue by jwni2018** [cov-lineages/pangolin#225]
Is there any plan to bring back the feature which produces global_lineage_information.csv output?

**Comment by aineniamh** [comment]
Hi @jwni2018, we don't plan to. It was for use by the web application and they now link to the website which has more and updated information.

**Comment by aineniamh** [comment]
We host all the same information on the site and the raw data can be found here: https://github.com/cov-lineages/lineages-website/tree/master/_data it's updated daily.
