### ISSUE TITLE
pkg_resources.ResolutionError: Script 'scripts/pangolearn.py' not found in metadata ....

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangolin#227]
I updated pangolin...

Traceback (most recent call last):
  File "/usr/local/tools/miniconda3/envs/pangolin/bin/pangolearn.py", line 4, in <module>
    __import__('pkg_resources').run_script('pangolin==3.0.3', 'pangolearn.py')
  File "/usr/local/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script **'scripts/pangolearn.py' not found in metadata** at '/usr/local/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin-3.0.3.dist-info'
[Thu Jun  3 10:30:51 2021]
Error in rule pangolearn:
    jobid: 5
    output: /tmp/tmpage8tcwh/lineage_report.pass_qc.csv
    shell:

        pangolearn.py --header-file /usr/local/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /usr/local/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/decisionTree_v1.joblib --reference-file /usr/local/tools/miniconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta --fasta /tmp/tmpage8tcwh/not_assigned.fasta -o /tmp/tmpage8tcwh/lineage_report.pass_qc.csv

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by aineniamh** [comment]
I would suggest following the update instructions here: https://cov-lineages.org/pangolin_docs/updating.html and just trying again!

**Comment by AKWB** [comment]
THANKS!!!! This worked now ;-)

**Comment by aineniamh** [comment]
Ah excellent! Glad it's working! 🎉
