### ISSUE TITLE
the update is not installeing constellations

### ISSUE THREAD

**Issue by wodanaz** [cov-lineages/pangolin#228]
Updated the version of pangolin and having issues with constellations.

how to solve?

![image](https://user-images.githubusercontent.com/5439367/120701748-3db48c80-c481-11eb-9bf7-ca164478f739.png)

**Comment by mcroxen** [comment]
try:

`pip install git+https://github.com/cov-lineages/constellations.git`

**Comment by aineniamh** [comment]
Thanks @mcroxen, I realised the message to handle this error had a typo- It's fixed in the latest release now!

**Comment by wodanaz** [comment]
@aineniamh  and @mcroxen, thanks so much for your help, I solved this by reinstalling pangolin  and making sure I was using v3.0.3 when setting up my environment. For some reason upgrading was not enough. Also, it installed all the new dependencies including usher, constellations and scorpio. 

Best
