### ISSUE TITLE
scikit-learn warning

### ISSUE THREAD

**Issue by kapsakcj** [cov-lineages/pangolin#230]
Hi Aine & pangolin dev team,

I'm working on on a docker container for pangolin v3.0.5 and I ran into a small warning from scikit-learn, I'm wondering if it is benign or if I should adjust the version of scikit-learn that is in the container. 

I saw this commit, allowing for later versions of scikit-learn to be installed https://github.com/cov-lineages/pangolin/commit/3498b9f486321d2a2cd6038d5feb98384f7f54b8

Here's the version of scikit-learn in the container:
```
scikit-learn              0.24.2                   pypi_0    pypi
```

And here's the warning I received when running a genome through pangolin with default settings (pangoLEARN)
```
loading model 06/04/2021, 13:34:04
/miniconda/envs/pangolin/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
processing block of 1 sequences 06/04/2021, 13:34:05
complete 06/04/2021, 13:34:06
```

Is this something to be worried about? Should I downgrade to scikit-learn 0.23.1?

**Comment by Mohit1-K** [comment]
You should not be worried about this warning.
As clearly mentioned in the warning you trained on 0.23.1 and unpickled on 0.24.2, it doesn't cause any problem. I have deployed one machine learning model while I was getting this warning and no problem occurred.

**Comment by aineniamh** [comment]
Thanks @Mohit1-K! 
@kapsakcj as far as I'm aware it won't cause any issues. We had reports of some environments unable to solve with the specific scikit-learn version we had in the setup.py file. The latest release had some flexibility added in to allow for versions >=0.23.1 in the environment, hence the warning. I think this should be fine but we'll keep an eye on it in case incompatibilities start to crop up in future scikit-learn releases.

**Comment by kapsakcj** [comment]
Thanks for the explanation @Mohit1-K and @aineniamh . I'm not familiar with scikit-learn at all, so "pickling/unpickling" doesn't mean much to me other than preserving veggies 😋
