### ISSUE TITLE
Error: Missing dependency `usher`. Please update your pangolin environment.

### ISSUE THREAD

**Issue by mabvakureb** [cov-lineages/pangolin#231]
Hi everyone,
I am getting the error:
Error: Missing dependency `usher`.
Please update your pangolin environment.

And when I run 'pangolin --update' it tells me everything is fine: 
pangolin already latest release (v3.0.5)
pangolearn already latest release (2021-05-27)
constellations already latest release (v0.0.4)
scorpio already latest release (v0.3)

Do I have to install usher separately?

**Comment by aineniamh** [comment]
Hi @mabvakureb, when updating with a major release you need to update the conda environment! Instructions are here: https://cov-lineages.org/pangolin_docs/updating.html

**Comment by mabvakureb** [comment]
Thank you @aineniamh. Its now working, I uninstalled the previous version and made a new installation.
