### ISSUE TITLE
faToVcf error crashing with UShER inference engine

### ISSUE THREAD

**Issue by kevinlibuit** [cov-lineages/pangolin#234]
I've had a few assemblies (three examples attached: [B1_usher_failure.txt](https://github.com/cov-lineages/pangolin/files/6621031/B1_usher_failure.txt), [B1565_usher_failure.txt](https://github.com/cov-lineages/pangolin/files/6621032/B1565_usher_failure.txt), [A6_usher_failure.txt](https://github.com/cov-lineages/pangolin/files/6621033/A6_usher_failure.txt)) that crash with the same faToVcf error message when I run pangolin with the `--usher` flag: 
` Using UShER as inference engine.
faToVcf: expecting multiple sequences in /dev/fd/63 but found only 1.`

When I run these same samples with default parameters (i.e. pangoLEARN inference engine), `No sequences to assign with pangoLEARN.` is printed to stderr. In these instances, Pangolin runs to completion, but the final report shows that the lineage was assigned with PANGO (version: `Pango-v1.2.12`; note: `Assigned from designation hash.`) rather than PLEARN. This seems to be in-line with the expected behavior, at least from my understanding of the documentation.

Please correct me if I'm wrong, but it seems that an initial lineage assignment is attempted with PANGO through a sequence hash search of all currently designated sequences to assign lineages, and--if this fails--the inference model designated by the user is invoked to assign a lineage (i.e. UShER or pangoLEARN). 

In the cases I've listed above, however, something in the PANGO hash search is failing when the `--usher` flag is utilized since, as the output with the pangoLEARN inference engine suggests, an assignment with PANGO should be successful. 

Not sure if this is relevant, but I've run  a few hundred samples with the `--usher` flag and have only ever seen `PANGO-v1.2.12` populated in the version column of the pangolin report in instances of failed assembly quality (e.g. `N_content:0.91`). This is to say that, at least in my small sample size, I've never seen a successful initial PANGO lineage assignment when using the UShER inference engine.

**Comment by kevinlibuit** [comment]
For added context, I'm running Pangolin through the [StaPH-B Pangolin Docker Image (pangolin:3.0.5-pangolearn-2021-06-05)](https://hub.docker.com/layers/staphb/pangolin/3.0.5-pangolearn-2021-06-05/images/sha256-53b74855720c4be4b4e0bb552304eefffdba7baf691d7ce41a130b238083d77b?context=explore) with the following commands:

UShER inference engine:
`pangolin {assembly} --usher --outfile {samplename}.pangolin_report.csv  --min-length 10000 --max-ambig 0.5 --verbose`

pangoLEARN inference engine:
`pangolin {assembly} --outfile {samplename}.pangolin_report.csv  --min-length 10000 --max-ambig 0.5 --verbose`

**Comment by AngieHinrichs** [comment]
Thanks for reporting this, Kevin!  I don't have time to look into it in detail at the moment, but I suspect that a PANGO call is made for the one input sequence, and then there are no sequences for usher to place -- so the snakemake rules for faToVcf & usher should be skipped, but instead faToVcf is run with an empty not_assigned.fasta file (and the reference, which is the "only 1" it's complaining about).

**Comment by kevinlibuit** [comment]
Ah, that makes sense! Also important to note, then, that I am running pangolin with just one input assembly at a time in hopes to incorporate it into a workflow that will process single samples in parallel. 

Thanks for the quick response, Angie. And considering we're in the same time zone, I'd be floored if you had the time to look into this in more detail at the moment :sleeping:

**Comment by aineniamh** [comment]
I think this is resolved now! Thanks @AngieHinrichs! 🎉
