### ISSUE TITLE
Reporting number of Snp's found

### ISSUE THREAD

**Issue by onurtugalan** [cov-lineages/pangolin#240]
Hello,

First of all I would like to say that IT IS A GREAT JOB! Congrats to all of you who has worked for the pangolin tool. We have been using pangolin last 6 months in our corona variant detection pipeline and loved what you guys have done.

In the last versions of the pangolin we observed that you are not giving info related to how many SNPs have been found. Before we used to have something like this in the output table -> 9/9 B.1.351 SNPs

Is there a possibility to extract this kind of output by using the latest pangolin version? If not can you reimplement it in the coming versions?

Best
Onur Tugalan

**Comment by aineniamh** [comment]
Hi @onurtugalan, thanks for your kind words! 

In the output column of note, if scorpio calls a variant constellation, we output the number of Reference, Alternative and Ambiguous alleles- the sum of these is the total number of alleles per variant used in scorpio (source of these calls is now hosted here: https://github.com/cov-lineages/constellations/tree/main/constellations/definitions). 

So all the same information should be available to you, just in a slightly different format!

**Comment by rmcolq** [comment]
Just adding to the above: we have defined constellations for a number of VOCs/VUIs including B.1.351 (before it was only B.1.351, B.1.1.7 and P.1). In the latest pangolin output you should see something like this in the `note` column:
```scorpio call: Alt alleles 9; Ref alleles 0; Amb alleles 0```
I'm closing this issue as resolved but feel free to reopen if you have further problems.
