### ISSUE TITLE
Docs for what `Assigned from designation hash.` means?

### ISSUE THREAD

**Issue by sidneymbell** [cov-lineages/pangolin#242]
Hello! We have a number of samples that didn't receive an `ambiguity_score`, and the note says they were `Assigned from designation hash.`

I've dug into the code base, and I see that these assignments are read from a file called `lineages.hash.csv` in the `data_dir`, but I can't find where that file is created / populated from? 

Also, do you mind pointing me to where the `ambiguity_score` is actually calculated? I want to make sure I'm interpreting it correctly. 

Thanks!

**Comment by rmcolq** [comment]
This means that the sequence matched one that has been designated a lineage i.e. is a representative sequence for that lineage. These calls are by definition high confidence - the list of designated sequences is used to train the model which assigns lineages to new sequences.

The version section here gives a one line explanation about how to interpret this https://cov-lineages.org/pangolin_docs/output.html

Hope that helps!

**Comment by kevinlibuit** [comment]
Thanks for posting this question @sidneymbell and the informative response @rmcolq. I'm also a bit confused on the entirety of the workflow, though this really helps. So, if I understand things correctly, when pangolin is run: 

Every sample is first assessed with PANGO to assess quality and if falls below any metric, things stop here and you'll see the notes column populated with what metric was missed and the version of PANGO used to assess quality. If there's no quality failure, PANGO will then attempt lineage  assignment by sequence hash similarity with respect to designated genomes per lineage. If there is a match, the lineage will be assigned accordingly and in the notes column of the final report table you'll see the message that Sidney posted, i.e. `Assigned from designation hash.`

If no lineage assignment is made by PANGO, then pangolin will attempt assignment with the inference engine selected by the user (either PUSHER or PLEARN). If PUSHER, you'll get a lineage assignment based on the phylogenetic placement and, if PLEARN, you'll get a lineage assignment based on the ML decision tree. In the latter case with PLEARN, the associated ambiguity score will be populated to the final report table. 

And, amidst all of this, SCORPIO will also be attempting VoC lineage assignment via SNP-threshold parameters that differ by VoC. And if SCORPIO makes an assignment, you'll see this reflected in the various Scorpio columns in the final report, as well as the notes column , e..g `scorpio call: Alt alleles 16; Ref alleles 3; Amb alleles 4`.

And so there's really four possible assignment approaches available through pangolin: PANGO (sequence similarity), PUSHER (phylogenetic placement), PLEARN (ML decision tree), and SCORPIO (SNP-thresholds for VoCs). Both PANGO and SCORPIO are applied on all runs for every sample, and PUSHER or PLEARN will be applied as per the user's command.

Please let me know if I'm in any way misinterpreting things!

**Comment by sidneymbell** [comment]
Thank you so much, @rmcolq! And thanks for the clear synopsis, @kevinlibuit, that matches my understanding, as well :)
