### ISSUE TITLE
Name of conda environement

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#245]
Hi,

 I already have a conda env named pangolin for v2. Is it possible to create a new pangolin env under a different name for v3; for example pangolinV3.  I know that we can change the name in environment.yml but I'm not sure if also need to do modifications in other files.

Thanks,
Eric

**Comment by AngieHinrichs** [comment]
Hi Eric -- You can set the env name on the command line using `-n` like this:

`conda env create -f environment.yml -n pangolinV3`

**Comment by EricFournier3** [comment]
Great @AngieHinrichs , thanks a lot
