### ISSUE TITLE
sklearn version warning

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#246]
Hi,

I got the following warning when running version 3.0.6

(pangolinV3) [foueri01@inspq.qc.ca@slbio00d V2_to_V3]$ pangolin -v;pangolin -pv;pangolin -dv
pangolin 3.0.6
pangoLEARN 2021-06-05
pango-designation v1.2.12

**/data/Applications/Miniconda/miniconda3/envs/pangolinV3/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.**

(pangolinV3) [foueri01@inspq.qc.ca@slbio00d ~]$ conda list | awk '/scikit-learn|^python /{print $1"\t"$2}'
python  3.8.10
scikit-learn    0.24.2

Do I need to remove  scikit-learn 0.24.2 and install version 0.23.1  ?

Thanks
Eric

**Comment by AngieHinrichs** [comment]
Hi Eric -- others have observed the same warning and it sounds like you can ignore it, see #230.

**Comment by EricFournier3** [comment]
Ok thank you @AngieHinrichs
