### ISSUE TITLE
Pangolin version control - unstable releases in master branch

### ISSUE THREAD

**Issue by jacaravas** [cov-lineages/pangolin#247]
The latest versions of pangolin have been released as "unstable" versions, but they are present in the master branch of the repo.  Anyone running the recommended installation or upgrade procedure will automatically pull unstable versions of pangolin rather than the official stable version.  This is not the expected behavior.  It leads to unstable versions being unintentionally incorporated into production pipelines that automatically update their software.

Version control for users would be simplified if only stable releases were published in the master branch and unstable versions were kept separate in a "dev" or "unstable" branch.

**Comment by aineniamh** [comment]
Hi @jacaravas, this was a one off- we don't intend to have unstable releases in the master in future. Updating to the latest release will resolve any issues you've got!
