### ISSUE TITLE
pango-designation version mismatch

### ISSUE THREAD

**Issue by jwni2018** [cov-lineages/pangolin#252]
I did the pangolin build using pango-designation v1.2.14 but pangolin -dv reports v1.2.13.

**Comment by rmcolq** [comment]
This is deliberate, although perhaps unclear - the pango-designation version installed should always be up to date to make sure that the aliases provided with `--aliases` are all provided. However the `-pv` gives the version of pango-designation trained on by pangoLEARN which may be a step behind. We will update the help to make this clear.
