### ISSUE TITLE
Unable to install constellations - repository not found

### ISSUE THREAD

**Issue by KajOsman** [cov-lineages/pangolin#255]
Hi, I'm trying to install constellations so I can use the new pangolin update, scorpio installed fine, but when installing constellations using pip install git+https://github.com/cov-lineage/constellations.git it first asks for my username and password and then fails with a fatal error saying repository not found?  Is there something blindingly simple I'm just missing? Thanks in advance.

**Comment by aineniamh** [comment]
Ah, I think there's a typo! It should be cov-lineages!

**Comment by KajOsman** [comment]
Ah sorry - yes no I tried that too - turns out I had a version of 2.3.2 still hanging around - uninstalled that and it worked fine. Thanks and sorry to bother you!

**Comment by aineniamh** [comment]
No worries, glad it's working now!
