### ISSUE TITLE
Error in rule scorpio

### ISSUE THREAD

**Issue by dezordi** [cov-lineages/pangolin#257]
Hello,

Today I installed de pangolin 3.1.4, but when I try to run, the following error message appears:

```
Error in rule scorpio:
    jobid: 6
    output: /tmp/tmpbsar4xty/VOC_report.scorpio.csv
    log: /tmp/tmpbsar4xty/logs/scorpio.log (check log file(s) for error message)
    shell:
        
        scorpio classify         -i /tmp/tmpbsar4xty/sequences.aln.fasta         -o /tmp/tmpbsar4xty/VOC_report.scorpio.csv         -t 1         --long &> /tmp/tmpbsar4xty/logs/scorpio.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message
```

when I tried to read the log error:

`more /tmp/tmpbsar4xty/logs/scorpio.log`

returns:

`more: stat of /tmp/tmpbsar4xty/logs/scorpio.log failed: No such file or directory`

I already used the previous versions of pangolin, but now I'm updating a workflow into a docker container and this error message appears, I already re-installed the conda and pangolin, and the same error message appears

**Comment by AngieHinrichs** [comment]
Hi @dezordi, can you add `--no-temp` to your pangolin command and try again?  By default the /tmp/tmp.... directory is always removed at the end even if there was an error, but `--no-temp` causes the intermediate files to be retained.  They will be left in your current directory unless you specify a different directory with `--outdir`.

**Comment by mcroxen** [comment]
@dezordi I am having the same issue. If you run with `--no-temp` you will get the log files.

**Comment by dezordi** [comment]
> Hi @dezordi, can you add `--no-temp` to your pangolin command and try again? By default the /tmp/tmp.... directory is always removed at the end even if there was an error, but `--no-temp` causes the intermediate files to be retained. They will be left in your current directory unless you specify a different directory with `--outdir`.

This one appears to be the problema:

`Traceback (most recent call last):
  File "/root/miniconda3/envs/pangolin/bin/scorpio", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/scorpio/__main__.py", line 227, in main
    args.func(args)
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/scorpio/subcommands/classify.py", line 7, in run
    classify_constellations(options.input,
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 657, in classify_constellations
    counts, call = count_and_classify(record.seq,
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 516, in count_and_classify
    call, query_allele = call_variant_from_fasta(record_seq, var)
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/scorpio/scripts/type_constellations.py", line 425, in call_variant_from_fasta
    query = query_allele.replace("-","")
AttributeError: 'Seq' object has no attribute 'replace'`

**Comment by AngieHinrichs** [comment]
Thanks!  This bug has also been reported in the scorpio repository: cov-lineages/scorpio#15 and @rmcolq is working on it.

**Comment by rmcolq** [comment]
I've pushed what should fix this to scorpio so a further `pangolin --update` will hopefully fix it - I have a feeling it could be specific to some versions of biopython/OS as I've not been able to replicate the bug on macOS.

**Comment by dezordi** [comment]
> I've pushed what should fix this to scorpio so a further `pangolin --update` will hopefully fix it - I have a feeling it could be specific to some versions of biopython/OS as I've not been able to replicate the bug on macOS.

thanks rmcolq, the pangolin --update fixed it.

this one is my OS and bioypthon versions:
biopython: 1.74
OS: Ubuntu 20.04.2 LTS

Idk if these details can help but I get this error in an interactive docker container where I just install python 3.8, the miniconda (conda 4.9.2) and the pangolin following the installation guide.

 Thanks

**Comment by dezordi** [comment]
After I restart the container, the pangolin --update return this error message:

`
pangolin already latest release (v3.1.4)
pangolearn already latest release (2021-06-15)
constellations already latest release (v0.0.9)
Traceback (most recent call last):
  File "/root/miniconda3/envs/pangolin/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 103, in main
    update({'pangolin': __version__,
  File "/root/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/command.py", line 460, in update
    subprocess.run([sys.executable, '-m', 'pip', 'install', '--upgrade',
  File "/root/miniconda3/envs/pangolin/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/pangolin/bin/python', '-m', 'pip', 'install', '--upgrade', 'git+https://github.com/cov-lineages/scorpio.git@v0.3.4']' returned non-zero exit status 1.
`

**Comment by rmcolq** [comment]
Could github/the internet have made that repo temporarily unavailable? Does this repeat?

**Comment by dezordi** [comment]
> Could github/the internet have made that repo temporarily unavailable? Does this repeat?

yes, the error persist

**Comment by rmcolq** [comment]
Could you try running `pip install git+https://github.com/cov-lineages/scorpio.git` on it's own in the environment?

**Comment by dezordi** [comment]
> Could you try running `pip install git+https://github.com/cov-lineages/scorpio.git` on it's own in the environment?

oh sorry, I was removed the git to get a light docker image, after I reinstall it the pangolin --update worked well

**Comment by rmcolq** [comment]
It sounds like something odd is happening specifically in your docker container - from the scorpio repo it sounds like v0.3.4 installs and works for other ubuntu/biopython=v1.74 users. There are also some github actions for this pangolin repo which include (fresh) installs of pangolin and tests on sequences for both ubuntu and macos and a docker container build. 

Ah, your message explains it - no git! Glad to hear it's fixed
