### ISSUE TITLE
Add scorpio  other allele counts to pangolin output.

### ISSUE THREAD

**Issue by pmenzel** [cov-lineages/pangolin#262]
Related to #240:

The sum of the Ref, Alt, and Amb alleles in the `note` column of the Pangolin report does not necessarily equal the number of sites  in the constellation file. This means one cannot deduce the number of sites in the constellation from the pangolin report file alone.

For example, the `note` says: `scorpio call: Alt alleles 20; Ref alleles 1; Amb alleles 0`, which does only sum up to 21 instead of 23 sites as defined in https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cB.1.1.7.json

The scorpio report `VOC_report.scorpio.csv` for this sample shows `Alpha (B.1.1.7-like),1,20,0,2,2,0.869600,0.043500`, i.e. 2 additional  sites in the `other_count`.

To make it consistent, I suggest to also add the `other_count` to the list of allele numbers in the `note` column of the pangolin report.

**Comment by aineniamh** [comment]
Just merged in now- thanks!
