### ISSUE TITLE
Pangolin 3.1.5 pulls the wrong scorpio version (0.3.1) which does not have --pangolin mode

### ISSUE THREAD

**Issue by fhansen-qiagen** [cov-lineages/pangolin#264]
When I run pangolin 3.1.5 (fresh checkout) I get the error:
![image](https://user-images.githubusercontent.com/20904009/123786050-8d983f00-d8d9-11eb-95b9-1d6014b3c653.png)

The scorpio log says: 
![image](https://user-images.githubusercontent.com/20904009/123786130-a274d280-d8d9-11eb-8c2d-8a05201cde71.png)

when checking the scorpio version, i get 
`bash-5.0# scorpio -v`
`scorpio 0.3.1`

'--pangolin' mode is not supported until 0.3.2 and forward. 

I am running this through docker, and the docker image is built using the Dockerfile from the repository. 

Temporary workaround includes: 
- Modify environment.yml to have `- git+https://github.com/cov-lineages/scorpio.git@v0.3.4`
- rebuild using `conda env update -f environment.yml`
- Then use pangolin.

**Comment by aineniamh** [comment]
If you run `pangolin --update` it should update to the latest scorpio version.

**Comment by fhansen-qiagen** [comment]
`pangolin --update` doesn't work as part of the normal docker workflow. When you run pangolin from docker, as per your own setup, it would be done using `docker run -it [image-id] pangolin [ARGS]`. The nature of docker, however, discards all changes unless you add new layers, i.e. running `docker run -it [image-id] pangolin --update` would give no permanent solution to the problem. 

Example:
```
fhansen@mypc:~$  docker run -it cov-lineages/pangolin pangolin --update
pangolin already latest release (v3.1.5)
pangolearn already latest release (2021-06-15)
constellations already latest release (v0.0.9)
scorpio updated to v0.3.4
pango-designation updated to v1.2.29
```
Then running 
```
fhansen@mypc:~$ docker run -it qiagen/pangolin scorpio --version
scorpio 0.3.1
```

The proposition of running `pangolin --update` only temporarily resolves the issue if you enter the docker image, update, and then run your analysis. Similar to my proposed workaround. 
The actual solution however, should be one of two options: 

1. add `RUN pangolin --update &> /pangolin-update.log` to the Dockerfile, before line 23 `RUN pangolin --version &> /pangolin-version.txt`   
_or (and preferably)_
2. Make sure scorpio-URL from the environment.yml either correctly resolves to the newest version (which it currently doesn't), or explicitly state the version, like this: 
```
name: pangolin
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - minimap2>=2.16
  - snakemake-minimal>=5.13
  - gofasta
  - usher
  - pip:
    - pandas==1.0.1
    - git+https://github.com/cov-lineages/pangoLEARN.git
    - git+https://github.com/cov-lineages/scorpio.git@v0.3.4
    - git+https://github.com/cov-lineages/constellations.git
    - git+https://github.com/cov-lineages/pango-designation.git
```

**Comment by aineniamh** [comment]
I wouldn't be keen on the second option as that then involves manually maintaining the pangolin environment file for every release that happens in a piece of independent software (scorpio). 

My understanding on this environment setup is that `conda env update -f environment.yml` _should_ pull the latest  available releases when creating or updating if no version is explicitly stated (as it seems to do with the other git dependencies?). If that's not happening I'd be interested to find out why.  

Running that command on my system results in
```
Successfully installed constellations-0.0.10 pango-designation-1.2.32 pangoLEARN-2021-06-15 scorpio-0.3.4
```
But I understand docker may be behaving differently.

**Comment by fhansen-qiagen** [comment]
When building the docker images now, I get the correct version. A pointer to scorpio must have moved somewhere. Either way, to prevent this issue moving forward, I still think you should consider adding 1) from my suggestions above, as long as pangolin updates "correctly" when so should the docker image.

**Comment by aineniamh** [comment]
Glad this issue has been resolved! The scorpio-URL from the environment.yml should always resolve to the newest version.
