### ISSUE TITLE
major update completely fails

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangolin#265]
I followed the instructions under updating pangolin for major releases...
git pull
conda env update -f environment.yml

What happens is that I get a list of tons of packages causing inconsistencies...see below...and then the complete install fails ???

Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistence

  - defaults/linux-64::aiohttp==3.7.4.post0=py39h3811e60_0
  - defaults/linux-64::grpcio==1.38.1=py39hff7568b_0
  - defaults/linux-64::liblapack==3.8.0=17_openblas
  - defaults/noarch::boto==2.49.0=py_0
  - [...]
Ran pip subprocess with arguments:
['/usr/local/tools/miniconda3/envs/pangolin/bin/python', '-m', 'pip', 'install', '-U', '-r', '/usr/local/tools/pangolin/condaenv.laavkizi.requirements.txt']
Pip subprocess output:
Collecting git+https://github.com/cov-lineages/pangoLEARN.git (from -r /usr/local/tools/pangolin/condaenv.laavkizi.requirements.txt (line 2))
  Cloning https://github.com/cov-lineages/pangoLEARN.git to /tmp/pip-req-build-m6pl8358
Collecting git+https://github.com/cov-lineages/scorpio.git (from -r /usr/local/tools/pangolin/condaenv.laavkizi.requirements.txt (line 3))
  Cloning https://github.com/cov-lineages/scorpio.git to /tmp/pip-req-build-o2iy0oe1
Collecting git+https://github.com/cov-lineages/constellations.git (from -r /usr/local/tools/pangolin/condaenv.laavkizi.requirements.txt (line 4))
  Cloning https://github.com/cov-lineages/constellations.git to /tmp/pip-req-build-5badcsya
Collecting git+https://github.com/cov-lineages/pango-designation.git (from -r /usr/local/tools/pangolin/condaenv.laavkizi.requirements.txt (line 5))
  Cloning https://github.com/cov-lineages/pango-designation.git to /tmp/pip-req-build-3iaziw3d
Collecting pandas==1.0.1
  **Using cached pandas-1.0.1.tar.gz (4.9 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'**

Pip subprocess error:
  Running command git clone -q https://github.com/cov-lineages/pangoLEARN.git /tmp/pip-req-build-m6pl8358
  Running command git clone -q https://github.com/cov-lineages/scorpio.git /tmp/pip-req-build-o2iy0oe1
  Running command git clone -q https://github.com/cov-lineages/constellations.git /tmp/pip-req-build-5badcsya
  Running command git clone -q https://github.com/cov-lineages/pango-designation.git /tmp/pip-req-build-3iaziw3d
  ERROR: Command errored out with exit status 1:
   command: /usr/local/tools/miniconda3/envs/pangolin/bin/python /tmp/pip-standalone-pip-d4kcgw86/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-9iv6r98x/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version>='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version>='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None

there is much more as it actually does not match to install anything. I did not touch my environment...

Any idea? Do I need to update anything else? Or do I need to completely uninstall? Last release which was working without issues is pangolin 3.0.3. It looks like it does not find the good path?

if I try to start pangolin I get: -bash: /usr/local/tools/miniconda3/envs/pangolin/bin/pangolin: /usr/local/tools/miniconda3/envs/pangolin/bin/python3.8: bad interpreter: No such file or directory

Best

**Comment by AKWB** [comment]
can this be an issue as I have python3.9 in my /usr/local/tools/miniconda3/envs/pangolin/bin ? It was installed along with the update of the environment

**Comment by aineniamh** [comment]
I would suggest removing the environment (https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment) and try building it from scratch- sometimes conda gets confused!

**Comment by AKWB** [comment]
Ok, I try ;-). Thanks for the fast answer!!!

**Comment by AKWB** [comment]
Worked!! THANK YOU VERY MUCH!!!

**Comment by aineniamh** [comment]
Yay! Glad it's working for you!
