### ISSUE TITLE
Usher throws error

### ISSUE THREAD

**Issue by GorgonVZ** [cov-lineages/pangolin#266]
Dear Pangos,
sadly pangolin throws an error if we try to use --usher flag. Do you have any idea how to fix this? 

I already updated pangolin ...

########################################################################################
pangolin already latest release (v3.1.5)
pangolearn already latest release (2021-06-15)
constellations already latest release (v0.0.9)
scorpio already latest release (v0.3.4)
pango-designation already latest release (v1.2.29)
######################################################################################

If I envoke usher directly from conda env I can see, that there is no option -D for usher that pangolin tries to use.
Please see full error message below...

#####################################################################################
Error in rule use_usher:
    jobid: 2
    output: /tmp/tmph7_ge32n/clades.txt
    log: /tmp/tmph7_ge32n/logs/usher.log (check log file(s) for error message)
    shell:

        echo "Using UShER as inference engine."
        if [ -s /tmp/tmph7_ge32n/not_assigned.fasta ]; then
            faToVcf <(cat /home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangolin/data/reference.fasta <(echo "") /tmp/tmph7_ge32n/not_assigned.fasta) /tmp/tmph7_ge32n/sequences.aln.vcf
            usher -n **-D** -i /home/pcr/anaconda3/envs/pangolin/lib/python3.7/site-packages/pangoLEARN/data/lineageTree.pb -v /tmp/tmph7_ge32n/sequences.aln.vcf -T 1 -d '/tmp/tmph7_ge32n' &> /tmp/tmph7_ge32n/logs/usher.log
        else
            rm -f /tmp/tmph7_ge32n/clades.txt
            touch /tmp/tmph7_ge32n/clades.txt
        fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by AngieHinrichs** [comment]
Sorry about that @GorgonVZ -- it looks like you have an outdated installation of usher.  I will add a version constraint to environment.yml, but in the meantime please try this:
```
conda upgrade -n pangolin usher
```

**Comment by GorgonVZ** [comment]
Thanks for your quick reply!!!
Upgrading usher worked for me, but I also had to install pandas dependency.

conda install -f pandas
