### ISSUE TITLE
scorpio vs. lineage call

### ISSUE THREAD

**Issue by BCArg** [cov-lineages/pangolin#267]
Hi there,

I have called pangolin (v 3.1.5) on multiple samples and for most for most of them the `scorpio_call` (Delta (B.1.617.2-like)) was in accordance with the lineage (B.1.617.2). Using the WHO page as reference https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/

For two samples, however, I am getting `scorpio_call` `Gamma (P.1-like)` whereas for one I get `P.1.1` and for the other `B.1.1.7`. So if I only look at the pango lineages I would get Gamma (P.1.1) and Alpha (B.1.1.7)  and not 2x Gamma (from `scorpio_call)`. 

My question is if there is any call (`scorpio_call` vs. `lineage`) that I can trust more in case of ambiguity? Can I get this information from any field produced by pangolin?

thanks in advance

**Comment by aineniamh** [comment]
Can you provide an example sequence of the B.1.1.7 call? There shouldn't be scorpio calls of Gamma that have B.1.1.7 lineage assignments in the latest version of pangolin.
The one example of P.1-like and P.1.1 is fine, as Gamma includes all sublineages within.

**Comment by BCArg** [comment]
Actually I have just tried and the web-based version of panglin (which presumably is the most up-to-date) and it outputs P.1, so it might well be that I was not running the latest version of pangolin when I had that ambiguous call. 

Will close the issue

**Comment by himamura2** [comment]
Dear Aine, I am using the exact sequencing data. With PLEARN-v1.2.13 and pangolin 3.1.5, we will get the following results shown below. It seems that scorpio changed lineage assignment B.1.1.7 to P.1 This sample does have S681H mutation, which is commonly unique to B.1.1.7 and likely led to PLEARN-v1.2.13 to call it B.1.1.7.

**Final.report**
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
ID788/ARTIC/nanopolish_MN908947.3,P.1,0.0,0.9821166473541908,Gamma (P.1-like),0.750000,0.062500,PLEARN-v1.2.13,3.1.5,2021-06-15,v1.2.13,passed_qc,scorpio call: Alt alleles 12; Ref alleles 1; Amb alleles 1; scorpio replaced lineage assignment B.1.1.7

**lineage_report.pass_qc.csv**
taxon,prediction,score,imputation_score,non_zero_ids,non_zero_scores,designated
ID788/ARTIC/nanopolish_MN908947.3,B.1.1.7,1.0,0.9821166473541908,B.1.1.7,1.0,

**pangolearn_assignments.csv**
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
ID788/ARTIC/nanopolish_MN908947.3,B.1.1.7,0.0,0.9821166473541908,,,,PLEARN-v1.2.13,3.1.5,2021-06-15,v1.2.13,passed_qc,

best Hideo

**Comment by aineniamh** [comment]
Thanks both, it's good to know it's behaving predictably!
