### ISSUE TITLE
How does Pangolin deal with nucleotide ambiguities?

### ISSUE THREAD

**Issue by domenico-simone** [cov-lineages/pangolin#268]
Hi,

I have a dataset of reconstructed SARS-CoV-2 genomes with ~40 IUPAC ambiguities in the consensus call. How does Pangolin deal with them?

Thank you,

Domenico

**Comment by aineniamh** [comment]
Hi @domenico-simone, any ambiguity codes are treated as equivalent to an N. The model imputes any missing bases as an A-lineage reference allele, which is the least informative base that can be at that site. The effect is that lineage calls may be pushed more rootward (less precise lineage assignments) with more missing data.

**Comment by domenico-simone** [comment]
@aineniamh thank you for this info!
