### ISSUE TITLE
VOC SNPs proportion in pangolin_V3 report

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#270]
Hi, 

in version 2  of pangolin report, the proportion of SNP for VOC were reported in the **note** columns.
With version 3, this proportion is reported in column scorpio_support, but only when the query is assigned a constellation by scorpio. But I noticed that there is not always a scopio call for VOC. Please see the attached report for example; SAMPLE_1, SAMPLE_4 and SAMPLE_8 are B.1.1.7 without scorpio call. For those, there is consequently no proportion of SNPs that we can check for our internal quality control. Is there an other way by which we can get this information ?

Thank you
Eric
![voc_snp_proportion](https://user-images.githubusercontent.com/15850682/124812100-345f8980-df31-11eb-8656-b56981989769.PNG)

**Comment by pmenzel** [comment]
Check out the file `VOC_report.scorpio.Alpha__B.1.1.7-like__counts.csv`.

**Comment by EricFournier3** [comment]
Is there an option to generate this file ?  I don't see it with `pangolin -h`

**Comment by pmenzel** [comment]
try `pangolin --no-temp`

**Comment by EricFournier3** [comment]
ok great. Thanks
