### ISSUE TITLE
scorpio_support calculation

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#271]
Hi, 

I just want to understand the difference between the calculation of scorpio_support value compare to 
Alt alleles / (Alt alleles + Ref alleles + Amb alleles)

For example, in the attached example, we have 0.87500 for scorpio_support but 14 / (14 + 0 + 0) is 1.0

Thanks
Eric
![Capture2](https://user-images.githubusercontent.com/15850682/124983139-9be70900-e005-11eb-93cc-aedee2ca4d4e.PNG)

**Comment by rmcolq** [comment]
Checking in https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cP.1.json, there are 16 constellation defining mutations for Gamma. Not currently provided in the break down is the "other" score, those mutations which had a non-ref, non-alt, non-ambiguous base. 14/16=0.875.

**Comment by EricFournier3** [comment]
Ok thanks
