### ISSUE TITLE
usher error after latest update

### ISSUE THREAD

**Issue by PHemarajata** [cov-lineages/pangolin#274]
Hi all. After the latest update when using the --usher option I ran into this error:

Error in rule usher_to_report:
    jobid: 0
    output: /home/...................../lineage_report.csv

RuleException:
KeyError in line 358 of /home/.............../anaconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk:
'lineage'
  File "/home/.............../anaconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk", line 358, in __rule_usher_to_report
  File "/home/.............../anaconda3/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message

Thank you!

**Comment by AngieHinrichs** [comment]
So sorry to hear that @PHemarajata!  

@rmcolq it's hard to tell without a test case that gets incompatible_lineage, but at line 358, perhaps `row['lineage']` should be just `lineage`?

**Comment by rmcolq** [comment]
You are right, sorry for the typo. Fixing now.
