### ISSUE TITLE
Pangolin 3.1.7 scorpio error

### ISSUE THREAD

**Issue by ibtissemkadri** [cov-lineages/pangolin#276]
Hi, after updating pangolin and when trying to generate lineage report i got this error:
![pangolin_new_version_error](https://user-images.githubusercontent.com/36642999/125437194-eb0ec907-7707-4d71-af4f-78c11ee7c375.png)
and I couldn't find the log file (the path specified does not exist), it seems like it's not generated.
Thank you so much!

**Comment by AngieHinrichs** [comment]
Hi @ibtissemkadri, can you add --no-temp to your pangolin command and try again?  Then the log files won't be automatically removed and the error messages can be seen.

**Comment by rmcolq** [comment]
Hi @ibtissemkadri , could you also try running `pangolin --update` and let me know what it says?

**Comment by ibtissemkadri** [comment]
Thank you so much for your response.
 `pangolin --update` gave me:
```
pangolin already latest release (v3.1.7)
pangolearn updated to 2021-07-09
constellations updated to v0.0.11
scorpio updated to v0.3.6
pango-designation updated to v1.2.37
```
and now pangolin command works fine! so my fault was that i only updated pangolin!
Thank you again!
