### ISSUE TITLE
sequence unable to be processed

### ISSUE THREAD

**Issue by adamrubrum** [cov-lineages/pangolin#279]
Hello,
I am brand new to entering the lineages and when I put in my fasta files, I am getting the following error:
Sequence unable to be processed with Pangolin (seq_len:4063)

I am guessing this may be user error on my part but I have played around with my files and I can't seem to get any of them to work. Any help would be appreciated.
Thanks

**Comment by AngieHinrichs** [comment]
Hi @adamrubrum -- it sounds like your sequences are too short for pangolin's default minimum length of 25000.  The coding portion of the SARS-CoV-2 is >29000 bases, and pangolin uses nucleotide sequence across that span (aligned to a reference sequence) to assign a lineage.  A 4063-base segment of the SARS-CoV-2 genome may have some informative mutations, but usually not enough for an automated method to make a reliable assignment (depending on where those 4063 bases fall in the genome, probably not enough even for a manual analysis to determine a lineage).  

That said, pangolin does have a `--min-length` parameter that you could set low enough for your sequences, and see what happens.  To see a list of pangolin's options, run `pangolin -h`.

**Comment by adamrubrum** [comment]
Thank you for your help Angie.

I am guessing that you can set the parameters on program and not on the app online because I don't see anywhere to do it on the online app.

**Comment by aineniamh** [comment]
Hi @adamrubrum, I really wouldn't trust an assignment from a sequence of only 4063 bases long. That's a lot of the genome missing information (~85% missing?) and the assignment out of pangolin could be wildly inaccurate. Thanks @AngieHinrichs for the response on that!
