### ISSUE TITLE
Discrepancy in Lineage Assignment between CommanLine and WebSite

### ISSUE THREAD

**Issue by AlessandroAlbiero** [cov-lineages/pangolin#280]
Hi There,

I'm experiencing an issues with the Classification provided by Pangolin Software.
Please find attached a zip file containing 2 fasta file :
[Fasta.zip](https://github.com/cov-lineages/pangolin/files/6862099/Fasta.zip)

Using the Pangolin Web Site these are classified as Lineage B.
Using the Pangolin Software From Command Line - here below the versions:
pangolin already latest release (v3.1.7)
pangolearn already latest release (2021-07-09)
constellations (v0.0.12) is newer than latest stable release (v0.0.11), not updating.
scorpio already latest release (v0.3.8)
pango-designation already latest release (v1.2.39)

it is classified as B.1.36.10

According to previous knowledge the correct lineage should be B - is this a bug in the command line?
Let me know if you need more informations.
Thanks
Alessandro

**Comment by philiptzou** [comment]
Our web service (https://covdb.stanford.edu/sierra/sars2/by-sequences/) also used Pangolin command line 3.1.7, and it also classifies them both as B.1.36.10. However, currently the Pangolin website uses an older version 3.1.5.

**Comment by AlessandroAlbiero** [comment]
HI,
thanks for the feed-back.
This explains the differences on the outputs but it's not clear to me what is the best assignments.
This consensus is coming from a sequencing experiment of a known sample. This sample should be lineage B.
Can you please confirm this is not a problem of the command line annotation?

**Comment by philiptzou** [comment]
Hi @AlessandroAlbiero, I'm not the developer. I just provided the observation of mine. From what I know, the lineage calls from Pangolin keep changing from version to version.

**Comment by AlessandroAlbiero** [comment]
Thanks @philiptzou  - I appreciate your feed-back; it confirms that my pipeline is working good and this classification problem is due to Pangolin Version

**Comment by varSEAK** [comment]
We experience a similar behaviour.
Please find attached a txt file that is actually a fasta.
Pangolin 3.1.5 classifies it as B.1.1.7.
Pangolin 3.1.7 classifies it as B.1.36.36

I know that the lineage assignment can change over time, but given that B.1.1.7 is a VOC, that change seems a bit unsettling.
[Example.txt](https://github.com/cov-lineages/pangolin/files/6900277/Example.txt)

**Comment by AngieHinrichs** [comment]
The pangoLEARN model was just updated some hours ago with a new release.  You could try `pangolin --update` which should pull down that release.  It assigns B to @AlessandroAlbiero's two sequences and B.1. to @varSEAK's example sequence.  (I.e. I think it's the version of pangoLEARN, not pangolin, that makes the difference in this case.)

**Comment by aineniamh** [comment]
We're adding in additional tests using scorpio by @rmcolq and @benjamincjackson to explicitly check for SNP presence as part of the lineage assignment, however the pangoLEARN model is a fragile decision tree and subject to the lineage designations. It comes with an error rate and can be used in conjunction with @AngieHinrichs's `--usher` mode to get multiple sources of information. 
As always, the assignment is an estimation and should be interpreted as such! 
I would also always recommend the latest pangolin and pangoLEARN version as when issues arise with new data we're constantly updating to account for this.
