### ISSUE TITLE
Low priority feature request: run pangolin quietly?

### ISSUE THREAD

**Issue by charlesfoster** [cov-lineages/pangolin#281]
Hi all,

Thanks again for the great tool. This feature request is exceptionally low priority, but would it be possible to run pangolin with a 'quiet' mode in the future? 

I'm asking because I currently have pangolin embedded in some pipelines that have a quiet mode, but when pangolin is run, there is a lot of text written to screen (e.g., the data files found, sequences passing QC etc.). While this is useful info, I'd like the option to silence the output in some circumstances, if possible. Redirecting stderr to /dev/null doesn't seem to help, i.e.:

```
pangolin consensus.fa 2> /dev/null
```

Thanks, and understand if this there are far more important things to do!

**Comment by Piplopp** [comment]
You can use instead

`pangolin consensus.fa &> /dev/null`

**Comment by aineniamh** [comment]
I've really tried to get the snakemake logging down to an absolute minimum unless in verbose mode, but there's some parts of it I haven't managed to get turned off. I will make a note to put in a quiet mode for all the pangolin output, but it may not be completely silent! Thanks @Piplopp for the reply as a stop-gap fix!

**Comment by charlesfoster** [comment]
Thank you @aineniamh, appreciate it! My pipeline that I've embedded pangolin in is also in snakemake, so I appreciate the various pains involved...

**Comment by aineniamh** [comment]
I think I can safely say we didn't do this in the end! Going to close as it's unlikely to be added (I still haven't found a solution to get snakemake to run more quietly when it's called through the API and have really tried a *lot* of things at this stage). Admitting defeat!
