### ISSUE TITLE
Potential incorrect assignment of AY.3

### ISSUE THREAD

**Issue by gkarthik** [cov-lineages/pangolin#292]
@batson pointed out that there could be potential incorrect assignment of AY.3 calls. 

Seems like AY.3 was designated based on ORF1a:T3646A and ORF1a:I3731V ([NextStrain](https://nextstrain.org/ncov/gisaid/global?c=gt-ORF1a_3731,3646)) which remains monophyletic. 
![image](https://user-images.githubusercontent.com/798263/128927527-7131f716-d22f-4e20-9614-e95cd2149b60.png)

However, seems like the pangolin calls AY.3 in many other parts of the tree ([NextStrain](https://nextstrain.org/ncov/gisaid/global?c=pango_lineage&f_pango_lineage=AY.3)).
![image](https://user-images.githubusercontent.com/798263/128927739-513d2ae5-aae6-4ca2-bbe8-f2dc2d69613b.png)

Appreciate any insight. Thank you!

**Comment by batson** [comment]
Some of these may be resolved by the new AY.11 clade, but there are too many to be covered by just that change

https://github.com/cov-lineages/pango-designation/issues/142

@chrisruis

**Comment by rmcolq** [comment]
There has been some curation of the designation sequences between this release and the current one ( see https://www.pango.network/new-ay-lineages-and-an-update-to-ay-4-ay-12/). I think this has improved this issue?

**Comment by gkarthik** [comment]
Hey @rmcolq, I forgot to update the issue. Yes with the new assignments seems like AY.3 is now monophyletic as expected ([NextStrain](https://nextstrain.org/ncov/gisaid/global?c=pango_lineage&f_pango_lineage=AY.3,AY.3.1&label=clade:21A%20%28Delta%29)). Thanks! 
![image](https://user-images.githubusercontent.com/798263/131558338-8ab3a324-d6eb-46b7-a94b-fc6eea745ed9.png)
