### ISSUE TITLE
Typo in pango-designation version causing failure to update the file with --update-data

### ISSUE THREAD

**Issue by jacaravas** [cov-lineages/pangolin#296]
I was just reviewing my log files and noticed the message:

"pango-designation (vv1.2.13) is newer than latest stable release (v1.2.59), not updating."

My pango-designation has not been updating correctly for quite some time due to a typo in the version information for v1.2.13.  This is the second time I have noticed the software failing to update correctly due to an extra "v" in the version name.  Would it be possible to remove all unnecessary characters from the version information when doing the version check to avoid this situation in the future?  My pangolin pipeline is automated and these sort of update errors are not always obvious.

**Comment by rmcolq** [comment]
We do try! Unfortunately, very occasionally these mistakes happen - we have a number of people who work on these repositories now alongside their usual work, and those 2 instances were different people. Happily within pangolin, the older version of pango-designation would only affect users making use of the `pangolin --aliases` command. The pango-designation version output for versioning purposes is the one stored within pangoLEARN ie it represents the version used for training the models and the designation hash.
