### ISSUE TITLE
Pangolin returns different results for aligned/unaligned sequences

### ISSUE THREAD

**Issue by theosanderson** [cov-lineages/pangolin#302]
If you run Pangolin with aligned sequences it can give results that are inconsistent with unaligned sequences.

This may not strictly be a bug as I don't think Pangolin is intended for aligned sequences, but in that case it might be helpful to surface an error on encountering a gap, in case people accidentally supply aligned sequences.

This file contains two identical sequences. The first is aligned, and the second is identical but with the gaps removed. [withwithoutgaps.fa.txt](https://github.com/cov-lineages/pangolin/files/7027867/withwithoutgaps.fa.txt)

The unaligned sequences is called as `AY.4` while the aligned sequence only gets `B.1.617.2`.

![image](https://user-images.githubusercontent.com/19732295/130365303-1263a7fb-7833-488f-8350-76c64f243ae4.png)

**Comment by theosanderson** [comment]
What seems to happen here is that when `-` is present in the input file, that base ends up as `N` in the internal pangolin alignment, whereas if that position is just absent the internal alignment gets a `-` gap.

**Comment by aineniamh** [comment]
I think this is a quirk of when we use minimap2 and gofasta to align sequences that already have gaps in. I believe a fix would be to strip `-` out from sequences prior to running through the pipeline. We can add this in, thanks for flagging!

**Comment by theosanderson** [comment]
Thanks @aineniamh !

**Comment by aineniamh** [comment]
Latest push to master fixed this issue on your test file, now calling both of the sequences `B.1.617.2`. Thanks again!

**Comment by theosanderson** [comment]
Thanks for the change. I'd have expected it to call both `AY.4` given the previous results but maybe this was with a new model or something?

**Comment by aineniamh** [comment]
We've got a new model training at the moment, but I just tested locally on an old model (pangoLEARN 2021-07-28). Really I meant to say they're consistent results now- should have said that! 

I've updated locally to 2021-08-09 and they're now both AY.4!
```
taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,version,pangolin_version,pangoLEARN_version,pango_version,status,note
with_gaps,AY.4,0.0,0.9895782384589338,Delta (B.1.617.2-like),1.000000,0.000000,PLEARN-v1.2.56,3.1.11,2021-08-09,v1.2.56,passed_qc,scorpio call: Alt alleles 13; Ref alleles 0; Amb alleles 0; Oth alleles 0
without_gaps,AY.4,0.0,0.9895782384589338,Delta (B.1.617.2-like),1.000000,0.000000,PLEARN-v1.2.56,3.1.11,2021-08-09,v1.2.56,passed_qc,scorpio call: Alt alleles 13; Ref alleles 0; Amb alleles 0; Oth alleles 0
```

**Comment by theosanderson** [comment]
Great!
