### ISSUE TITLE
How to assign B.1.617.2 to AY sublineage

### ISSUE THREAD

**Issue by alantsangmb** [cov-lineages/pangolin#306]
Hello,
I have got a few genomes which supposed belong to AY sublineages, but pangolin reported them to B.1.617.2 or incorrectly reported as AY.4/AY.12.

Here the latest version I used:
pangolin: 3.1.11
pangolearn: 2021-08-09
constellations: v0.0.15
scorpio: 0.3.12
pango-designation: 1.2.70

For the attached genome,  I suppose it belonged to AY.23 but both pangolearn or usher mode reported it is B.1.617.2.
As hgPhyloPlace assigned it to AY.23, I wonder I am not installing the latest version correctly?

[usher-lineage_report.csv](https://github.com/cov-lineages/pangolin/files/7063695/usher-lineage_report.csv)
[lineage_report.csv](https://github.com/cov-lineages/pangolin/files/7063696/lineage_report.csv)
[VM21036229.fasta.txt](https://github.com/cov-lineages/pangolin/files/7063697/VM21036229.fasta.txt)

**Comment by rmcolq** [comment]
The latest release of pangoLEARN is 2021-08-24 and the previous release only included sub-lineages up to AY.12. Try running `pangolin --update`.

**Comment by rmcolq** [comment]
I can confirm that with the new release, your sequence is assigned AY.23 like with the usher mode
