### ISSUE TITLE
sub-lineage Determination

### ISSUE THREAD

**Issue by Pratibhakadam** [cov-lineages/pangolin#308]
Hello there,
I have sequences whose lineage were determined using the latest version of pangolin i.e. 3.1.11 with --usher option.
It had shown B.1.617.2 for all the sequences but when I build a phylogeny tree of my sequences with other sub-lineage sequences from the GISAID database for Indian strains using the Nextstrain tool.  My sequences were in the group of sub-lineage sequences of GISAID sequences.

This means my sequences are similar to them yet I don't have sub-lineage.
Help to get the right sub-lineages for my sequences .

also, are there any sub-lineages for the Indian strains?

**Comment by rmcolq** [comment]
Hi @Pratibhakadam,
Could you share an example of some sequences or share the Nextstrain placement of them? What sublineages are coming up with Nextstrain?

**Comment by Pratibhakadam** [comment]
Hello,
yes sure..
In the phylogeny first 2 sequences and the last one are from the GISAID
database and have sub-lineage AY.5.Rest samples are from my lab .
Also added the sublineage sheet, which includes sublineages determined
using PangoLEARN, usher and also from the Nextstrain in which group they
are falling.

Thanx

**Comment by rmcolq** [comment]
@Pratibhakadam they don't seem to have attached, but your comments help. The most common reasons why samples might not be assigned to the sub-lineages are:
1. They are best represented by the parent lineage (ie the defined sublineages doesn't fit)
2. They contain more ambiguous bases (N) compared to the reference and therefore can't be placed with enough certainty at the sub-lineage level and get assigned usually to the parent instead.
3. They are more diverged from the designated sequences representing the sublineage. 

If your sequences are high quality, on GISAID and you have some evidence that they should belong to a sublineage (ie case 3) then you could submit an issue here https://github.com/cov-lineages/pango-designation/issues suggesting we include your sequences to improve future designations.

AY.5 was defined by an introduction and then spread in the UK and there are still some false positive assignments of it after the latest release, which we will be continuing to improve. There aren't currently any AY sublineages defined by an epi-event into India. I'm sure more sublineages will be defined over the coming months.
