### ISSUE TITLE
inconsistent lineage assignment between pangolin web version and github version

### ISSUE THREAD

**Issue by ShannonDaddy** [cov-lineages/pangolin#311]
Hi, we've found that the results of lineage assignment from pangolin web and github version are different, but we can't tell why, please help us. The snapshots of version check and lineage results are attached.

github command-line version:
<img width="657" alt="github_command_line" src="https://user-images.githubusercontent.com/6656888/133025571-4a535702-9347-411f-9e09-ce406bd7f019.png">

web version:
<img width="665" alt="web" src="https://user-images.githubusercontent.com/6656888/133025621-a06bc7a4-0df4-4e8c-b392-b7380cd950dc.png">

sequence:
[assembly_consensus.zip](https://github.com/cov-lineages/pangolin/files/7151428/assembly_consensus.zip)

please check it and tell us if there are any software or database/model version differences. 

Thanks a lot!

**Comment by rmcolq** [comment]
It looks like the website is behind by one model release (the bottom of the page says lineages version 2021-08-09, which means that it is running pangoLEARN release 2021-08-09). This website is maintained by different people to the command line tool/model generation and I have sent them a message to query it with them. The correct assignment is the one with the github/command line version.

**Comment by ShannonDaddy** [comment]
> It looks like the website is behind by one model release (the bottom of the page says lineages version 2021-08-09, which means that it is running pangoLEARN release 2021-08-09). This website is maintained by different people to the command line tool/model generation and I have sent them a message to query it with them. The correct assignment is the one with the github/command line version.

Thanks!
