### ISSUE TITLE
Discrepancy web application vs offline Pangolearn version 

### ISSUE THREAD

**Issue by brittvanm** [cov-lineages/pangolin#312]
Hello, 

When we compare the results of our offline Pangolearn version (24/08/2021) with the web application https://pangolin.cog-uk.io/ (9/8/2021), we see many differences for the sublineages (AY) of the Delta variant. I suppose our offline Pangolearn version is the most correct one? When will the web application be updated?

**Comment by aineniamh** [comment]
You're right that the offline version will be the most up-to-date one! The Centre for Genomic Pathogen Surveillance (https://www.pathogensurveillance.net/) made and maintain the web application! @aunderwo updates and builds a new version of the web app every time there's a new release tagged!

**Comment by rmcolq** [comment]
The web app is currently running the release from 2021-09-17, and I hear it is being updated to yesterday evening's release now, so I think this issue is now resolved.
