### ISSUE TITLE
New snakemake version introduces path handling error

### ISSUE THREAD

**Issue by abel-betraoui** [cov-lineages/pangolin#313]
Hi all,

I got the following error running pangolin today:

```
Traceback (most recent call last):
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/snakemake/__init__.py", line 593, in snakemake
    workflow.include(
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/opt/conda/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk", line 13, in <module>
    config["trained_model"] = os.path.join(workflow.current_basedir,'..', config["trained_model"])
  File "/opt/conda/envs/pangolin/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not LocalSourceFile
```

The piece of incriminated code is the following (from **pangolearn.smk**):
```.python
if config.get("trained_model"):
    config["trained_model"] = os.path.join(workflow.current_basedir,'..', config["trained_model"])
```
I ran a previous version of the code (docker built on the 2021-09-20) on the same file and everything went well.

I noticed an update of snakemake (from 6.8.0 to 6.8.1) 3 days ago which introduces modifications in the definition of 
 the **workflow.current_basedir** function which now returns the path as a LocalSourceFile (apparently not handled by os.path.join).

Snakemake version is constrained in **environment.yml** as follows:
```
  - snakemake-minimal>=5.13
```

If I'm not mistaken, converting current_basedir to something os.path.join can handle should correct this issue. A temporary workaround would be to set the version were there any side effects to the fix.

Cheers

**Comment by tomu01** [comment]
Also seeing this same error. In fact pangoLEARN 2021-09-17 was working fine last week, but due to the recent snakemake change, is now failing.

**Comment by tomu01** [comment]
Thanks so much @aineniamh for the quick fix!
