### ISSUE TITLE
Conda environment name suddenly changed from pangolin --> pangolin2

### ISSUE THREAD

**Issue by lvreynoso** [cov-lineages/pangolin#314]
Hi there! I work on a project that uses pangolin in automated batch jobs, and I noticed that our install script started failing on `conda activate pangolin`. The conda environment name was changed to `pangolin2` in [this commit](https://github.com/cov-lineages/pangolin/commit/bda2c9ac221c48975ab7589bdab67aca99f99285), but this appears to be a side effect of testing the changes, and not an intentional change to the `environment.yml` file distributed with pangolin. Should I update our scripts to use `conda activate pangolin` or was this change made in error?

Cheers,
Lucia

**Comment by aineniamh** [comment]
Should be fixed now, sorry about that!

**Comment by lvreynoso** [comment]
Thank you for the quick response!
