### ISSUE TITLE
Pangolin not completing after initial error message about config

### ISSUE THREAD

**Issue by grovesn** [cov-lineages/pangolin#317]
Hi, 

I have installed pangolin and dependencies on one of our virtual machine (it doesn't have conda so I have had to install each piece separately). I can run the checks successfully (`pangolin -v` etc.) without any issues. 

When I try to run pangolin on a fasta file I get the following output:

```Traceback (most recent call last):
  File "/databricks/python3/lib/python3.8/site-packages/snakemake/__init__.py", line 593, in snakemake
    workflow.include(
  File "/databricks/python3/lib/python3.8/site-packages/snakemake/workflow.py", line 1182, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/databricks/python3/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk", line 13, in <module>
    config["trained_model"] = os.path.join(workflow.current_basedir,'..', config["trained_model"])
  File "/usr/local/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not LocalSourceFile
All dependencies satisfied.
The query file is:/data_dump/delta_seqs_1.fasta
** Sequence QC **
Sequence name                 	                   Reason	Value     


Number of sequences detected: 5531
Total passing QC: 5531

Data files found:
Trained model:	/databricks/python3/lib/python3.8/site-packages/pangoLEARN/data/decisionTree_v1.joblib
Header file:	/databricks/python3/lib/python3.8/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
Designated hash:	/databricks/python3/lib/python3.8/site-packages/pangoLEARN/data/lineages.hash.csv
```

My command is `pangolin --max-ambig 0.55 -t 3 --outfile ${f}.pango.csv $f` 

I'm not sure if the issue is something in my set up but I can't see what might be wrong.

**Comment by aineniamh** [comment]
This is from an issue a few days ago that is introduced with the latest snakemake minimal release (https://github.com/cov-lineages/pangolin/issues/313). As a fix, I've specified that an older version of snakemake-minimal is needed in the conda environment file (<=6.8.0) so downgrading to an earlier snakemake version should fix your issue!

**Comment by grovesn** [comment]
Ah! Great, thanks!
I'll give that a go :)
