### ISSUE TITLE
Pangolin (apparently) installed, but I can't use it

### ISSUE THREAD

**Issue by ThiagoRBM** [cov-lineages/pangolin#318]
Hello all,

I've installed pangolin, as said here: https://cov-lineages.org/resources/pangolin/installation.html (first five steps).
Apparently all is ok, but when I try to get pangolin version (pangolin -v) or run any commando, I get  "command not found: pangolin". Pangolin is active as far as I can say (I run the command to activate and got no error message).

Thanks for your help!

**Comment by ThiagoRBM** [comment]
Solved! :)

**Comment by AnyaKovalenko** [comment]
Hello @ThiagoRBM 
I have the same issue with the pangolin. Please could you say how did you resolve this? Many thanks in advance.

**Comment by AnyaKovalenko** [comment]
Now it works :) just missed <.> in the <pip install.>

**Comment by julesjulesjules** [comment]
I am also experiencing this issue now. @ThiagoRBM how did you resolve yours? @AnyaKovalenko what was the full command that you used that needed a "."?

**Comment by theosanderson** [comment]
I would assume `pip install .`
