### ISSUE TITLE
Upgrade biopython dependency?

### ISSUE THREAD

**Issue by priesgo** [cov-lineages/pangolin#321]
We are trying to integrate pangolin in a variant calling workflow for SARS-CoV-2 (https://github.com/TRON-Bioinformatics/covigator-ngs-pipeline/pull/2). This workflow depends on a recent version of Biopython 1.79 to perform the global alignment of sequence and reference. But, Pangolin depends on an older version of biopython 1.74 (see https://github.com/cov-lineages/pangolin/blob/master/environment.yml#L7). We were wondering if it would be possible to change the Pangolin dependency to `biopython>=1.74` or just upgrade to the latest.

Of course using a more recent version of biopython may have an impact in Pangolin. Most evident is the Python versions that are supported which for 1.79 is Python >=3.7.

**Comment by aineniamh** [comment]
We have added in biopython>=1.74, we may need to specificy a particular version again in future if biopython introduces anything that breaks in future versions though!
