### ISSUE TITLE
pangoLEARN lineage assignment B.1.1.7 was not supported by scorpio 

### ISSUE THREAD

**Issue by antra14** [cov-lineages/pangolin#322]
Hi,

I am analyzing some samples for which I am getting clade as 20I (Alpha, V1) by Nextclade tool bit in pangolin 3.1.14 getting pangoLEARN lineage assignment B.1.1.7 was not supported by scorpio  or usher lineage assignment B.1.1.7 was not supported by scorpio which report lineage as None.
Could you please guide me what does it mean

**Comment by rmcolq** [comment]
https://github.com/cov-lineages/constellations/blob/main/constellations/definitions/cB.1.1.7.json
