### ISSUE TITLE
Full reporting of software version in 'lineage_report' file

### ISSUE THREAD

**Issue by aretchless** [cov-lineages/pangolin#338]
For QMS purposes, would it be possible to write the full software version information in the lineage_report file produced by pangoiln? Currently, the version information does not include scorpio or constellations, which have become essential to the identification of lineages such as AY.4.2. 

It would be especially helpful if there were a single version identifier that accounted for the full process of assigning lineages, including both the algorithms (pangolin, scorpio) and the reference datasets (pangoLearn, constellations), so that we could assure that two people running that version of the software with default settings would obtain the same results. This would make it easier to account for any discrepancies among public-facing datasets.

Thank you for maintaining this software that has filled a critical need for providing shared nomenclature during the pandemic.

**Comment by aineniamh** [comment]
In pangolin 4.0, we now report pangolin, scorpio, pangolin-data and constellations versions! Thanks for your patience!
