### ISSUE TITLE
Likely Mis-alignment of P.1.16 lineage call to Alpha sequences

### ISSUE THREAD

**Issue by DOH-SML1303** [cov-lineages/pangolin#342]
The recent version of pangolin assigned two alpha sequences to the P.1.16 lineage

taxon | lineage | pangolin call v 3.1.16 | usher | nextclade
-- | -- | -- | -- | --
USA/WA-UW-21042027698/2021 | B.1.1.7 | P.1.16 | B.1.1.7 | 20I
USA/WA-UW-21051199263/2021 | B.1.1.7 | P.1.16 | B.1.1.7 | 20I

pangolin v3.1.16
pangolearn 2021-10-18
constellations v0.0.21
scorpio  v0.3.14
pango-designation av1.2.91

**Comment by rmcolq** [comment]
I ran pangolin with `--no-temp` on both these sequences and see that neither is called as B.1.1.7 by scorpio. It looks like the first sequence has 6 ref and 17 alt calls for the defining mutations of Alpha, and the second has 15 ref calls and 6 alt calls. In usher mode when I run, the first is coming out as B.1.1.7 and the second as B.1.

So the first thing is that neither sequence should be given a classification as B.1.1.7. Seeing such a mix of alt and ref calls for the defining mutations is odd (we don't usually see intermediates for B.1.1.7) - are you using a bioinformatics pipeline which inserts reference sequence where read quality drops when generating the consensus sequences?

I would have expected the usher B.1.1.7 call to be replaced, given that scorpio did not support it. I will investigate why it didn't.

**Comment by DOH-SML1303** [comment]
Hi @rmcolq, thank you so much for your response and for looking into this. I am not sure if the bioinformatics pipeline that the submitter uses insert reference sequence where read quality drops during consensus sequence building, but I can try to find out.
