### ISSUE TITLE
Pangolin fails to classify samples in --usher mode

### ISSUE THREAD

**Issue by CVL-IL-omer** [cov-lineages/pangolin#344]
Hey Pangolin developers,
Most of the sequences in my query fasta file are not classified when using UShER, without an clear explanation why, e.g.:
```
<id>,None,,,,,,PANGO-v1.2.88,3.1.16,2021-10-18,v1.2.88,fail,failed_to_map
```
How can solve this issue? Pangolin is up to date.

Thanks!

**Comment by rmcolq** [comment]
Does it work in pangoLEARN (default) mode? Could you check that minimap2 has installed correctly (run `minimap2 -h` to make sure the help menu comes up with no errors - on my M1 mac I have before had it install in a corrupted way)

**Comment by CVL-IL-omer** [comment]
@rmcolq Thank you for your answer. Minimap is properly installed and pangoLEARN performs well.

**Comment by aineniamh** [comment]
It sounds like your sequences failed to map using minimap2 ("failed_to_map" in the output report). This could be for a number of reasons- your sequence might be too ambiguous, may be too divergent to the SARS-CoV-2 reference or might be too short. If you could post your sequence here (anonymised if necessary), we could troubleshoot to see why minimap2 isn't mapping your sequence to the reference.

**Comment by CVL-IL-omer** [comment]
@aineniam
Thanks, please find attached. PangoLEARN doesn't use minimap2?
[Pango.zip](https://github.com/cov-lineages/pangolin/files/7494945/Pango.zip)
h

**Comment by AngieHinrichs** [comment]
Thanks @CVL-IL-omer for reporting this and sharing sequences to reproduce the problem.  Short answer, assuming your original sequence file uses numeric sequences names like the file you shared, is that it's an issue with an older version of usher that you can fix by updating usher:
```
conda activate pangolin
conda update usher
```
Longer answer: usher ignores any sequence whose name matches the name of any node in the tree.  Earlier versions of usher used numbers as internal node names, so any sequence with a numeric name that happened to match an internal node name would be ignored.  More recent versions of usher now use `node_`_number_ for internal node names, so it is less likely to have that accidental name clash.  

You can find out your current version of usher with `conda list usher`.  When I had version 0.3.2, and ran `pangolin --usher --no-temp`, the file logs/usher.log had many lines like this:
```
WARNING: Ignoring sample 1 as it is already in the tree.
WARNING: Ignoring sample 2 as it is already in the tree.
WARNING: Ignoring sample 4 as it is already in the tree.
```
After I ran `conda update usher`, the version from `conda list usher` was 0.4.8.  Then the usher log showed normal messages about placing sequences in the tree, and the CSV output included lineage assignments for sequences that passed QC.  

I hope that updating usher does the trick for you too.  If it doesn't work, then please send the logs/usher.log file (from `pangolin --usher --no-temp`).

**Comment by CVL-IL-omer** [comment]
@AngieHinrichs Thanks for your reply! However, your assumption is wrong :)
The headers were converted to numbers in order to remove identifying details.

**Comment by AngieHinrichs** [comment]
Sorry to hear that wasn't the issue on your end.  However, the fasta file that you sent is working fine with my installation of pangolin, so hopefully we can get your installation of pangolin to a similar state.  Can you send the output of these commands?  
```
conda activate pangolin
pangolin --all-versions
conda list usher
```
And then if you could run `pangolin --usher --no-temp` on your file, when the run completes there should be a file logs/usher.log.  Can you send that file as well?  It should contain clues as to why you're not getting lineage assignments as expected.

**Comment by aineniamh** [comment]
Hi @CVL-IL-omer, just checking back in about this issue. I've run your attached file through the latest version of pangolin 

Output of pangoLEARN mode posted here: 
[lineage_report.csv](https://github.com/cov-lineages/pangolin/files/7617931/lineage_report.csv)

Output of UShER mode here: 
[lineage_report.usher.csv](https://github.com/cov-lineages/pangolin/files/7617969/lineage_report.usher.csv)

and that issue reported as 'failed_to_map' doesn't seem to be appearing. The only sequences that have failed seem to be because of high N-content. 

Can you confirm if the issue has resolved on your end?

**Comment by rmcolq** [comment]
This appears to be a stale issue. Feel free to reopen if not resolved
