### ISSUE TITLE
Likely mis-assignment of AY.119?

### ISSUE THREAD

**Issue by alantsangmb** [cov-lineages/pangolin#346]
I have got the attached sequence which seems like to be a AY.119 sequence, but latest pangolin assigned it to AY.43 and B.1.617.2 using usher.
[AY119.txt](https://github.com/cov-lineages/pangolin/files/7524277/AY119.txt)

**Comment by AngieHinrichs** [comment]
Hi @alantsangmb -- AY.119 was added in pango-designation [release v1.2.92](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.92), while the latest release of pangoLEARN ([2021-11-04](https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-11-04)) was trained on pango-designation release v1.2.91, and the lineageTree.pb used in --usher mode was also constructed with v1.2.91 lineages.  The next release of pangoLEARN will include the new lineages in v1.2.92 (and [v1.2.93](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.93) I believe) for both pangoLEARN and UShER.

**Comment by AngieHinrichs** [comment]
P.S. If you run `pangolin --all-versions`, it includes "pango-designation used by pangoLEARN/Usher" so you can see that the pango-designation version is v1.2.91:
```
pangolin: 3.1.16
pangolearn: 2021-11-04
constellations: v0.0.21
scorpio: 0.3.14
pango-designation used by pangoLEARN/Usher: v1.2.91
pango-designation aliases: 1.2.94
```

**Comment by alantsangmb** [comment]
@AngieHinrichs  Thank you for your detailed and clear explanation.
I will check the pango-designation version next time.
