### ISSUE TITLE
Earliest date of AY.4

### ISSUE THREAD

**Issue by 1GHX** [cov-lineages/pangolin#350]
Currently your website reads that the earliest date of AY.4 (B.1.617.2.4) is May 11th, 2020. This looks like a mistake to me as the first B.1.617.2 case was detected in India, February 2021 (e.g.: https://en.wikipedia.org/wiki/SARS-CoV-2_Delta_variant). 

Unless cov-lineages is trying to claim that B.1.617 has existed for almost a year in the UK (May 2020 - February 2021) without massively infecting populations, cov-lineages is publishing incorrect information. If not, please provide evidence for earliest AY.4 date of May 11th, 2020.

**Comment by rmcolq** [comment]
The website is currently updated automatically based on the information in GISAID on a daily basis. We have a recurrent problem of individuals submitting incorrect dates to GISAID and this is what you are seeing here. In this particular case of misdated UK sequences, the submitting organization is aware of the problem and is working to fix the dates - when their fix is pushed to GISAID, this will be reflected in a correction to the website.

**Comment by aineniamh** [comment]
Thanks @rmcolq for responding! I'm going to close this issue as it's unrelated to the pangolin software tool and is an issue of date mis-reporting on GISAID being reflected on the cov-lineages.org website.
