### ISSUE TITLE
Mis-assignment of Omicron (B.1.1.529) variant

### ISSUE THREAD

**Issue by XubCherif** [cov-lineages/pangolin#353]
Both Docker Pangolin and the pangolin website assign the B.1.1.529 as  B.1.1.524. 
The last check I did, was downloading all Omicron sequences from GISAID, and most of them got B.1.1.524 classification.

**Comment by aineniamh** [comment]
Can you confirm you have constellations 0.0.24 because if not you don't have the latest docker container! Double check you have the latest as the docker pangolin should be assigning Omicron fine. We're aware of the web app issue and @aunderwo is working to resolve it!

**Comment by XubCherif** [comment]
Despite I was pulling covlineages/pangolin:latest in each run. In fact, constellations was 0.0.21, and it needs manual update after each time I pull.  Issue resolved by moving to staphb/pangolin:latest (giving 0.0.25 by default).  
Thanks @aineniamh ! 
Thanks also @aunderwo I noticed that you secured to resolve the web app issue rapidly
