### ISSUE TITLE
lineage assigment was not supported by scorpio

### ISSUE THREAD

**Issue by dezordi** [cov-lineages/pangolin#355]
Hi all.

I'm running the last version of pangolin:

> pangolin 3.1.16
> pangoLEARN 2021-11-25
> pango-designation v1.2.101 used for pangoLEARN and UShER training, alias version 1.2.103
> scorpio 0.3.14

Using only genomes with coverage >= 95%, I noticed some incongruencies (the same are obtained on online version https://pangolin.cog-uk.io/)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<body>

taxon | lineage | note
-- | -- | --
EPI_ISL_1161405 | None | pangoLEARN lineage assignment B.1.1.318 was not supported by scorpio
EPI_ISL_6193379 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193398 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193411 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193417 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193422 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193426 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193430 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193440 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193449 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193458 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193470 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193476 | None | pangoLEARN lineage assignment AY.39 was not supported by scorpio
EPI_ISL_6193481 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193485 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193489 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193496 | None | pangoLEARN lineage assignment AY.39 was not supported by scorpio
EPI_ISL_6193498 | None | pangoLEARN lineage assignment AY.106 was not supported by scorpio
EPI_ISL_6193502 | None | pangoLEARN lineage assignment AY.106 was not supported by scorpio
EPI_ISL_6193503 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193509 | None | pangoLEARN lineage assignment AY.106 was not supported by scorpio
EPI_ISL_6193513 | None | pangoLEARN lineage assignment AY.39 was not supported by scorpio
EPI_ISL_6193519 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193528 | None | pangoLEARN lineage assignment AY.23 was not supported by scorpio
EPI_ISL_6193534 | None | pangoLEARN lineage assignment AY.43 was not supported by scorpio
EPI_ISL_6193555 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193560 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193565 | None | pangoLEARN lineage assignment AY.39 was not supported by scorpio
EPI_ISL_6193584 | None | pangoLEARN lineage assignment AY.39 was not supported by scorpio
EPI_ISL_6193586 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193594 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193605 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193617 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193621 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193623 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193629 | None | pangoLEARN lineage assignment AY.23 was not supported by scorpio
EPI_ISL_6193633 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193646 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193653 | None | pangoLEARN lineage assignment AY.23 was not supported by scorpio
EPI_ISL_6193660 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193683 | None | pangoLEARN lineage assignment AY.23 was not supported by scorpio
EPI_ISL_6193688 | None | pangoLEARN lineage assignment AY.106 was not supported by scorpio
EPI_ISL_6193708 | None | pangoLEARN lineage assignment AY.23 was not supported by scorpio
EPI_ISL_6193715 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193717 | None | pangoLEARN lineage assignment AY.125 was not supported by scorpio
EPI_ISL_6193721 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193725 | None | pangoLEARN lineage assignment AY.34 was not supported by scorpio
EPI_ISL_6193730 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193745 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193752 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193780 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193860 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6193865 | None | pangoLEARN lineage assignment AY.39 was not supported by scorpio
EPI_ISL_6342714 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6342715 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6342717 | None | pangoLEARN lineage assignment AY.99.2 was not supported by scorpio
EPI_ISL_6342719 | None | pangoLEARN lineage assignment AY.23 was not supported by scorpio

</body>

</html>

So apparently, some genomes are annotated as None but in fact belong to some lineage, including Delta-like.

edit*: Maybe this is the expected behavior, but, can I configure the command line only to assign those cases without the scorpion?

**Comment by rmcolq** [comment]
This is deliberate - it means that the model in pangoLEARN has assigned a lineage, but that when we look explicitly for the defining mutations of that lineage (or a parent) which is a VOC/VUI using scorpio, we can't satisfy ourselves that it is a correct lineage assignment. There is no lineage that we are able to call here because a false positive VOC/VUI call would be a BAD THING.

Two things to check, given you say your sequences have high coverage:
1. Are you using a consensus building pipeline which adds in ref bases in low coverage areas? An excess of ref calls at positions which define the VOC/VUI will cause problems.
2. If you use the command line tool, you can run in `--usher` mode and get an assignment using an alternative model. This might resolve some of these if the initial call is not the VOC/VUI which was rejected by scorpio.

**Comment by rmcolq** [comment]
E.g. your first example with `--usher` comes back as B.1.575. I suspect that pangoLEARN is having problems with some of your sequences being perhaps more distantly related from the designated set? You are welcome to raise an issue in https://github.com/cov-lineages/pango-designation proposing high quality ones be added to the designated set to improve future calls with pangoLEARN

**Comment by dezordi** [comment]
Alright, thanks @rmcolq.
