### ISSUE TITLE
Minor change to clean() in ./pangolin/pangolearn/pangolearn.py

### ISSUE THREAD

**Issue by Fitzy1293** [cov-lineages/pangolin#356]
# Change how characters are handled in clean() to use a set

Checking for the character's exists here using a set might be clearer and faster.
This is a minor change. Do you allow minor pull requests for stuff like this or do they have to be more substantial?

https://github.com/cov-lineages/pangolin/blob/e6745873d13a96e29be2d1015351652e7c741534/pangolin/pangolearn/pangolearn.py#L32-L33

Changes to

```python
if x in {'T', 'A', 'G', 'C', '-'}:
		return x, False
```
#  New clean()

Behavior should not change with cleaning the sequences like this. 

```python
def clean(referenceSeq,x, loc):
	x = x.upper()

	if x in {'T', 'A', 'G', 'C', '-'}:
		return x, False

	if x == 'U':
		return 'T', False

	# replace ambiguity with the reference seq value

	if referenceSeq[loc] == x:
		return referenceSeq[loc], False

	return referenceSeq[loc], True
```

*These two pieces of code are logically equivalent so it may just be a style change, but a set might be quicker here. I'm trying to explore the code base right now so I may not have all of the context.*

**Comment by rmcolq** [comment]
We accept minor pull requests - sometimes takes us a little longer to merge them into master/a release

**Comment by aineniamh** [comment]
Just seeing this style change now and I like it, I've pushed it to master and it'll get included in next release!
