### ISSUE TITLE
DecisionTreeClassifier

### ISSUE THREAD

**Issue by manolis80** [cov-lineages/pangolin#358]
Hi,

I installed pangolin

pangolin: 3.1.17
pangolearn: 2021-12-06
constellations: v0.1.0
scorpio: 0.3.16
pango-designation used by pangoLEARN/Usher: v1.2.105
pango-designation aliases: 1.2.112

but when I'm running it I have this UserWarning

/home/.../anaconda3/envs/pangolin/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.23.1. This might lead to breaking code or invalid results. Use at your own risk.

I also did an update but the problem persist:

pangolin: 3.1.17
pangolearn: 2021-12-06
constellations: v0.1.1
scorpio: 0.3.16
pango-designation used by pangoLEARN/Usher: v1.2.105
pango-designation aliases: 1.2.114

Can I fix it locally and if yes, how?

Best,
Emmanouil

**Comment by rmcolq** [comment]
We don't believe it is a problem, just a warning from a dependancy: https://github.com/cov-lineages/pangolin/issues/246
