### ISSUE TITLE
B.1.1.228 - Valid lineage?

### ISSUE THREAD

**Issue by DOH-SML1303** [cov-lineages/pangolin#359]
I have spotted a lineage B.1.1.228 (estimate early 2020s to mid 2021, primarily U.S) that is not on the list of pangolin lineages at https://cov-lineages.org/lineage_list.html. I can't seem to find any information on this lineage, but I do see (primarily) USA sequences in GISAID that has been assigned to this lineage. Is this a valid lineage and perhaps was missed to be included in the ultimate list of lineages?

**Comment by AngieHinrichs** [comment]
Good find @DOH-SML1303.  It is a valid lineage -- [pango-designation/lineages.csv](https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv) has 165 representative sequences for B.1.1.228.  I don't know how lineage_list.html is generated, but I see B.1.1.228 does not appear in [pango-designation/lineage_notes.txt](https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt) - @aineniamh would that have anything to do with it?

The UCSC/UShER tree has 525 sequences on the branch matched up with those 165 representative sequences by usher's `matUtils annotate` method.  You can query those on the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace): paste in a sequence name like USA/CA-CZB-15467/2020, choose the full tree with GISAID, GenBank, etc, set the number of samples per subtree to 1000, click the Upload button and in a couple minutes you get a link to view the subtree in Nextstrain.

**Comment by rmbarnett-rice** [comment]
FYI, same story for `B.1.88.1`.

**Comment by DOH-SML1303** [comment]
Could we get the lineage list at https://cov-lineages.org/lineage_list.html updated with those lineages? My team scrapes the data from those pages to do a form of QC check to validate lineage data coming from our sentinel labs and it would be helpful to have those two lineages included.

**Comment by aineniamh** [comment]
Just catching up on issues here- the source of that lineage list is on pango-designation, I'm not sure how they went missing! I'll cross post to there and see if @chrisruis can track them down!

**Comment by aineniamh** [comment]
I'll close here and it they'll get found soon!
