### ISSUE TITLE
New update fails to run on usher

### ISSUE THREAD

**Issue by LukVasNVSPL** [cov-lineages/pangolin#362]
After updating to the:
- pangolin updated to v3.1.18
- pangoLEARN already latest release (2022-01-20)

And running:
`pangolin seqs.fasta --usher `

Pango fails to complete the program:
```
Error in rule usher_to_report:
    jobid: 0
    output: /home/user/tasks/concating_renaming_fastas/VDV_aLL_FASTAS/lineage_report.csv

RuleException:
KeyError in line 408 of /home/user/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk:
'lineage'
  File "/home/user/miniconda3/envs/pangolin/lib/python3.8/site-packages/pangolin/scripts/pangolearn.smk", line 408, in __rule_usher_to_report
  File "/home/user/miniconda3/envs/pangolin/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message
```
The error does not fail when run without --usher flag.
After reinstalling using conda (or mamba) `conda install -c conda-forge -c bioconda -c defaults pangolin` , the program runs successfully and fails again after update. 
The program was run on WSL system.

**Comment by rmcolq** [comment]
Will fix asap
