### ISSUE TITLE
BA.1.1 Misclassification

### ISSUE THREAD

**Issue by Rezwanuzzaman** [cov-lineages/pangolin#369]
I have noticed a few sequences (n=61) in GISAID being misclassified as BA.1.1 by a recent constellation update. Those sequences belong to the different non-omicron phylogenetic cluster (analysis report and phylogenetic tree attached here with). The collection dates of those sequences are prior to the discovery of Omicron in November, 2021.

List of sequences affected:
Accession ID
EPI_ISL_2461319
EPI_ISL_2555800
EPI_ISL_2461323
EPI_ISL_2555804
EPI_ISL_2461329
EPI_ISL_2461336
EPI_ISL_2504832
EPI_ISL_2556465
EPI_ISL_2556957
EPI_ISL_2555771
EPI_ISL_2461225
EPI_ISL_2461347
EPI_ISL_2461320
EPI_ISL_2555755
EPI_ISL_2461034
EPI_ISL_2461079
EPI_ISL_2556097
EPI_ISL_2461108
EPI_ISL_2955731
EPI_ISL_4436413
EPI_ISL_4436470
EPI_ISL_4450963
EPI_ISL_4462320
EPI_ISL_2189609
EPI_ISL_2504595
EPI_ISL_2555910
EPI_ISL_2461925
EPI_ISL_2461978
EPI_ISL_2556008
EPI_ISL_2556023
EPI_ISL_2460937
EPI_ISL_4459825
EPI_ISL_4447003
EPI_ISL_2504833
EPI_ISL_2504834
EPI_ISL_2504835
EPI_ISL_2460436
EPI_ISL_2555728
EPI_ISL_2504947
EPI_ISL_2556181
EPI_ISL_2556185
EPI_ISL_2460520
EPI_ISL_2556268
EPI_ISL_2556847
EPI_ISL_2555775
EPI_ISL_4462430
EPI_ISL_4462435
EPI_ISL_4493123
EPI_ISL_4462295
EPI_ISL_4493115
EPI_ISL_4462405
EPI_ISL_4493125
EPI_ISL_4493135
EPI_ISL_2504722
EPI_ISL_2504730
EPI_ISL_4462050
EPI_ISL_4435965
EPI_ISL_2555832
EPI_ISL_2555842
EPI_ISL_2461655
EPI_ISL_1970212

Analysis Report
![Analysis Report_screenshot](https://user-images.githubusercontent.com/92582414/152634295-34001972-7365-4085-9f19-dbdef453551d.png)

Phylogenetic tree generated by Nextclade (as well attaching nextclade.auspice.json file)

![Phylogenetic tree](https://user-images.githubusercontent.com/92582414/152634575-b74e61c0-2f9d-4003-af04-a32a1b74a3e7.png)

![Phylogenetic_tree_scatterplot](https://user-images.githubusercontent.com/92582414/152634581-01c79c8d-ce30-43e8-ad0a-15f343e4b9ac.png)

[BA.1.1_misclassification.csv](https://github.com/cov-lineages/pangolin/files/8007656/BA.1.1_misclassification.csv)

[nextclade.auspice.zip](https://github.com/cov-lineages/pangolin/files/8007657/nextclade.auspice.zip)

**Comment by rmcolq** [comment]
I have just pushed a new release which should fix these

**Comment by rmcolq** [comment]
I can confirm that these are all fixed in the latest release. They now have assignment "None"
