### ISSUE TITLE
Supplying both pangoLEARN and constellation datadirs

### ISSUE THREAD

**Issue by srx3001** [cov-lineages/pangolin#370]
Hi all,

I just realized I cannot supply both pangoLEARN and constellations file at once using --datadir.

A bit of a background here - we are using a bit of a strict versioning system, so I cant just update the tool constantly, I think it wont be  efficient enough.
Using --update or --update-data is also a no due to write permissions that are a bit problematic.
For me it would be best if I could just select which data to run with.

Is there a way around this?

I guess I could code something, if you think there is a need for it.

**Comment by rmcolq** [comment]
It should work if there is a subdirectory of your datadir called "constellations". 
Pangolin and its data dependancies receive regular updates and only calls made with the latest versions are considered valid assignments at any time.
