### ISSUE TITLE
Lineage defining mutations presence is compulsory in the variant

### ISSUE THREAD

**Issue by Pratibhakadam** [cov-lineages/pangolin#372]
Hello There,

I have been working with the genomics of Sars-CoV-2. I found that in some strains one or two Lineage defining mutations has not seen though they are determined as Delta(Other lineage defining mutations are present).

So, How the tool determine the lineage on the basis of lineage defining mutations ? Is it ok to not have one of the lineage defining mutation in the strain?

Please clarify this small doubt, It would be helpful for my understanding.

Thanks

**Comment by aineniamh** [comment]
Hi @Pratibhakadam, there is a certain level of flexibility in the required number of defining mutations for a given variant. Variants of concern (such as Delta and Omicron) are checked within the pangolin software by a tool called scorpio (https://github.com/cov-lineages/scorpio). To allow for missing data (like amplicon dropouts) or some small level of issues in bioinformatic analysis (like mistakenly calling a reference allele in areas of low coverage across the genome), there is flexibility in number of defining SNPs that must be present for a given variant. 

This curation step does not apply to all lineage calls made in pangolin, just to those associated with variants (of interest or of concern).
