### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by k-srdjan** [cov-lineages/pangolin#373]
Hi all, not a code or tool issue, but a license question.
We are looking into using pangolin as one of our reporting tools, in a commercial sense.
Is pangolin allowed for commercial use? Pangolin, pangoLEARN and scorpio use GNU General Public License v3.0.

This is not the case for pango-designation and constellations which have a non-commercial license,  but since they get used by pangolin doesn't that mean pangolin is non-commercial too?

Are we allowed to use pangolin report for commercial needs then?

Thanks!

**Comment by corneliusroemer** [comment]
@k-srdjan I can't comment on pangolin as I'm not the license holder, but Nextclade which calls the same lineages is published under an MIT license so you can use it commercially (as for example Illumina does already)
