### ISSUE TITLE
5% of BA.1.1 carrying the R346K mutations are classified as BA.1

### ISSUE THREAD

**Issue by wodanaz** [cov-lineages/pangolin#374]
Hi folks,
In our genomic surveillance data, we have been consistently finding that about 5% of samples with high quality sequencing seem to be misclassified as BA.1 even when using the most recent version of pangolin and pangoLEARN. In addition, almost all the misclassified samples BA.1s have a phylogenetic backbone that corresponds to BA.1.1 and they have great calling quality for the R346K mutation. Given the medical importance of that mutation (R346K) I hope this phenomenon can be reviewed . 

Example of read depth and quality in one sample

![image](https://user-images.githubusercontent.com/5439367/155599922-d98e4d62-66e1-4f68-bc30-d983bf843bdb.png)

and Phylogeny:

and an example of the tree placing of the BA.1 (These samples are confirmed to have the R346K mutation)

![image](https://user-images.githubusercontent.com/5439367/155600430-fe96dc56-7ef5-4bb6-97de-79592707d7d8.png)

Thank you so much an keep up with the great work

Warmly,

Alejandro Berrio
Duke University

**Comment by aineniamh** [comment]
Hi @wodanaz, thanks for your comment- if possible can you file this issue in [pango-designation](https://github.com/cov-lineages/pango-designation) as this repo is specifcially for bugs with the software rather than issues with lineage assignments/ designations.
