### ISSUE TITLE
Omicron samples reassigned as 'None' in pango version 3.1.20

### ISSUE THREAD

**Issue by Sreelekshmi-291** [cov-lineages/pangolin#377]
Around 300 of our in-house genome samples were assigned 'BA.2' in the previous versions of Pango (versions- 3.1.17 & 3.1.19) but were reassigned as 'None' in the latest pango update (version-3.1.20).
The samples are of medium to high coverage.
Attached is a file containing sample sequences
[none_issue_seqs.txt](https://github.com/cov-lineages/pangolin/files/8161727/none_issue_seqs.txt)

**Comment by rmcolq** [comment]
They do look like BA.2 sequences and are being rejected at the moment because they have the reference C allele at defining nucleotide site C10198T. If you are confident that this is a true reference allele at this site, I can look to update the constellation for BA.2

**Comment by stefanhelfert** [comment]
Which kit were the samples analysed with?

**Comment by Sreelekshmi-291** [comment]
> Around 300 of our in-house genome samples were assigned 'BA.2' in the previous versions of Pango (versions- 3.1.17 & 3.1.19) but were reassigned as 'None' in the latest pango update (version-3.1.20). The samples are of medium to high coverage. Attached is a file containing sample sequences [none_issue_seqs.txt](https://github.com/cov-lineages/pangolin/files/8161727/none_issue_seqs.txt)

We checked for the mutation C10198T in our samples and 84% of them have the reference allele C at site 10198.

**Comment by Sreelekshmi-291** [comment]
> Which kit were the samples analysed with?
We use Illumina COVIDSeq

**Comment by rmcolq** [comment]
I'll update the definition shortly

**Comment by rmcolq** [comment]
I have just published a new constellations release which should fix this!
