### ISSUE TITLE
Cannot access pangolin web application 

### ISSUE THREAD

**Issue by coreymeloche** [cov-lineages/pangolin#385]
![PANGO Error](https://user-images.githubusercontent.com/86015486/159707752-22880bb2-ec5b-4bda-979a-16045dfb4546.PNG)

Good morning - I have been trying to access the pangolin web application for the last 24 hours will no success. Please let me know when it is expected to be up and running. Or is there an new web address? Thank you in advance!

**Comment by AngieHinrichs** [comment]
@antunderwood [antunderwood](https://github.com/antunderwood) ?

**Comment by CorinY** [comment]
Hi Angie,

Apologies to our users but we've got a temporary issue with a handful of our websites at the CGPS and the Pangolin web server is one of them. We're trying to resolve it, and they should be back up fairly soon. I will comment back here once I know it is up again.

Best wishes,  
Corin

**Comment by jemstone78** [comment]
Pangolin web application isn't working for us either. Does anyone know if the web application will also be updated? The current version was from 2-28-2022.

**Comment by CorinY** [comment]
Hi @jemstone78 ,

I can also confirm it was updated shortly before going down. You can run your genomes against the newest version also at https://pathogen.watch/, though you have to register an account there.

Best wishes,  
Corin

**Comment by CorinY** [comment]
Hi @coreymeloche, @AngieHinrichs, @jemstone78,

https://pangolin.cog-uk.io/ is back online, our apologies for any problems this may have caused. This was a pure logistical glitch and we've set things up so it doesn't happen again.

Best,
Corin

**Comment by aineniamh** [comment]
Glad this has been resolved, thanks for sorting it out @CorinY!
