### ISSUE TITLE
Question regarding update to v4.0

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#390]
Hi,

regarding the upcoming update to v4.0, will it be possible to continue to update pango-designation separately in version 3. We need to do some changes in our Quebec pipeline prior to use your new version 4

Thanks
Eric

**Comment by aineniamh** [comment]
Hi @EricFournier3, we're going to continue to release pangoLEARN and pango-designation as before for the near future to give everyone a bit of time to make the changes they need. It will eventually get phased out to just pangolin-data (although pango-designation will continue to be updated as before, it will no longer be a pangolin dependency).

**Comment by EricFournier3** [comment]
Thank you @aineniamh, but when we will execute `pangolin --update`, does it will automatically update to pangolin v4 or we will have the choice to install v4 separately ?

**Comment by aineniamh** [comment]
If you try update pangolin it will update to the latest version, which will be 4.0. If you use the `--update-data` flag instead it will only update the data dependencies rather than the software.

**Comment by EricFournier3** [comment]
perfect. You can close this ticket. Have a nice day Aine

**Comment by rrdavis77** [comment]
Sorry to piggy back on this topic.  With the imminent release of 4.0, can you share the new headers and how they are different from 3.*?  Wanted to start changing our pipeline in anticipation!  Thanks!!!

**Comment by aineniamh** [comment]
Of course, no worries! They're here: https://cov-lineages.org/resources/pangolin/output.html and an example output file is attached below!
[lineage_report.csv](https://github.com/cov-lineages/pangolin/files/8390221/lineage_report.csv)

**Comment by RaverJay** [comment]
Looks good, this will simplify things a lot

**Comment by aineniamh** [comment]
Going to close this now as the release notes for the update have all this info in them now!
