### ISSUE TITLE
Missing lineages from pango-designation v1.2.141 in lineages.hash.csv with pangolin pangolin v4.0.1

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#402]
Hi,

is this normal that we don't see recombinant XP, XQ, XR and XR in **/envs/pangolinV4/lib/python3.8/sitepackages/pangolin_data/data/lineages.hash.csv  ?

```
(pangolinV4) [TestRecombinant]$ pangolin --all-versions
pangolin: 4.0.1
pangolin-data: 1.2.133
constellations: v0.1.4
scorpio: 0.3.16
pangolin-assignment: v1.2.133
```
Thank you
Eric

**Comment by AngieHinrichs** [comment]
Hi @EricFournier3 -- yes, those new recombinant lineages were designated very recently, in pango-designation release [v1.2.141](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.141).  Your pangolin-data version corresponds to an earlier pango-designation release, v1.2.133.  Currently @aineniamh is re-training the pangoLEARN model, and I am working on a new lineageTree.pb for UShER, for pango-designation v1.2.141.  After the next pangolin-data release, you should be able to pick that up by running `pangolin --update-data`.

**Comment by EricFournier3** [comment]
Ok, thank you @AngieHinrichs.
