### ISSUE TITLE
--use-assignment-cache error: AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jacaravas** [cov-lineages/pangolin#410]
Hello,

Thank you for helping me resolve my [previous issue](https://github.com/cov-lineages/pangolin/issues/403).  Unfortunately, I encountered another error immediately after that was solved.

When running with `--use-assignment-cache`, I am getting the following error:
```
Using UShER as inference engine.
Traceback (most recent call last):
  File "/home/XXX/my_conda_envs/pangolin-4/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "/home/XXX/my_conda_envs/pangolin-4/lib/python3.8/site-packages/pangolin/command.py", line 229, in main
    generate_final_report(preprocessing_csv, inference_csv, cached_csv, config[KEY_ALIAS_FILE], constellation_list, config[KEY_PANGOLIN_DATA_VERSION],config[KEY_ANALYSIS_MODE], args.skip_designation_cache, config[KEY_OUTFILE],config)
  File "/home/XXX/my_conda_envs/pangolin-4/lib/python3.8/site-packages/pangolin/utils/report_collation.py", line 243, in generate_final_report
    not expanded_pango_lineage.startswith(expanded_scorpio_lineage) and \
AttributeError: 'NoneType' object has no attribute 'startswith'
```

The lineage_report.csv file is truncated and contains only 329 of the 1000 sequences I analyzed.  `--analysis-mode accurate` runs to completion

The 330th sequence might be causing the problem. It has a high "Ambiguous_content" (0.43) relative to the 329 sequences that made it into the lineage file before it encountered the error, but otherwise it seems to resemble other low quality sequences that were processed successfully before it.

`cache_assigned.csv`

hash | lineage | conflict | version | note
-- | -- | -- | -- | --
f5aa391ccab4a9861fa4ebc2baedece7 | Unassigned | |PUSHER-v1.2.127 | Assigned from cache

`preprocessing.csv`

name | hash | lineage | scorpio_constellations | scorpio_mrca_lineage | scorpio_incompatible_lineages | scorpio_support | scorpio_conflict | scorpio_notes | designated | qc_status | qc_notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0280d14c94f4003dd03ce01c23ddf3af380674b1 | f5aa391ccab4a9861fa4ebc2baedece7 | Alpha (B.1.1.7-like) | B.1.1.7 |   | 0.65 | 0 | scorpio call: Alt alleles 15; Ref alleles 0; Amb alleles 8; Oth alleles 0 | FALSE | fail | Ambiguous_content:0.43

`designation_status.csv`

hash | designated | lineage
-- | -- | --
f5aa391ccab4a9861fa4ebc2baedece7 | FALSE |  

Command:
```
pangolin test_data.fasta -o test -t 2 --use-assignment-cache --verbose --no-temp
```

Versions:
```
pangolin --all-versions
pangolin: 4.0.2
pangolin-data: 1.2.133
constellations: v0.1.4
scorpio: 0.3.16
pangolin-assignment: v1.2.133
```

Thank you

**Comment by AngieHinrichs** [comment]
Thanks @jacaravas!  I was able to find the sequence that matches that hash and triggers the bug, and reproduced the crash locally, so I should be able to fix it soon.

**Comment by AngieHinrichs** [comment]
Thanks again @jacaravas -- I believe this is fixed now in the latest source (unreleased).  Hopefully @aineniamh can review and maybe roll another patch release?
