### ISSUE TITLE
Error in rule rule usher_inference - invalid option for faToVcf

### ISSUE THREAD

**Issue by BCArg** [cov-lineages/pangolin#417]
Hi,

I have been using pangolin, below is the env information:

```
name: pangolin
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - biopython=1.74=py38h516909a_0
  - boost-cpp=1.74.0=h312852a_4
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.5=py38ha65f79e_0
  - chardet=4.0.0=py38h578d9bd_1
  - coincbc=2.10.5=hcee13e7_1
  - configargparse=1.5=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - datrie=0.8.2=py38h497a2fe_2
  - docutils=0.17.1=py38h578d9bd_0
  - filelock=3.0.12=pyh9f0ad1d_0
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.18=pyhd8ed1ab_0
  - gofasta=0.0.4=h9ee0642_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.6.0=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_core=4.7.1=py38h578d9bd_0
  - k8=0.2.5=h9a82719_1
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libgomp=9.3.0=h2828fa1_19
  - liblapack=3.9.0=9_openblas
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libuuid=2.32.1=h7f98852_1000
  - lz4-c=1.9.3=h9c3ff4c_0
  - mafft=7.480=h779adbc_0
  - minimap2=2.20=h5bf99c6_0
  - mysql-connector-c=6.1.11=h6eb9d5d_1007
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.21.0=py38h9894fe3_0
  - openssl=1.1.1k=h7f98852_0
  - pip=19.3.1=py38_0
  - psutil=5.8.0=py38h497a2fe_1
  - pulp=2.4=py38h578d9bd_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.10=h49503c6_1_cpython
  - python_abi=3.8=2_cp38
  - pyyaml=5.4.1=py38h497a2fe_0
  - ratelimiter=1.2.0=py_1002
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - setuptools=49.6.0=py38h578d9bd_3
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=5.1.0=pyhd8ed1ab_1
  - smmap=3.0.5=pyh44b312d_0
  - snakemake-minimal=6.5.1=pyhdfd78af_0
  - sqlite=3.36.0=h9cd32fc_0
  - stopit=1.1.2=py_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tk=8.6.10=h21135ba_1
  - toposort=1.6=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ucsc-fatovcf=407=hd50662f_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - usher=0.3.2=h7b4d82f_0
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py38h497a2fe_3
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - constellations==0.1.4
    - joblib==1.0.1
    - pandas==1.0.1
    - pango-designation==1.2.141
    - pangolearn==2022-03-22
    - pangolin==4.0.2
    - pangolin-data==1.2.133
    - pysam==0.16.0.1
    - python-dateutil==2.8.1
    - pytz==2021.1
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - scorpio==0.3.16
    - threadpoolctl==2.1.0
prefix: /home/ngs/.conda/envs/pangolin
```

I am getting the following error:

```
Using UShER as inference engine.
-includeNoAltN is not a valid option
[Thu Apr  7 08:09:37 2022]
Error in rule usher_inference:
    jobid: 3
    output: /tmp/253103.1.nipt.q/tmp9jvuzk12/clades.txt
    log: /tmp/253103.1.nipt.q/tmp9jvuzk12/logs/usher.log (check log file(s) for error message)
    shell:
        
        echo "Using UShER as inference engine."
        if [ -s /tmp/253103.1.nipt.q/tmp9jvuzk12/not_cache_assigned.fasta ]; then
            cat /home/ngs/.conda/envs/pangolin/lib/python3.8/site-packages/pangolin/data/reference.fasta > /tmp/253103.1.nipt.q/tmp9jvuzk12/sequences.withref.fa
            echo >> /tmp/253103.1.nipt.q/tmp9jvuzk12/sequences.withref.fa
            cat /tmp/253103.1.nipt.q/tmp9jvuzk12/not_cache_assigned.fasta >> /tmp/253103.1.nipt.q/tmp9jvuzk12/sequences.withref.fa
            faToVcf -includeNoAltN /tmp/253103.1.nipt.q/tmp9jvuzk12/sequences.withref.fa /tmp/253103.1.nipt.q/tmp9jvuzk12/sequences.aln.vcf
            usher -n -D -i /home/ngs/.conda/envs/pangolin/lib/python3.8/site-packages/pangolin_data/data/lineageTree.pb -v /tmp/253103.1.nipt.q/tmp9jvuzk12/sequences.aln.vcf -T 1 -d '/tmp/253103.1.nipt.q/tmp9jvuzk12' &> /tmp/253103.1.nipt.q/tmp9jvuzk12/logs/usher.log
        else
            rm -f /tmp/253103.1.nipt.q/tmp9jvuzk12/clades.txt
            touch /tmp/253103.1.nipt.q/tmp9jvuzk12/clades.txt
        fi
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message
```
So far I could not resolve the issue by reinstalling faToVcf. Also it appears that pangolin can finish if I just create a new env from scratch and install it via `mamba install -c bioconda pangolin`

Thanks for checking

**Comment by rgerhards** [comment]
I had a similar issue just this night. I ran out of main memory on the VM. I can see in syslog that the OS out-of-memory killer was activated and killed `faToVcf`. My VM had 12GiB main memory (plus 1 GiB "emergency swap").

Another thing to check is temp disk space? I had a couple of similar abort (but in other components) when I ran out of disk space.

**Comment by aineniamh** [comment]
```
Using UShER as inference engine.
-includeNoAltN is not a valid option
```
You just need an updated version of faToVcf (same issue in #394 and #398!).
The latest pangolin environment file has `ucsc-fatovcf>=426` in it. If you try updating the environment, as it looks like you're running `ucsc-fatovcf=407=hd50662f_0`.

**Comment by BCArg** [comment]
Thanks, updating `ucsc-fatovcf=426` solved the issue

**Comment by Sarahvl** [comment]
I updated ucsc-fatovcf=426 but my pipeline is still not making a pangolin result file again. 

I ready on the issue #394 that the directories need to be changed (pangoLEARN and pango_designation directories need to be replaced to directory pangolin_data), but I don't know how to do this?

**Comment by AngieHinrichs** [comment]
@Sarahvl we recommend a conda environment update as described here:
https://cov-lineages.org/resources/pangolin/updating.html

If it's still not working after you do a full update, please send the complete output of pangolin so we can look for error messages.

**Comment by Sarahvl** [comment]
Dear,

I managed to get the pangolin working (from command line) but it is not working from the script (which was written by a consultant who doesn't work here anymore). So the problem is not pangolin itself.

We will try to contact the consultant to help with the script and to explain to us what was wrong.

thank you


ZNA | Sarah Van Lent | Klinisch Laboratorium | Wetenschappelijk medewerker Microbiologie

ZNA Middelheim | Lindendreef 1 – 2020 Antwerpen

Tel. +32 3 280 48 13



>> Bezoek onze website: zna.be<https://zna.be/>
>> Volg ons op Facebook<https://www.facebook.com/ZiekenhuisNetwerkAntwerpen>, Twitter<https://twitter.com/ZNAwoordvoerder>, LinkedIn<https://www.linkedin.com/in/znantwerpen/>, YouTube<https://www.youtube.com/user/znantwerpen>

Deze e-mail en eventuele bijlagen zijn uitsluitend bestemd voor de geadresseerde. De informatie in de e-mail is strikt persoonlijk en vertrouwelijk. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Indien deze e-mail niet voor jou bestemd is, vragen wij je per kerende de afzender hiervan op de hoogte te brengen. Verwijder het bericht daarna uit je mailbox. Bekendmaking, verspreiding en/of doorgeven van deze e-mail aan derden is niet toegestaan.
________________________________
Van: Angie Hinrichs ***@***.***>
Verzonden: dinsdag 12 april 2022 18:23
Aan: cov-lineages/pangolin ***@***.***>
CC: Sarah Van Lent ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [cov-lineages/pangolin] Error in rule rule usher_inference - invalid option for faToVcf (Issue #417)


@Sarahvl<https://github.com/Sarahvl> we recommend a conda environment update as described here:
https://cov-lineages.org/resources/pangolin/updating.html

If it's still not working after you do a full update, please send the complete output of pangolin so we can look for error messages.
