### ISSUE TITLE
Disagreements between USHER and PangoLEARN for some recombinants

### ISSUE THREAD

**Issue by gyebra-phs** [cov-lineages/pangolin#418]
Hi all, 

I was wondering if I could get some advice on the following issue: we have been testing the new Pangolin v4 and seen that, even though PangoLEARN and USHER agree on the lineage assignment in most cases, there are some differences particularly when analysing recombinant sequences (just to clarify, both runs had Scorpio deactivated because it seems to overwrite any recombinant assignment which I guess is the expected behaviour).

For example, we have 3 genome that are classified as the XD recombinant by USHER, but are classified as AY.4.2.2 (2) and B.1 (1) by PangoLEARN;. We have examined them in detail and, although they do show some evidence of recombination (I'm using the [sc2rf](https://github.com/lenaschimmel/sc2rf) software) some of these sequences are not very good quality (10-15% of Ns) and appear as outgroups when included in a tree with reference XDs from GISAID.

Similarly, we have 1 genome classified as XF by USHER and as BA.1.16 by PangoLEARN. This genome has a very good quality, and it doesn't seem to have any reliable Delta segments --although it might be particularly close to the BA.1 segment in XF. In a tree, again, it looks different enough from the XFs in GISAID. 

I guess my question is: I know that USHER is supposed to be the more accurate method, but is it more reliable than PangoLearn, particularly for recombinant lineages?

Many thanks!

Gonzalo

**Comment by aineniamh** [comment]
Hey Gonzalo, I completely missed this issue- recombination assignment is something we haven't fully solved right now. We're explicitly checking for XE recombinants through scorpio & constellations, but others are being assigned using the inference methods. UShER is likely to be more reliable in the case of recombinant lineages as @AngieHinrichs is hand-crafting the tree and branches for these lineages. For pangoLEARN, the model is being trained based on the information given into it, and that includes recombinant lineages, but we're not post-hoc checking most of these.
