### ISSUE TITLE
Information about analysis mode ends up in --all-versions output and --aliases output

### ISSUE THREAD

**Issue by KHajji** [cov-lineages/pangolin#420]
This seems to me to be unintended behaviour. Especially if the output of these commands is considered to be valid yaml and json in e.g. pipelines.

https://github.com/cov-lineages/pangolin/blob/663c6d26445fd8f2aad1794b6f6ad8da1f1d63af/pangolin/command.py#L143-L157

**Comment by aineniamh** [comment]
Fixed now in v4.0.4!
