### ISSUE TITLE
BUG: `attributeError in line 28 of pangolearn.smk: 'DecisionTreeClassifier' object has no attribute 'n_features_'`

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pangolin#427]
When running pangolin v4.0.4 installed via bioconda with mode pangolearn, I get the following error:

`attributeError in line 28 of pangolearn.smk: 'DecisionTreeClassifier' object has no attribute 'n_features_'`

<img width="2546" alt="image" src="https://user-images.githubusercontent.com/25161793/162981070-b0eb61e6-e91a-4958-8856-2317e9bf9a0c.png">

<img width="2544" alt="image" src="https://user-images.githubusercontent.com/25161793/162981353-91c25fd1-7554-442d-8337-e5e940581a98.png">

<img width="2551" alt="image" src="https://user-images.githubusercontent.com/25161793/162981085-ff204a7a-07ef-4689-b56c-72f86255098e.png">

Is this fixed in v4.0.5? It's not yet on bioconda. An earlier version of v4 worked for pangolearn, so this is probably a regression of some sort.

**Comment by aineniamh** [comment]
<img width="752" alt="Screenshot 2022-04-12 at 15 30 07" src="https://user-images.githubusercontent.com/11678307/162985918-942e7292-a795-4e9a-9e05-3dbaea433107.png">
All runs fine on my system and it's passing github actions tests, perhaps check your install?

**Comment by corneliusroemer** [comment]
Ah that's good news :) 

Strange, I'll reinstall and try also locally. Let's see if anyone else will have this problem. Maybe a broken model installation.

Bioconda is struggling with v4 I think

**Comment by fmaguire** [comment]
I strongly suspect this may be one of those "conda has randomly decided to install an odd and weirdly old version of certain dependencies (e.g., sklearn)" situations. 

 It is always an annoying bug to track down because it seems local cached package versions is a major factor.

**Comment by aineniamh** [comment]
The error suggests it's looking for a decision tree classifier, which would be related to pangolin 3.0, rather than 4.0. It could be that you've conflicting versions of pangolin installed and it's mixing inputs?

**Comment by aineniamh** [comment]
Although, I'm not very familiar with how the rf model works- so maybe the individual components are just called decision tree classifiers anyway.

**Comment by corneliusroemer** [comment]
Alright, uninstall, reinstall and `--update` fixed it.

If anyone encounters this, try it. If it doesn't work, comment and we'll reopen.
