### ISSUE TITLE
Error in iqtree_with_guide_tree

### ISSUE THREAD

**Issue by 65eg** [cov-lineages/pangolin#431]
I am unable to get Pangolin to successfully complete a run.  The error generated is CalledProcessError in line 76 of /miniconda3/lib/python3.7/site-packages/pangolin/scripts/assign_query_lineage.smk:

Command 'set -euo pipefail;  iqtree -s PangolinTemp/tmpplbvwzup/tax242361tax.aln.fasta -bb 1000 -au -alrt 1000 -m HKY -g /miniconda3/lib/python3.7/site-packages/lineages/data/anonymised.aln.safe.fasta.treefile -quiet -nt 1 -o 'outgroup_A'' returned non-zero exit status 2.

The program () is running in the slurm cluster environment as /miniconda3/bin/pangolin $FASTA --outfile $OUTPUT --outdir $OUTPUTDIR --tempdir $TEMPDIR

pangolin -v returns
pangolin 1.1.14

**Comment by aineniamh** [comment]
Hi @65eg. It looks like you're running a very old version of pangolin (~2 years old)- we're on pangolin v4.0 now. I suggest uninstalling your current version (to avoid conflicts) and reinstall from scratch!

**Comment by aineniamh** [comment]
Closing this as updating from pangolin 1.0 to 4.0 will resolve this issue.
