### ISSUE TITLE
Testing of pangolearn analysis mode

### ISSUE THREAD

**Issue by wm75** [cov-lineages/pangolin#433]
I'm trying to update our Galaxy wrapper of pangolin to v4, but our tests with --analysis-mode pangolearn are failing without a proper error message. The same tests are passing locally for me.
Could it be that the pangolearn model has just become too resource-hungry by now to be compatible with our CI?
If that's the case, is there a less challenging way to test the pangolearn mode?

Here's my currently stalled PR: https://github.com/galaxyproject/tools-iuc/pull/4494
I've pulled the important parts of the CI output into the conversation to make it easier for you to help if you can.

Thanks a lot for any insight!

**Comment by aineniamh** [comment]
Have a read through issue https://github.com/cov-lineages/pangolin/issues/395, we've added a warning to the latest version as random forest does take more RAM, but actually shows greater accuracy whilst still being a very fast method!

**Comment by wm75** [comment]
Thanks @aineniamh. Had missed the issue with the actual numbers.
Is their no workaround for testing purposes then? If possible, I would like to have the pangolearn branch covered by our Galaxy wrapper tests and not just test usher exclusively.

**Comment by wm75** [comment]
btw, my local machine only has 8GB of memory, and if I close all other programs I can make our tests (which use just one single sequence) pass using one thread only. So at least under ideal conditions you can still get away with less than the 12GB mentioned in #395 :)
