### ISSUE TITLE
Error in rule usher_inference

### ISSUE THREAD

**Issue by githubuser238** [cov-lineages/pangolin#435]
Hello,

After updating pangolin, I am now running into the error below.

Output for pangolin -v: pangolin 4.0.5
Output for pangolin -pv: pangolin-data 1.3

I've tried reinstalling the programs and updating. I've also tried chmod x+a /data/usr/.conda/envs/pangolin/bin/faToVcf

Any advice would be greatly appreciated!

The usher.log file comes out empty. 

Input command: pangolin --analysis-mode usher  alignment.fasta --max-ambig 0.7 -t 16 --no-temp

Error message:

Using UShER as inference engine.
/usr/bin/bash: line 6: /data/usr/.conda/envs/pangolin/bin/faToVcf: Permission denied
[Sun Apr 17 17:09:45 2022]
Error in rule usher_inference:
    jobid: 3
    output: /tmp/tmp_fnf84nr/clades.txt
    log: /tmp/tmp_fnf84nr/logs/usher.log (check log file(s) for error message)
    shell:

        echo "Using UShER as inference engine."
        if [ -s /tmp/tmp_fnf84nr/not_cache_assigned.fasta ]; then
            cat /data/usr/.local/lib/python3.7/site-packages/pangolin/data/reference.fasta > /tmp/tmp_fnf84nr/sequences.withref.fa
            echo >> /tmp/tmp_fnf84nr/sequences.withref.fa
            cat /tmp/tmp_fnf84nr/not_cache_assigned.fasta >> /tmp/tmp_fnf84nr/sequences.withref.fa
            faToVcf -includeNoAltN /tmp/tmp_fnf84nr/sequences.withref.fa /tmp/tmp_fnf84nr/sequences.aln.vcf
            usher -n -D -i /opt/miniconda3/lib/python3.7/site-packages/pangolin_data/data/lineageTree.pb -v /tmp/tmp_fnf84nr/sequences.aln.vcf -T 16 -d '/tmp/tmp_fnf84nr' &> /tmp/tmp_fnf84nr/logs/usher.log
        else
            rm -f /tmp/tmp_fnf84nr/clades.txt
            touch /tmp/tmp_fnf84nr/clades.txt
        fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message

**Comment by AngieHinrichs** [comment]
Sorry to hear you're having trouble with the update!  To help debug, I have a few questions:

1. What method did you use to update pangolin?  (We recommend a full conda environment update, instructions here: https://cov-lineages.org/resources/pangolin/updating.html)

2. Can you copy-paste the output of these commands?
```
ls -l /data/usr/.conda/envs/pangolin/bin/faToVcf
file /data/usr/.conda/envs/pangolin/bin/faToVcf
chmod a+x /data/usr/.conda/envs/pangolin/bin/faToVcf
uname -a
/data/usr/.conda/envs/pangolin/bin/faToVcf
```

**Comment by yxuil** [comment]
had the same error after update to the latest version (4.0.5). 

faToVcf doesn't seem to have `-includeNoAltN` option

```$ faToVcf
faToVcf - Convert a FASTA alignment file to Variant Call Format (VCF) single-nucleotide diffs
usage:
   faToVcf in.fa out.vcf
options:
   -ambiguousToN         Treat all IUPAC ambiguous bases (N, R, V etc) as N (no call).
   -excludeFile=file     Exclude sequences named in file which has one sequence name per line
   -includeRef           Include the reference in the genotype columns
                         (default: omitted as redundant)
   -maskSites=file       Exclude variants in positions recommended for masking in file
                         (typically https://github.com/W-L/ProblematicSites_SARS-CoV2/raw/master/problematic_sites_sarsCov2.vcf)
   -minAc=N              Ignore alternate alleles observed fewer than N times
   -noGenotypes          Output 8-column VCF, without the sample genotype columns
   -ref=seqName          Use seqName as the reference sequence; must be present in faFile
                         (default: first sequence in faFile)
   -resolveAmbiguous     For IUPAC ambiguous characters like R (A or G), if the character
                         represents two bases and one is the reference base, convert it to the
                         non-reference base.  Otherwise convert it to N.
   -startOffset=N        Add N bases to each position (for trimmed alignments)
   -vcfChrom=seqName     Use seqName for the CHROM column in VCF (default: ref sequence)
in.fa must contain a series of sequences with different names and the same length.
Both N and - are treated as missing information.

```

**Comment by aineniamh** [comment]
HI @githubuser238,

You just need an updated version of faToVcf (same issue in https://github.com/cov-lineages/pangolin/issues/417,  https://github.com/cov-lineages/pangolin/issues/394 and https://github.com/cov-lineages/pangolin/issues/398!).
The latest pangolin environment file has ucsc-fatovcf>=426 in it. If you try updating the environment, this should resolve your issue.

**Comment by aineniamh** [comment]
That looks like you still don't have permissions to modify faToVcf, because it's symlinked so it's failing to update versions.
```-bash: /data/usr/.conda/envs/pangolin/bin/faToVcf: Permission denied```

If you check `faToVcf --version`, I suspect it might not have updated correctly.

**Comment by AngieHinrichs** [comment]
Thanks @githubuser238 for sending the command results.  Sorry but at this point I think the best approach would be to remove your pangolin conda environment, recreate it, and reinstall pangolin:
```
conda env remove --name pangolin
conda env create --name pangolin
conda activate pangolin
conda install -c bioconda -c conda-forge -c defaults pangolin
```

**Comment by aineniamh** [comment]
Going to close as the issue is now stale, hope @githubuser238 managed to uninstall and reinstall successfully!
