### ISSUE TITLE
Meaning/handling of pangolin Unassigned, scorpio-replaced lineages

### ISSUE THREAD

**Issue by wm75** [cov-lineages/pangolin#445]
Just finished lineage reassignment with pangolin v4 for a huge set of sequences and I notice that the vast majority of "Unassigned" lineages in the output looks like this:

```
taxon   lineage conflict        ambiguity_score scorpio_call    scorpio_support scorpio_conflict        scorpio_notes   version pangolin_version        scorpio_version constellation_version   is_designated   qc_status       qc_notes        note    expanded_lineage
ERR9268548	Unassigned	0.0		Omicron (Unassigned)	1.0	0.0	scorpio call: Alt alleles 33; Ref alleles 0; Amb alleles 0; Oth alleles 0	PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.1	Usher placements: XE(4/4); scorpio replaced lineage inference XE	Unassigned
ERR9268560	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1.1(1/1); scorpio replaced lineage inference BA.1.1.1	Unassigned
ERR9268564	Unassigned	0.0		XE-parent1	0.95	0.03		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/1); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268593	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.06	Usher placements: BA.1(1/1); scorpio replaced lineage inference BA.1	Unassigned
ERR9268577	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1.15(1/1); scorpio replaced lineage inference BA.1.1.15	Unassigned
ERR9268586	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/1); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268599	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/1); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268620	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.17.2(1/1); scorpio replaced lineage inference BA.1.17.2	Unassigned
ERR9268621	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.03	Usher placements: BA.1.1.13(1/1); scorpio replaced lineage inference BA.1.1.13	Unassigned
ERR9268624	Unassigned	0.5		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/2) BA.1.1.2(1/2); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268626	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/1); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268627	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.03	Usher placements: BA.1(1/1); scorpio replaced lineage inference BA.1	Unassigned
ERR9268635	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.03	Usher placements: BA.1.1.14(2/2); scorpio replaced lineage inference BA.1.1.14	Unassigned
ERR9268696	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/1); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268658	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.15.1(1/1); scorpio replaced lineage inference BA.1.15.1	Unassigned
ERR9268661	Unassigned	0.0		XE-parent1	0.95	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.04	Usher placements: BA.1.17.2(1/1); scorpio replaced lineage inference BA.1.17.2	Unassigned
ERR9268671	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1.1(1/1); scorpio replaced lineage inference BA.1.1	Unassigned
ERR9268686	Unassigned	0.0		XE-parent1	0.97	0.0		PUSHER-v1.8	4.0.5	0.3.16	v0.1.9	False	pass	Ambiguous_content:0.02	Usher placements: BA.1(1/1); scorpio replaced lineage inference BA.1	Unassigned
```
I'm puzzled by both the meaning of these "assignments" and how we are supposed to handle it.

**Comment by wm75** [comment]
What I do understand is that scorpio replaced the original lineage assignment for all of these, but does that mean that the final pangolin lineage assignment should be "Unassigned"?

**Comment by wm75** [comment]
The "Unassigned" cases are also clearly from the first wave of omicron. Look at this subset of our (the Galaxy project's) tracking efforts of COG-UK data:
![Screenshot from 2022-05-06 11-09-51](https://user-images.githubusercontent.com/4742081/167102898-a2e87568-4f89-4735-bc35-97ad67754b77.png)

**Comment by wm75** [comment]
and this is independent of the assignment engine used, but seems to be a consequence of scorpio lineage replacement only.

**Comment by aineniamh** [comment]
It's not possible for scorpio to assign an XE parent as a lineage, but in this case it was the best scoring constellation. It didn't quite meet the criteria to be classified as an XE recombinant lineage, but The BA.* sublineage constellation isn't met/ isn't ranked as highly as the other one. 

Now, this may be something to do with us removing the probable labels from the constellations, we now have rather strict criteria for scorpio to specifically overwrite something, but perhaps the XE parent lineage constellations need to have BA.1 and BA.2 added as compatible assignments so that the UShER assignments don't get overwritten if cases like this occur.

**Comment by wm75** [comment]
I see, thanks for the explanation @aineniamh !
Maybe it's generally a good idea to fall back to the original assignments if scorpio replacement would result in "Unassigned"?

Just to mention it: this isn't some few exotic cases, but the above plot is based on just a bit over 50,000 samples.

**Comment by aineniamh** [comment]
In general the purpose of scorpio is to avoid false positives as much as possible- for instance if B.1.1.7 is called by usher or pangolearn, but scorpio identifies it doesn't have the defining mutations it will overwrite as Unassigned. In this case, the XE recombinant constellations complicate this situation as we don't want a parent lineage to be assigned. 
I believe https://github.com/cov-lineages/constellations/tree/recomb-compatible  will resolve the issue, but will need to test this theory! We don't want to inadvertantly have false positive recombinants.

**Comment by wm75** [comment]
If it helps we could reassign all our data with constellations from the recomb-compatible branch I think. If you're confident enough about the change (it will take some hours to recompute everything), just give me a go.

**Comment by aineniamh** [comment]
Oh that would be a great independent check actually if you're happy to do that! I'm currently running a local test on a set of XE genomes and BA.1 genomes.

**Comment by wm75** [comment]
Aah! I realized only now that you've addressed exactly this issue here in scorpio 0.3.17 already. Our Galaxy environment is still at 0.3.16 (see also the report above). Rerunning some of the above lineages with 0.3.17 restores the assignments.
So, in a way your recomb-compatible branch of constellations is a solution that doesn't require a scorpio update and scorpio 0.3.17 implements what I had in mind but couldn't phrase accurately enough with:
> Maybe it's generally a good idea to fall back to the original assignments if scorpio replacement would result in "Unassigned"?

**Comment by aineniamh** [comment]
Ah, I didn't quite realise that was the same issue as before- if the latest scorpio fixes your issue, maybe I'll leave the constellation as is then.

**Comment by wm75** [comment]
I *think* upgrading scorpio will fix it, and I'm going to close this now. Can still reopen if there are questionable remaining Unassigned cases in the full dataset.
Thanks for all your help and sorry for stealing some of your time!
