### ISSUE TITLE
Scorpio lineage replacement results in "Unassigned" lineage.

### ISSUE THREAD

**Issue by eddieimada** [cov-lineages/pangolin#449]
Dear pangolin developers and users,

After updating to the latest version (4.0.6), I started to observe a high number of "Unassigned" samples, that had been assigned lineages successfully in previous versions. This unassigned calls occurs even when the samples pass QC check.

I noticed that when Scorpio replaces usher lineage inference, the "lineage" field becomes "Unassigned". To confirm this, I disabled scorpio and the lineage field was properly populated (see bellow).

With Scorpio:

> taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,scorpio_notes,version,pangolin_version,scorpio_version,constellation_version,is_designated,qc_status,qc_notes,note
> test1,Unassigned,0.0,,Omicron (Unassigned),0.79,0.06,scorpio call: Alt alleles 26; Ref alleles 2; Amb alleles 5; Oth alleles 0,PUSHER-v1.8,4.0.6,0.3.17,v0.1.10,False,pass,Ambiguous_content:0.03,Usher placements: BA.2(3/3); scorpio replaced lineage inference BA.2

Without Scorpio:

> taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,scorpio_notes,version,pangolin_version,scorpio_version,constellation_version,is_designated,qc_status,qc_notes,note
> test1,BA.2,0.0,,,,,,PUSHER-v1.8,4.0.6,0.3.17,v0.1.10,False,pass,Ambiguous_content:0.03,Usher placements: BA.2(3/3)

Is anyone else experiencing this?

Thank you.

Versions:
pangolin (v4.0.6)
pangolin-data (v1.8)
constellations (v0.1.10)
scorpio (v0.3.17)
pangolin-assignment (v1.8)

**Comment by aineniamh** [comment]
We removed the 'probable' constellation definition for BA.* sublineages- this was originally intended to avoid false negatives when Omicron was first spreading and the SNP profile of the sublineages was a lot more distinguishable. 

At this stage, particularly when BA.2, BA.4 and BA.5 are so similar, we now need to prioritise avoiding false positives in the case of missing SNPs. If you check some of the more recent issues with constellations you'll see people reporting that probable definitions from scorpio had been leading to mis-calls and inappropriate overwriting of UShER assignments. This is why we've now removed probable definitions. 

The sequences that will have switched to unassigned are those that don't meet the SNP thresholds defined within scorpio constellations, and previously may have been picked up by the 'probable' definitions but now cannot be.

**Comment by KatSteinke** [comment]
We've been seeing this for unambiguous Usher calls as well - we almost have more samples with no reported conflict affected than ones which do have conflict.

**Comment by donutbrew** [comment]
Hi team--is there any update on this issue--the final `lineage` being (incorrectly?) overridden by scorpio? This affects a very large number of sequences.

**Comment by molly-hetheringtonrauth** [comment]
Wanted to post this here. At Colorado we are seeing the issue that previously assigned lineages are now unassigned as has been discussed above. However we are only seeing this issue on our ONT runs using the V4.1 artic primers, not on our Illumina runs using the V3 artic primers. We have also noticed that the sequences being called as unassigned have low coverage (~10x read depth) between 22,475-22,775 which corresponds to AA 305-405 in the Spike protein. Also when using the --skip-scorpio flag it seems like most of these unassigned sequences get assigned to BA.2 or it's sublineages and a handful get assigned to BA.4. We are prioritizing getting these sequencing up on GISAID so we can provide GISAID ids.

**Comment by karenbobier** [comment]
We are are also seeing sequences with "Unassigned" for the lineage. ~1/3 of our recent sequences that passed QC having an unassigned lineage. Were using midnight 1200 primers, sequencing on illumina miseq and run pangolin with the staph-b docker image.
pangolearn version: PLEARN-v1.8
pangolin_version: 4.0.6
scorpio_version: 0.3.17
constellation_version: v0.1.10


Some of our sequence with this problem GISAID IDs
EPI_ISL_12882763
EPI_ISL_12882764
EPI_ISL_12882765
EPI_ISL_12882766
EPI_ISL_12882768
EPI_ISL_12882769
EPI_ISL_12882770
EPI_ISL_12882771
EPI_ISL_12882772
EPI_ISL_12882773
EPI_ISL_12882775
EPI_ISL_12882776
EPI_ISL_12882780
EPI_ISL_12882782
EPI_ISL_12882784
EPI_ISL_12882785
EPI_ISL_12882786
EPI_ISL_12882787
EPI_ISL_12882788
EPI_ISL_12882789
EPI_ISL_12882790
EPI_ISL_12882792
EPI_ISL_12882793
EPI_ISL_12882794
EPI_ISL_12882795
EPI_ISL_12882796
EPI_ISL_12882797
EPI_ISL_12882801

**Comment by KatSteinke** [comment]
We *might* be seeing a trend towards fewer unassigned with ONT's Midnight V3 primers, but it's a little early to tell. 
Has anything changed about the weighting of ambiguous nucleotides or such? The affected sequences do meet our national quality criteria of <3000 missing with 4.1 as well, so it surprises me somewhat if that's become so harsh.

**Comment by AngieHinrichs** [comment]
It's really difficult to find a combination of mutation lists, thresholds and specific allele rules to get both sensitivity and specificity when distinguishing between BA.2, BA.4 and BA.5 in the presence of Ns and false reversions in different regions from different sequencing methods.  And @aineniamh has many demands on her time, but is actively working on this now, and I will try to help in what ways I can, being less familiar with scorpio/constellations.

Thanks @molly-hetheringtonrauth and @karenbobier for the specific examples!  Those will be really helpful for testing.

In the meantime, one thing we've been considering is possibly making scorpio override pangoLEARN but not UShER.  If you are running pangolin with the default UShER mode, consider adding the `--skip-scorpio` option to prevent the override.

**Comment by aineniamh** [comment]
In the latest release (4.1) we no longer overwrite usher calls if they don't meet the scorpio checks as we're confident in the usher calls. In pangoLEARN mode scorpio is still in place as before and will elimiate false positives. Closing this issue as I believe the latest version of pangolin will resolve your issue.
