### ISSUE TITLE
Usher conflict

### ISSUE THREAD

**Issue by huipingis** [cov-lineages/pangolin#450]
Dear Sir/Madam,

For the data: BA.2 (8/9), BA.2.24 (1/9), I wonder if in total 9 times of testing by Usher, 8 times of results with BA.2, and 1 time with BA.2.24?

Best regards,
Chen Huiping
University Hospital of Iceland

**Comment by aineniamh** [comment]
@AngieHinrichs, is it that there are 9 equally parsimonious placements and 8 of them would give a BA.2 result and 1 of them would give a BA.2.24 result?

**Comment by AngieHinrichs** [comment]
> there are 9 equally parsimonious placements and 8 of them would give a BA.2 result and 1 of them would give a BA.2.24 result?

Yes, thanks @aineniamh!  

@huipingis UShER evaluates the parsimony score (i.e. the number of substitutions required to transform that node's sequence into your sequence or vice versa) of placing your sequence at every node of input tree and reports the node(s) with the lowest score (fewest differences) and the associated lineage(s).  For pangolin, usher's input tree is a minimized version of the comprehensive SARS-CoV-2 tree maintained by UCSC, with 50 randomly selected descendants per lineage.  If you upload your sequence to the [UShER web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace), your sequence may have a more specific placement in the full tree, in which it can be compared to almost 10 million sequences -- or it may not, if there are Ns or ambiguous bases in informative positions.

The defining mutation for BA.2.24 is G22577A (relative to the reference genome [NC_045512.2](https://www.ncbi.nlm.nih.gov/nuccore/NC_045512.2)) so looking at the corresponding base in your sequence would also be helpful in determining whether your sequence is [BA.2.24](https://cov-lineages.org/lineage.html?lineage=BA.2.24) or just BA.2.

**Comment by huipingis** [comment]
Dear Sir/Madam,

Recently we got results on COVID genotyping, and found some samples unassigned, see below:

NEG6_13052022 | Unassigned | 0,090909091 | PUSHER-v1.8v4.0.6 | pass | Ambiguous_content:0.15 | Omicron (Unassigned) | Usher placements: BA.2(10/11) BA.2.11(1/11); scorpio replaced lineage inference BA.2

POS1_13052022 | Unassigned | 0 | PUSHER-v1.8v4.0.6 | pass | Ambiguous_content:0.12 | Probable Omicron (Unassigned) | Usher placements: BA.2.3.3(2/2); scorpio replaced lineage inference BA.2.3.3

pOS2_13052022 | Unassigned | 0,333333333 | PUSHER-v1.8v4.0.6 | pass | Ambiguous_content:0.1 | Probable Omicron (Unassigned) | Usher placements: BA.2(1/3) BA.2.3.3(2/3); scorpio replaced lineage inference BA.2.3.3

I am wondering why these samples were unassigned for lineages? Thanks.

Best regards,
Chen Huiping
University Hospital of Iceland

________________________________
Frá: Angie Hinrichs ***@***.***>
Sent: fimmtudagur, 12. maí 2022 16:26
Til: cov-lineages/pangolin ***@***.***>
Afrit: Huiping Chen ***@***.***>; Mention ***@***.***>
Efni: Re: [cov-lineages/pangolin] Usher conflict (Issue #450)

Þú færð ekki oft tölvupóst frá ***@***.*** Kynntu þér hvers vegna þetta gæti verið mikilvægt<https://aka.ms/LearnAboutSenderIdentification>

there are 9 equally parsimonious placements and 8 of them would give a BA.2 result and 1 of them would give a BA.2.24 result?

Yes, thanks @aineniamh<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faineniamh&data=05%7C01%7Chuiping%40landspitali.is%7Ccf348711a2454ab3aa6808da343426ae%7Ce1011e5272104017950f458075f9f84e%7C0%7C0%7C637879695877318998%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BSjswGwM%2FeP9VVBEzWm8QmpGzbtI6X1fpLZib5u5fd8%3D&reserved=0>!

@huipingis<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhuipingis&data=05%7C01%7Chuiping%40landspitali.is%7Ccf348711a2454ab3aa6808da343426ae%7Ce1011e5272104017950f458075f9f84e%7C0%7C0%7C637879695877318998%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qYbZRDTcw4XnDJ%2FpgXhLKS9i2DT39141xOnQdXY4o1g%3D&reserved=0> UShER evaluates the parsimony score (i.e. the number of substitutions required to transform that node's sequence into your sequence or vice versa) of placing your sequence at every node of input tree and reports the node(s) with the lowest score (fewest differences) and the associated lineage(s). For pangolin, usher's input tree is a minimized version of the comprehensive SARS-CoV-2 tree maintained by UCSC, with 50 randomly selected descendants per lineage. If you upload your sequence to the UShER web interface<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgenome.ucsc.edu%2Fcgi-bin%2FhgPhyloPlace&data=05%7C01%7Chuiping%40landspitali.is%7Ccf348711a2454ab3aa6808da343426ae%7Ce1011e5272104017950f458075f9f84e%7C0%7C0%7C637879695877475227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AthkXr%2FF0Z1m6MSjBM%2BlSEGVgfvwUaQEdmGsn%2BajXFo%3D&reserved=0>, your sequence may have a more specific placement in the full tree, in which it can be compared to almost 10 million sequences -- or it may not, if there are Ns or ambiguous bases in informative positions.

The defining mutation for BA.2.24 is G22577A (relative to the reference genome NC_045512.2<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fnuccore%2FNC_045512.2&data=05%7C01%7Chuiping%40landspitali.is%7Ccf348711a2454ab3aa6808da343426ae%7Ce1011e5272104017950f458075f9f84e%7C0%7C0%7C637879695877475227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A%2BlLk7Dguz9xR%2FNUdAwFQh6UICo5B3IeZmkOYPJTc9Y%3D&reserved=0>) so looking at the corresponding base in your sequence would also be helpful in determining whether your sequence is BA.2.24<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcov-lineages.org%2Flineage.html%3Flineage%3DBA.2.24&data=05%7C01%7Chuiping%40landspitali.is%7Ccf348711a2454ab3aa6808da343426ae%7Ce1011e5272104017950f458075f9f84e%7C0%7C0%7C637879695877475227%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rcB87eAit7Ax6kzeY7sOeVCR2hGO1odoVqdehHCz1aU%3D&reserved=0> or just BA.2.
