### ISSUE TITLE
Samples Unassigned

### ISSUE THREAD

**Issue by huipingis** [cov-lineages/pangolin#451]
Dear Sir/Madam,

Recently we got results on COVID genotyping, and found some samples unassigned, see below:

NEG6_13052022 | Unassigned | 0,090909091 | PUSHER-v1.8v4.0.6 | pass | Ambiguous_content:0.15 | Omicron (Unassigned) | Usher placements: BA.2(10/11)   BA.2.11(1/11); scorpio replaced lineage inference BA.2

POS1_13052022 | Unassigned | 0 | PUSHER-v1.8v4.0.6 | pass | Ambiguous_content:0.12 | Probable Omicron (Unassigned) | Usher placements: BA.2.3.3(2/2); scorpio replaced lineage inference   BA.2.3.3

pOS2_13052022 | Unassigned | 0,333333333 | PUSHER-v1.8v4.0.6 | pass | Ambiguous_content:0.1 | Probable Omicron (Unassigned) | Usher placements: BA.2(1/3) BA.2.3.3(2/3); scorpio replaced lineage  inference BA.2.3.3

I am wondering why these samples were unassigned for lineages? Thanks.

Best regards,
Chen Huiping
University Hospital of Iceland

**Comment by Hideaki615** [comment]
I've got the same issue when I updated my local pangolin_3.1.20 to 4.0.6.

Then it could be avoided by downgrading constellations-0.1.10 to 0.1.9, by executing a command like below.

$ conda activate pangolin
$ pip install git+https://github.com/cov-lineages/constellations.git@v0.1.9

Adding, I don't know how much it would be related, but I found the output of scorpio call is decreasing in the latest version, like below.

sample-01
-- constellations-0.1.10
---- scorpio call: Alt alleles 37; Ref alleles 1; Amb alleles 20; Oth alleles 1
-- constellations-0.1.9
---- scorpio call: Alt alleles 21; Ref alleles 0; Amb alleles 12; Oth alleles 0

So the latest one may have underestimated alleles and therefore made the sample "Unassigned", I guess...

**Comment by aineniamh** [comment]
Unassigned is often a result of conflicting signals or reference calls that scorpio thinks would make a lineage call unreliable. If you suspect your sequences are from contaminated samples, this would exactly be why scorpio would mask the lineage call.

**Comment by huipingis** [comment]
Thanks, Áine.

I wonder if the contamination can cause a wrong call, e.g., from B to BA.3 by using pangolin?

Regards,
Chen

**Comment by huipingis** [comment]
Thanks, Áine.

I wonder if the contamination can cause a wrong call, e.g., from B to BA.3 by using pangolin?

Regards,
Chen

________________________________
Frá: aineniamh ***@***.***>
Sent: miðvikudagur, 18. maí 2022 10:12
Til: cov-lineages/pangolin ***@***.***>
Afrit: Huiping Chen ***@***.***>; Author ***@***.***>
Efni: Re: [cov-lineages/pangolin] Samples Unassigned (Issue #451)

Þú færð ekki oft tölvupóst frá ***@***.*** Kynntu þér hvers vegna þetta gæti verið mikilvægt<https://aka.ms/LearnAboutSenderIdentification>

Unassigned is often a result of conflicting signals or reference calls that scorpio thinks would make a lineage call unreliable. If you suspect your sequences are from contaminated samples, this would exactly be why scorpio would mask the lineage call.

**Comment by aineniamh** [comment]
Hi @huipingis, this can absolutely happen as conflicting signals can confuse the inference. This is why we curate the assignments and check this, reporting Unassigned if the sequence doesn't meet the scorpio checks.

**Comment by eddieimada** [comment]
Hi @aineniamh, 
Does this means that if scorpio cannot confidently assign a lineage, the lineage call from UShER should not be trusted and discarded?

**Comment by huipingis** [comment]
Hi, Eddie,

Some samples were unassigned, probably due to low quality of the sequencing data, which is not for the whole genome, just a part of it. So accurate genotyping is impossible.

Regards,
Chen
________________________________
Frá: Eddie Imada ***@***.***>
Sent: miðvikudagur, 18. maí 2022 16:39
Til: cov-lineages/pangolin ***@***.***>
Afrit: Huiping Chen ***@***.***>; Mention ***@***.***>
Efni: Re: [cov-lineages/pangolin] Samples Unassigned (Issue #451)


Hi @aineniamh<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faineniamh&data=05%7C01%7Chuiping%40landspitali.is%7C0ab68e2ad7f14295bcee08da38ed09f9%7Ce1011e5272104017950f458075f9f84e%7C0%7C0%7C637884887973985324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3p7bTKO8akS%2BEcK64HoJAfntWgmP3UenoK6PWfuJoS0%3D&reserved=0>,
Does this means that if scorpio cannot confidently assign a lineage, the lineage call from UShER should not be trusted and discarded?

**Comment by aineniamh** [comment]
Hi all, in the latest release of pangolin (4.1), we now have introduced an updated process. 

We are confident in the calls by usher, so now bypass scorpio in usher mode and do not overwrite the usher assignment (so now default behaviour is to take the usher assignment as is, but still report the scorpio call). In pangoLEARN/ fast mode we still overwrite assignments that do not explicitly agree with scorpio to elimitate false positive calls with the pangoLEARN method. 

Hopefully this will resolve these Unassigned samples, but bear in mind that they would have been unassigned because they did not pass the scorpio checks.
