### ISSUE TITLE
pango-designation v1.9

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#453]
Hi, 
is this normal that pangolin-data doesn't update to 1.9 ?

(pangolin) [foueri01@inspq.qc.ca@slurm11p ~]$ pangolin --update
pangolin already latest release (v4.0.6)
pangolin-data already latest release (v1.8)
constellations already latest release (v0.1.10)
scorpio already latest release (v0.3.17)
(pangolin) [foueri01@inspq.qc.ca@slurm11p ~]$ pangolin --all-versions
pangolin: 4.0.6
pangolin-data: 1.8
constellations: v0.1.10
scorpio: 0.3.17
usher: 0.5.4
ucsc-fatovcf: 426
gofasta: 1.0.0
minimap2: 2.24

I see that pango-designation has been updated to 1.9 (https://github.com/cov-lineages/pango-designation/releases)

Thank you
Eric

**Comment by aineniamh** [comment]
Yes, it takes us some time to prepare the data release after the designation release has been tagged. It's on its way, but is not quite ready for release yet.

**Comment by EricFournier3** [comment]
perfect, thank you @aineniamh
