### ISSUE TITLE
No ambuiguity score

### ISSUE THREAD

**Issue by Aduboahen** [cov-lineages/pangolin#454]
Since the update to 4.0.6 pangolin output does not report ambiguity score. After downgrading to 3.1.17 ambiguity scores are reported.

**Comment by aineniamh** [comment]
Can you provide an example output of this as my own version appears to produce it as normal! Thanks for flagging!

**Comment by aineniamh** [comment]
Going to close this issue as it's stale. If you need anymore help Aduboahen just say and I'll repoen it.
