### ISSUE TITLE
Question regarding UNASSIGNED_LINEAGE_REPORTED

### ISSUE THREAD

**Issue by EricFournier3** [cov-lineages/pangolin#460]
Hi,

I have the following results in my preprocessing.csv report;
**name,hash,lineage,scorpio_constellations,scorpio_mrca_lineage,scorpio_incompatible_lineages,scorpio_support,scorpio_conflict,scorpio_notes,designated,qc_status,qc_notes
Canada/Qc-L00476699001/2022,86aad0efd5b0917ddabcd63e34b15195,,Omicron (Unassigned),None,,0.82,0.03,scorpio call: Alt alleles 27; Ref alleles 1; Amb alleles 5; Oth alleles 0,False,pass,Ambiguous_content:0.11
Canada/Qc-L00476357001/2022,f5e46d6062c320bdc799383d2fd7279a,,Omicron (Unassigned),None,,0.97,0.0,scorpio call: Alt alleles 32; Ref alleles 0; Amb alleles 1; Oth alleles 0,False,pass,Ambiguous_content:0.07**

According to the function generate_final_report() in report_collation.py, I see that lineage result in the final report will be Unassigned
**taxon,lineage,conflict,ambiguity_score,scorpio_call,scorpio_support,scorpio_conflict,scorpio_notes,version,pangolin_version,scorpio_version,constellation_version,is_designated,qc_status,qc_notes,note
Canada/Qc-L00476699001/2022,Unassigned,0.0,,Omicron (Unassigned),0.82,0.03,scorpio call: Alt alleles 27; Ref alleles 1; Amb alleles 5; Oth alleles 0,PUSHER-v1.9,4.0.6,0.3.17,v0.1.10,False,pass,Ambiguous_content:0.11,Usher placements: BA.5(1/1); scorpio replaced lineage inference BA.5
Canada/Qc-L00476357001/2022,Unassigned,0.0,,Omicron (Unassigned),0.97,0.0,scorpio call: Alt alleles 32; Ref alleles 0; Amb alleles 1; Oth alleles 0,PUSHER-v1.9,4.0.6,0.3.17,v0.1.10,False,pass,Ambiguous_content:0.07,Usher placements: BA.4(1/1); scorpio replaced lineage inference BA.4**

Can you please explain me why there is this final condition when scorpio_mrca_lineage is None and scorpio_constellations is Omicron (Unassigned)
```
elif not expanded_scorpio_lineage:
   append_note(new_row, f'scorpio replaced lineage inference {inference_lineage}')
    new_row['lineage'] = UNASSIGNED_LINEAGE_REPORTED
```

Why in such case the lineage value in the final report is Unasigned instead of the lineage value in the inference_report.csv
**hash,lineage,conflict,usher_note
86aad0efd5b0917ddabcd63e34b15195,BA.5,0.0,Usher placements: BA.5(2/2)
f5e46d6062c320bdc799383d2fd7279a,BA.4,0.0,Usher placements: BA.4(1/1)**

I am not sure to clearly understand this decision algorithm

Is there a parameter that we can adjust in the pangolin command line so that the lineage result is not Unassigned

Thank you in advance

Eric

**Comment by EricFournier3** [comment]
great @AngieHinrichs , I will try that

**Comment by EricFournier3** [comment]
thanks, it works

**Comment by AngieHinrichs** [comment]
Great, glad to hear it.
