### ISSUE TITLE
install pangolin

### ISSUE THREAD

**Issue by jeansaplische** [cov-lineages/pangolin#463]
Good afternoon,
I'm from Brazil
I'm trying to install pangolin in conda and it's giving the following error below.
please someone help?

(pangolin) PS C:\Users\Pokemaster> conda install -c bioconda -c conda-forge -c defaults pangolin
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__archspec==1=x86_64:  80%|█████████████████████████████████▌        | 4/5 [00:00<00:00,  5.53it/s]-                                                                                                                       \failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by aineniamh** [comment]
Hi @jeansaplische, do you have a current installation of pangolin that may be conflicting? I'll be honest, I'm not very familiar with windows installation!

**Comment by jeansaplische** [comment]
I don't have a conflicting Pangolin installation.
The computer's operating system is Windows 10.
I installed Anaconda 3 inside win10 and I'm trying to install Pangolin inside Anaconda 3.
I will do the installation test with Windows Subsystem Linux.

**Comment by aineniamh** [comment]
Hope this alternative approach worked. Will close the issue now but if you're still encountering install issues happy to reopen. 

Áine
