### ISSUE TITLE
Can't install pangolin 4.1.1

### ISSUE THREAD

**Issue by synmuh** [cov-lineages/pangolin#469]
Hello, we are having issues  installing pangolin 4.1.1. Seems there are lots of conflicts and if you are  forcing the install. a lower version of pangolin is installed (version 1 i think) Using miniconda env on Ubuntu 22.04 LTS

**Comment by AngieHinrichs** [comment]
Sorry to hear you're having installation issues.  What commands are you using to install pangolin?

**Comment by synmuh** [comment]
conda install -c bioconda pangolin , i already tried conda install -c bioconda -c conda-forge -c defaults pangolin.

What I did to make it work and update from 4.0.6 to 4.1.1 is to uninstall miniconda and installed anacoda. Seems to work just fine now.

Thank you.

> Sorry to hear you're having installation issues. What commands are you using to install pangolin?

**Comment by AngieHinrichs** [comment]
Glad you got it working, thanks for the update.
