### ISSUE TITLE
Usher calls an unexpected high proportion of BE.1 Variants

### ISSUE THREAD

**Issue by GorgonVZ** [cov-lineages/pangolin#470]
Dear Pangos,
during my last analysis I recognised an unexpected high proportion (~20%) of sequences annotated as BE.1 by Usher and BA.5-like by scorpio.
Given the pandemic situation I would expect around 60% of my sequences to reflect the BA.5 variant. That's why I am very confident that scorpio is giving me the "True/Omikron BA.5" call here.
I also uploaded sequences to UCSC's webversion of usher, which was giving me the same result.
Do you have an explanation for that?
Maybe something changed in ushers tree?
I was first expecting rawdata issues, but fastq, mappingfiles and fastas looking totally fine.

I am running versions:
pangolin: 4.1.1
pangolin-data: 1.11
constellations: v0.1.10
scorpio: 0.3.17
pangolin-assignment: 1.11
usher 0.5.4
gofasta 1.0.0
minimap2 2.24-r1122

command I used:
pangolin --no-temp All.fasta --min-length 26900 --max-ambig 0.5 -t $threads -o $out_final

Example output:
S245,BE.1,0.0,,Omicron (BA.5-like),0.98,0.02,scorpio call: Alt alleles 60; Ref alleles 1; Amb alleles 0; Oth alleles 0,PUSHER-v1.11,4.1.1,0.3.17,v0.1.10,False,pass,Ambiguous_content:0.02,Usher placements: BE.1(1/1)

**Comment by GorgonVZ** [comment]
I just recognised, that BE.1 is actually BA.5, sorry for that misunderstanding! But nevertheless I think it's curious, that naming seemed to change, since the last update.

**Comment by AngieHinrichs** [comment]
Yes, BE is an [alias](https://github.com/cov-lineages/pango-designation/blob/master/pango_designation/alias_key.json) for BA.5.3.1 (fully expanded, BE.1 is B.1.1.529.5.3.1.1).  Every new [pangolin-data release](https://github.com/cov-lineages/pangolin-data/releases) includes newly defined sublineages.  They are listed in the pango-designation release notes.  For example, the latest pangolin-data release included new lineages defined in pango-designation [v1.10](https://github.com/cov-lineages/pango-designation/releases/tag/v1.10) (including BE.1) and [v1.11](https://github.com/cov-lineages/pango-designation/releases/tag/v1.11).
