### ISSUE TITLE
regarding installation of pangolin

### ISSUE THREAD

**Issue by Rashmi-12-a11y** [cov-lineages/pangolin#471]
hi i am unable to install pangolin by using this commmand 
conda install -c bioconda -c conda-forge -c defaults pangolin
after runing this command  i ge
commander@commander:~$ conda install -c bioconda -c conda-forge -c defaults pangolin
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/commander/anaconda3

  added / updated specs:
    - pangolin

The following packages will be UPDATED:

  conda              pkgs/main::conda-4.13.0-py38h06a4308_0 --> conda-forge::conda-4.13.0-py38h578d9bd_1

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
commander@commander:~$ cd /home/commander/anaconda3
commander@commander:~/anaconda3$ pangolin -h
pangolin: command not found
commander@commander:~/anaconda3$ 

kindly please help.

- [ ]

**Comment by wm75** [comment]
Hi @Rashmi-12-a11y ,
you normally wouldn't install things into your base environment, but create a tool-specific environment with e.g. `conda create -n pangolin_env`, then step into it with `conda activate pangolin_env` (of course, you can use whatever name you like for pangolin_env in these commands).
With the environment activated you then run `conda install -c conda-forge -c bioconda pangolin` (notice the swap between conda-forge and bioconda, which is the standard way of using these channels though I don't know if it'll change anything for this specific install).

**Comment by synmuh** [comment]
I resolve this issue by uninstalling minicoda and installed the anaconda package and set installation conda create -n pangolin pangolin=4.1.1

**Comment by aineniamh** [comment]
In your second command, you don't list conda forge, which is why the error says packages are not available from current channels maybe try: 
```
conda create -n pangolin -c bioconda -c conda-forge  pangolin=4.1.1
conda activate pangolin

pangolin --help
```

**Comment by hafizmtalha** [comment]
M facing this issue.. can someone help ?
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 327, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/cli/install.py", line 356, in handle_txn
        unlink_link_transaction.execute()
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/core/link.py", line 277, in execute
        self.verify()
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/core/link.py", line 238, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/core/link.py", line 622, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 520, in map
        yield func(thing)
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/core/link.py", line 443, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/d/anaconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 319, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/d/anaconda3/lib/python3.9/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/d/anaconda3/pkgs/ncurses-6.3-h27087fc_1/share/terminfo/N/NCR260VT300WPP'

`$ /mnt/d/anaconda3/bin/conda create -n pangolin -c bioconda -c conda-forge pangolin=4.1.1`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mnt/d/anaconda3/bin/conda
             CONDA_PREFIX=/mnt/d/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mnt/d/anaconda3/bin/python
               CONDA_ROOT=/mnt/d/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/mnt/d/anaconda3/bin:/mnt/d/anaconda3/bin:/home/talha/.local/bin:/mnt/
                          d/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
                          :/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/Common
                          Files/libhmsbeagle:/mnt/c/Program Files (x86)/Common Files/Oracle/Java
                          /javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System
                          32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/
                          System32/OpenSSH:/mnt/c/Program Files/MEGA11:/mnt/c/Program Files
                          (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program
                          Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Users/haf
                          iz/AppData/Local/Microsoft/WindowsApps:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /mnt/d/anaconda3
            shell level : 1
       user config file : /home/talha/.condarc
 populated config files : /home/talha/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.9.12.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/d/anaconda3  (writable)
      conda av data dir : /mnt/d/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/d/anaconda3/pkgs
                          /home/talha/.conda/pkgs
       envs directories : /mnt/d/anaconda3/envs
                          /home/talha/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Linux/4.4.0-19041-Microsoft ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

**Comment by aineniamh** [comment]
I just googled your error "too many levels of symbolic links" and there seems to be a step by step for solving it here: https://www.baeldung.com/linux/too-many-levels-of-symlinks

**Comment by aineniamh** [comment]
Going to close due to inactivity. Hope it got sorted
