### ISSUE TITLE
BA.2.75 sequence gets misclassified as BA.2.73

### ISSUE THREAD

**Issue by KHajji** [cov-lineages/pangolin#473]
This is concerning this particular sequence in gisaid: hCoV-19/Netherlands/GE-RIVM-104208/2022.
Though it misses an amplicon in spike, the sequence contains all the charactic mutations of BA.2.75 as described in [pango designation issue #773](https://github.com/cov-lineages/pango-designation/issues/773). Since NextClade now also outputs pangolin lineages it seems to correctly characterise it as BA.2.75.

**Comment by aineniamh** [comment]
Hi @KHajji, which mode are you using to assign the lineage? Usher mode or pangoLEARN mode?

**Comment by aineniamh** [comment]
![Screenshot 2022-07-13 at 11 15 50](https://user-images.githubusercontent.com/11678307/178710496-c1a8e3c9-156c-4f55-932d-5433fd49fd4f.png)

Viewing it on the global tree with usher phyloplace shows it gets placed in the BA.2.73 group.
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_38ed8_e94ba0.json?c=pango_lineage

**Comment by aineniamh** [comment]
![Screenshot 2022-07-13 at 11 18 15](https://user-images.githubusercontent.com/11678307/178710978-226a9963-5a9e-4b88-9994-461f33cbcd82.png)
There's also apparently a BA.2.75 assignment by the latest usher as described here, but I'm not sure what version that information is sourced from

**Comment by KHajji** [comment]
![Uploading image.png…]()

**Comment by theosanderson** [comment]
As far as I can see the latest PangoLearn release is from prior to BA.2.75 designation. If so isn't this expected behaviour?

**Comment by aineniamh** [comment]
Ah good spot @theosanderson! I've just pushed a new model to a branch this morning so there may be an update to this in the not too distant future.

**Comment by KHajji** [comment]
Ah, so this will be corrected as soon as pangolin-data is updated. Thanks for the help!
