### ISSUE TITLE
Regarding Scorpio Call Prioritisation 

### ISSUE THREAD

**Issue by msinno01** [cov-lineages/pangolin#477]
I wanted to clarify the role of Scorpio in lineage designation using the default ("accurate") mode of pangolin.

My understanding was that the Scorpio call would override the UShER placement call where there is discrepancy, however I can see from some examples that this is not universally the case. For instance I can see a few samples which are called by pangolin as BA.4 with a scorpio call of BA.5, in the `note` output I can see the following: "scorpio lineage BA.5 conflicts with inference lineage BA.4".

Therefore would you be able to provide some clarification on when the Scorpio call is prioritised over the UShER placement and vice versa?

Many thanks in advance.

**Comment by msinno01** [comment]
I think I may have ound an answer, am I right in saything that this was updated in June with [4b9dc82](https://github.com/cov-lineages/pangolin/commit/4b9dc82aa9469d58171a77d8b6e4bf869a794f4f)?

**Comment by aineniamh** [comment]
Hey @msinno01, you're right that that used to be the case and that it's just recently been updated. Recently we've switched to not overwriting UShER calls, just pangoLEARN calls, if scorpio conflicts with them (we believe the vast majority UShER calls are giving accurate enough results the don't need to be overwritten by scorpio). PangoLEARN still gets overwritten though, and in cases of conflict will likely output an UNASSIGNED call.

**Comment by msinno01** [comment]
Hi @aineniamh, that's great thank you very much for the explanation, much appreciated!
