### ISSUE TITLE
Inconsistency between data_compatibility.csv and releases in Github

### ISSUE THREAD

**Issue by pvanheus** [cov-lineages/pangolin#478]
The [data_compatibility.csv](https://github.com/cov-lineages/pangolin/blob/master/pangolin/data/data_compatibility.csv) file mentions pangolin-data version [1.2.133](https://github.com/cov-lineages/pangolin/blob/master/pangolin/data/data_compatibility.csv#L8) and also pangolin-assigment version [1.2.133](https://github.com/cov-lineages/pangolin/blob/master/pangolin/data/data_compatibility.csv#L16). These versions do not, however, exist as Github releases. Instead pangolin-data has a release [v1.2.133.2](https://github.com/cov-lineages/pangolin-data/tree/v1.2.133.2) and pangolin-assignment has a release [v1.2.133.1](https://github.com/cov-lineages/pangolin-assignment/tree/v1.2.133.1).

While these are old releases and thus perhaps not so important, the inconsistency makes it somewhat harder to download all releases of pangolin's supporting data and match it up to the data_compatibility.csv. I don't think these version numbers are used in the pangolin code anywhere, so may I suggest changing the data_compatibility.csv to contain the version numbers in the Github releases?

I'm opening this as an issue instead of a PR to solicit feedback before proposing changes.

**Comment by AngieHinrichs** [comment]
I think you and @wm75 are currently the only consumers of data_compatibility.csv, so as far as I'm concerned, do whatever makes sense for your purposes!  It would most likely also make sense for others' purposes too.  Of course if @aineniamh sees anything I'm missing then I defer to her.  🙂

**Comment by aineniamh** [comment]
Nope, I'm happy for whichever suits your purposes best @pvanheus!

**Comment by wm75** [comment]
So just to be sure, those two different point releases of pangolin-data and pangolin-assignment are compatible with each other?

**Comment by AngieHinrichs** [comment]
> those two different point releases of pangolin-data and pangolin-assignment are compatible with each other?

They should be.  IIRC at the time, while the actual tagged releases had 4th level dot-suffixes (the extra .1 or .2), the `__init__.py` versions only had the first 3 levels (v1.2.133), and the compatibility check used versions extracted from `__init__.py` files so it didn't complain.  But testing would tell for sure.

**Comment by wm75** [comment]
Thanks @aineniamh and @AngieHinrichs for the feedback.
@pvanheus I guess the simplest solution is to add the `.2` to the pangolin-data 1.2.133 record and remove the pangolin-assignment 1.2.133 line.
This way Galaxy admins will be able to provide each version of pangolin-data and an assignment cache for everything except 1.2.133. If someone really wants a pangolin run with such an old version of the data, they just need to be a bit more patient and go without the assignment cache.
At the same time, that saves us the complexity of having to teach the pangolin wrapper that 1.2.133.2 (data) and 1.2.133.1 (assignment) should be offered to users together even though they don't have the same version number.

**Comment by aineniamh** [comment]
I'm going to close this now as I think it's been resolved!
