### ISSUE TITLE
Sequence unable to be processed with Pangolin (unknown error) 

### ISSUE THREAD

**Issue by coreymeloche** [cov-lineages/pangolin#481]
![Pango Issue](https://user-images.githubusercontent.com/86015486/184949197-61b3f9c4-7fdf-468a-8645-1457c73fda82.PNG)

Pango populates error "Sequence unable to be processed with Pangolin (unknown error)" with sequences that are known to have a valid result (as proven on different verisons".

**Comment by CorinYeatsCGPS** [comment]
Dear @coreymeloche,

Thanks for bringing this to our attention. I've fixed the deployment and all tasks should now run properly. Apologies for any inconvenience caused.

Best wishes, 
Corin

**Comment by coreymeloche** [comment]
Thank you Corin for the quick response and fix! We reran the sequences and received a valid result - all is well! Thanks again!

From: CorinYeatsCGPS ***@***.***>
Sent: Wednesday, August 17, 2022 4:37 AM
To: cov-lineages/pangolin ***@***.***>
Cc: Meloche, Corey E. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [cov-lineages/pangolin] Sequence unable to be processed with Pangolin (unknown error) (Issue #481)


Dear @coreymeloche<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcoreymeloche&data=05%7C01%7Cmeloche.corey%40mayo.edu%7C07a06d12f966421006f808da8034144c%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C637963258445420343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7uMNzlCVtFrVmehdPkS%2FDfJ6bFtIsHsvtOZFtwdmOlc%3D&reserved=0>,

Thanks for bringing this to our attention. I've fixed the deployment and all tasks should now run properly. Apologies for any inconvenience caused.

Best wishes,
Corin

-
