### ISSUE TITLE
BA.4* sequences identified as BA.2 by Pangolin after Scorpio override

### ISSUE THREAD

**Issue by gyebra-phs** [cov-lineages/pangolin#482]
Dear all,

We have ~30 Scottish sequences which are BA.4* according to our trees (not forming a cluster but rather interspersed across the BA.4 clade) but are identified as BA.2 by Pangolin. From what I can see PangoLEARN assigns them to BA.4 but this call is replaced by Scorpio. They seem to vary in terms of sequence quality and they come from different sequencing sites so I don't think it's a quality issue.

Any help with this would be appreciated! Below a selection of COG-UK IDs.

```
LSPA-3E7754A
LSPA-3F51ED1
PLYM-3EEAB7D
PLYM-3EFDB2C
QEUH-3EA3985
QEUH-3F48893
SCOT-13564
SCOT-15786
SCOT-16241
```

Many thanks!

Gonzalo

**Comment by gyebra-phs** [comment]
Hi Áine,

When I ran it using the UShER mode, it successfully assigns them to BA.4x (with a message in the `note` column such as `Usher placements: BA.4.1(1/1); scorpio lineage BA.2 conflicts with inference lineage BA.4.1`).

Many thanks for taking a look at this!

Gonzalo

**Comment by aineniamh** [comment]
Okay, great! It looks like your sequences are BA.4.1- UShER is now the default mode for a reason! 
Scorpio constellations might be struggling to ID the lineages with the level of convergence we see.

**Comment by gyebra-phs** [comment]
Thanks Áine, good to know! We'll keep this in mind if we find unexpected results.
