### ISSUE TITLE
"Check your environment, didn't find appropriate files from the pangoLEARN repo.  Trained model must be installed, please see https://cov-lineages.org/pangolin.html for installation instructions."

### ISSUE THREAD

**Issue by nonononanana** [cov-lineages/pangolin#484]
I have followed instuctions regarding pangoLEARN https://cov-lineages.org/resources/pangolin/pangolearn.html, and installed pango-data https://github.com/cov-lineages/pangolin-data, but the error still remains.

> Check your environment, didn't find appropriate files from the pangoLEARN repo. Trained model must be installed, please see https://cov-lineages.org/pangolin.html for installation instructions

It will be greatly appreciated if anyone could kindly help.

**Comment by aineniamh** [comment]
What version of pangolin are you running? 

Did you follow the install instructions here: https://cov-lineages.org/resources/pangolin/installation.html

**Comment by nonononanana** [comment]
> 
Thank you so much for your timely reply! Here are the version information given by conda.

> pangolin                  4.1.2                    pypi_0    pypi
> pangolin-data             1.14                     pypi_0    pypi

Yes I followed the instructions.
First I tried to install from the github repo but it wasn't successful, so I turned to using bioconda. I suspect this caused some problems.

**Comment by nonononanana** [comment]
Hey I just tried to reinstall pangolin with bioconda in a new docker, and the same error occurred. Shall I somehow fix the pangoLEARN repo?

**Comment by aineniamh** [comment]
I'm not sure what installing in a docker will do to the install. I'd suggest either just install the [docker image](https://hub.docker.com/r/covlineages/pangolin) for pangolin, or else install with bioconda, it sounds like you might be currently attempting a mixture of both.

**Comment by aineniamh** [comment]
Going to close this as it's a stale issue. Will reopen if needed.
