### ISSUE TITLE
cov-lineages.org doesn't find B.1.617.3

### ISSUE THREAD

**Issue by trilisser** [cov-lineages/pangolin#498]
Hi there!

cov-lineages.org (lineages' page) doesn't find B.1.617.3 (B.1.640.2 btw). The other lineages (B.1.617.1/2) it sees well. Bug maybe?

![image](https://user-images.githubusercontent.com/43595074/203893923-5b0efba6-9682-42c3-8c8b-a87ba55d4605.png)

**Comment by rmcolq** [comment]
Only lineages seen at least once within the last 6 months are currently displayed one the website. The full set can be found in the JSON file (stored with git-lfs) `https://github.com/cov-lineages/lineages-website/blob/master/_data/lineage_data.full.json`
