### ISSUE TITLE
Rebuild pangolin when edit some of the files

### ISSUE THREAD

**Issue by afdhalrashid** [cov-lineages/pangolin#502]
I try to edit report collation file and run pangolin filename.fas but no changes. My changes is skipping the has assigment part.
How to rebuild the project after making changes?

**Comment by AngieHinrichs** [comment]
Try running this command in the top-level pangolin directory:
```
pip install .
```

**Comment by afdhalrashid** [comment]
> Try running this command in the top-level pangolin directory:
> 
> ```
> pip install .
> ```

Its working. My changes already can be seen in terminal. **Thank you**
