### ISSUE TITLE
Naming convention violates best practices in regard to not using geographical Names

### ISSUE THREAD

**Issue by AurelWu** [cov-lineages/pangolin#507]
Variants which use 2 Letters at the beginning collide with ISO-3166 Country Codes and can cause stigma. CH Variant might be interpreted as originating from Switzerland. Same Issue for BA actually but not many know that BA stands for Bosnia and Herzegovina. I'm not sure why there is even a need to have a 2nd Letter, with 1 Letter no such problems arise and Numbers suffice for naming anyways. Aside from geographical Names there also might be future variants which have Names which are problematic in some countries (e.g. "HJ" , "NS" , "SA" , "SS" in Germany).

**Comment by rambaut** [comment]
This is the wrong place for this discussion - this is an issue list for the Pangolin software. Pangolin does not create lineage names nor define the rules of the Pango lineage system.
