### ISSUE TITLE
Pangolin.cog-uk.io - Not loading

### ISSUE THREAD

**Issue by coreymeloche** [cov-lineages/pangolin#517]
Pangolin Web Application will not load. 
![PANGO](https://user-images.githubusercontent.com/86015486/233664360-c238b6ea-d853-490c-9d0b-cbd0649d29f0.PNG)

**Comment by CorinYeatsCGPS** [comment]
Hi @coreymeloche, the site should be back up. Our host (CLIMB) was down for a few days for a major upgrade, which is now complete.
