### ISSUE TITLE
Pangolin.cog stuck in analyzing

### ISSUE THREAD

**Issue by pu1621** [cov-lineages/pangolin#518]
I have upload nanopore data which processed via artic protocol to Pangolin web applicatiom, but it cannot analyzed. Some of barcode can be analyzed, but almost of them show analysing process (not fail).

What should I do to fix it? (I used pangolin to analyzed more than 20 run, but this is first time that it stuck)

![image](https://user-images.githubusercontent.com/69662902/235629871-df07cab6-3945-41bb-8159-b01612324bbb.png)

![image](https://user-images.githubusercontent.com/69662902/235630813-9420439a-ffb0-4d4f-bb25-72b74fe33c51.png)

**Comment by CorinYeatsCGPS** [comment]
Hi @pu1621
It appears there's an issue with the server. I'm just looking at it now.

**Comment by CorinYeatsCGPS** [comment]
@pu1621 Could you try uploading your sequences again? Hopefully it should work this time.

If the service is down again in the future, you can also upload the genomes to https://pathogen.watch/. Though please do let us know if https://pangolin.cog-uk.io/ is down, so we can fix it!

**Comment by pu1621** [comment]
> @pu1621 Could you try uploading your sequences again? Hopefully it should work this time.
> 
> If the service is down again in the future, you can also upload the genomes to https://pathogen.watch/. Though please do let us know if https://pangolin.cog-uk.io/ is down, so we can fix it!

Thank you, I can upload and analyze the data now.

**Comment by Siribun-P** [comment]
Hi @CorinYeatsCGPS 
https://pangolin.cog-uk.io/ is down again. I am also facing the same problem. Could you please fix it?

**Comment by CorinYeatsCGPS** [comment]
Thanks @Siribun-P 
It should be back up again.

**Comment by Siribun-P** [comment]
Thanks @CorinYeatsCGPS 
Now I could do the analysis.
