### ISSUE TITLE
Pangolin Web Application will not load.

### ISSUE THREAD

**Issue by s-groc** [cov-lineages/pangolin#520]
Pangolin Web Application will not load.

**Comment by CorinYeatsCGPS** [comment]
Hi @s-groc
We're are of the issue, apologies for the inconvenience. Unfortunately, it's a bit out of our hands, but we hope it will be back up very soon.

**Comment by s-groc** [comment]
Thanks for your quick feedback. I hope so.

**Comment by s-groc** [comment]
Hi, do you know more about the Pangolin loading problem?

**Comment by CorinYeatsCGPS** [comment]
Sorry, no solution yet. In the mean time, you can also upload your genomes to https://pathogen.watch/. It's running the same version of Pangolin, but does require a log in.
