### ISSUE TITLE
faToVcf seems to omit insertions in vcf output (input to usher)

### ISSUE THREAD

**Issue by smsaladi** [cov-lineages/pangolin#530]
It seems that faToVcf's vcf output is used as the input to usher:

https://github.com/cov-lineages/pangolin/blob/2f2756e5ddd23b10cd8a1724d71e0f92c7c5b78f/pangolin/scripts/usher.smk#L109-L110

We've been working with the vcf file and were not able to find insertions with respect to the reference in this file. It seems like `faToVcf` might omit them.  A minimal example below.

Has this come up before? Or maybe we are misunderstanding something?

Command: 
```bash
./faToVcf -includeNoAltN test.fa test.vcf` 
```
"kent source version 453".

input: `test.fa`
```text
>ref
------NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
ATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTT------
GCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGG
AGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGGCTTA
GTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCAT
CAAACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGG
>ref
------NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
ATGGAGAGCCTTGTCCCTGGTTTCAACGAGAAAACACACGTCCAACTCAGTTTGGGGGG
GCCTGTTTTACAGGTTCGCGACGTGCTCGTACGTGGCTTTGGAGACTCCGTGG
AGGAGGTCTTATCAGAGGCACGTCAACATCTTAAAGATGGCACTTGTGGCTTA
GTAGAAGTTGAAAAAGGCGTTTTGCCTCAACTTGAACAGCCCTATGTGTTCAT
CAAACGTTCGGATGCTCGAACTGCACCTCATGGTCATGTTATGGTTGAGCTGG
```

output: `test.vcf`

```text
##fileformat=VCFv4.2
##reference=test.fa:ref
##source=faToVcf test.fa out.vcf
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  ref
```

**Comment by smsaladi** [comment]
Actually, it looks like USher doesn't support indels at this time, so there's no effect that insertions are dropped by faToVcf

https://github.com/yatisht/usher/issues/186

**Comment by AngieHinrichs** [comment]
Right, faToVcf was written [in a hurry earlier in the pandemic] specifically for UShER, and since UShER ignores indels, I haven't bothered to implement them.  Sorry about that, faToVcf should have a warning message about that!

**Comment by smsaladi** [comment]
So grateful for you - thanks!
