### ISSUE TITLE
Pango Designation Hash

### ISSUE THREAD

**Issue by whottel** [cov-lineages/pangolin#534]
Hello,

I have been using Pango to analyze some historical sequences, and I see a fair amount are “Assigned from a designation hash”. Where can I find the reference sequence(s) that were used to define a hash for a given lineage.

Thanks,
Wes

**Comment by AngieHinrichs** [comment]
Hello @whottel, you can find sequence designations in this file: https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv
That file lists sequence names and lineages.  To get the actual sequences, you'll need to obtain them from https://gisaid.org/ which requires registration; some sequences are also available from [INSDC](https://www.insdc.org/) databases such as GenBank; you can try searching in [NCBI Virus](https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Severe%20acute%20respiratory%20syndrome%20coronavirus%202,%20taxid:2697049).

**Comment by whottel** [comment]
Great, that was the file I was looking!

Thanks,
Wes
