### ISSUE TITLE
I'm curious what this software does.

### ISSUE THREAD

**Issue by ShangTianYa** [cov-lineages/pangolin#552]
～～～

**Comment by aineniamh** [comment]
Hi @ShangTianYa, thanks for your question. I would first direct you to the documentation on our cov-lineages.org website here: https://cov-lineages.org/resources/pangolin.html, which gives an overview of the software and what it is for. If you want more details I would point you to the published article for the pangolin software here:  https://academic.oup.com/ve/article/7/2/veab064/6315289
If anything is not clear or you need clarification please don't hesitate to ask.
