### ISSUE TITLE
Error in rule add_failed_seqs:

### ISSUE THREAD

**Issue by dcadam** [cov-lineages/pangolin#93]
Hi there, 

I'm encountering an error running pangolin v2.0.5 and can't seem to find a solution. 

See the error message below: 

```
loading model 08/17/2020, 16:56:28
/usr/local/Caskroom/miniconda/base/envs/pangolin/lib/python3.6/site-packages/scikit_learn-0.23.2-py3.6-macosx-10.7-x86_64.egg/sklearn/base.py:334: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
generating predictions 08/17/2020, 16:56:28
processing block of 50 sequences 08/17/2020, 16:56:29
complete 08/17/2020, 16:56:41
Job counts:
	count	jobs
	1	add_failed_seqs
	1
[Mon Aug 17 16:56:41 2020]
Error in rule add_failed_seqs:
    jobid: 0
    output: /Users/dcadam/Dropbox/Shared HK 2019nCoV/data_genomes/lineage_report.csv

RuleException:
ValueError in line 132 of /usr/local/Caskroom/miniconda/base/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.5-py3.6.egg/pangolin/scripts/pangolearn.smk:
too many values to unpack (expected 3)
  File "/usr/local/Caskroom/miniconda/base/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.5-py3.6.egg/pangolin/scripts/pangolearn.smk", line 132, in __rule_add_failed_seqs
  File "/usr/local/Caskroom/miniconda/base/envs/pangolin/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message
```

I've tested this on different batches of sequences, and some work, outputting the expected lineages_report.csv, but others inexplicably do not. Perhaps there is a problem with some of the sequences themselves, as suggested by the ```Error in rule add_failed_seqs:```

Hopefully, you can help.

**Comment by aineniamh** [comment]
Hi Dillon, 

That's a new one! Would you be able to provide me with a file to test as I haven't been able to replicate that error on my end!

Áine

**Comment by dcadam** [comment]
Hi Áine, 

See the attached zip files. The *_batch1.fasta file works fine but *_batch2.fasta produces the error. 

I note there is a single sequence in batch 2 that is not full length but I wouldn't have thought that would matter so much, and testing on other batches that contain only full-length sequences still produced the same error. 

Looking forward to hearing back from you.

Dillon

[Archive.zip](https://github.com/cov-lineages/pangolin/files/5087886/Archive.zip)

**Comment by aineniamh** [comment]
Ah, I can see what the problem is! The comma in the name of your sequence is breaking our csv parsing. When I remove the comma it all works okay. I will add in a qc check for commas in sequence names now so that it has a more informative error! 

Thanks for providing the file, that wasn't a case I had considered before! 

Áine

[lineage_report.batch_2.csv.zip](https://github.com/cov-lineages/pangolin/files/5089814/lineage_report.batch_2.csv.zip)
