### ISSUE TITLE
Key error in pangolearn.smk file 

### ISSUE THREAD

**Issue by lr5317** [cov-lineages/pangolin#94]
On line 31, there is a key error with outfile: 

KeyError in line 31 of /anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.5-py3.6.egg/pangolin/scripts/pangolearn.smk:
'outfile'
  File "/anaconda3/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.5-py3.6.egg/pangolin/scripts/pangolearn.smk", line 31, in <module>
Exiting because a job execution failed. Look above for error message

Please let me know what the issue might be. 

Thank you.

**Comment by aineniamh** [comment]
Hi, thanks for getting in touch- hard to know what the error is from the message as it's running fine on this end. 

Could you let me know exactly what command you ran and if possible provide the file you used that got the error? Feel free to email me at aine.otoole@ed.ac.uk if you'd rather not post the file up on GitHub.

**Comment by aineniamh** [comment]
I'm going to close this issue as I haven't heard back, but if this problem has continued let me know and I can re-open!
