### ISSUE TITLE
Decision tree / Ns?

### ISSUE THREAD

**Issue by bbimber** [cov-lineages/pangolin#95]
Hello - if you're prefer that I ask this elsewhere please let me know.  I was looking at the decision tree rules, and was surprised to see a fair number of rules with something like XXXX != 'N'.  Do you believe these have anything meaningful to do with the biology/sequence of lineages, or is this just the classifier picking up on common low-coverage positions?

**Comment by aineniamh** [comment]
@emilyscher will know the in-depth details of the training, but really there won't be anything biological about 'N's informing decisions. There might be something to say about excluding N's from a decision tree model, me and Emily can chat about it, but thanks for pointing it out!

**Comment by bbimber** [comment]
Biological was a poor word choice - systematic technical issues due to amplification methods or due to the sequence of the lineage would be more precise. For example, the artic primer set might dominate YOUR data, and some lineages might have systematic issues over a given region.  Perhaps a snp under one of the artic primers. This is all speculation. Just in general I would have expected coverage (which presumably is what Ns measure), would not differentiate lineages.

**Comment by aineniamh** [comment]
So, to update, the most recent release of pangoLEARN now switches out N's in the training data and replaces them with the non-informative reference variant. This should account for any sort of decisions that might be made based on missing data. Thanks for highlighting this issue!
