### ISSUE TITLE
Version control dependencies

### ISSUE THREAD

**Issue by schorlton** [cov-lineages/pangolin#96]
## Issue

I use `pangolin` in Docker containers - great work. When building the container, I downloaded [source code](https://github.com/cov-lineages/pangolin/archive/v2.0.5.tar.gz) tagged at version `2.0.5` for installation. In the meantime, `pangoLEARN` underwent changes leading to the `pangoLEARN` db not being found when executing `pangolin`. `pangolin` underwent concurrent changes accounting for changes in `pangoLEARN`. Updating `pangolin` to `2.0.7` fixes the issue.

## Solution
 Dependencies should be pinned (particularly git repos like pangoLEARN and datafunk) at versions/commits (or ranges of them) in [`environment.yml`](https://github.com/cov-lineages/pangolin/blob/master/environment.yml).

Thanks!

**Comment by aineniamh** [comment]
Thanks for pointing that out. In general the most recent releases of pangolin and pangoLEARN are combatible at any given time and are usually released at the same time. 

You're right though about specifying specific versions in the environment and we can do that from now on.
