### ISSUE TITLE
Problem with the path to the data reference

### ISSUE THREAD

**Issue by Gabo-Gonzalez** [cov-lineages/pangolin#97]
I just updated Pangolin and was getting this error on the execution: 
-----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gabriel/miniconda3/envs/pangolin/bin/pangolearn.py", line 4, in <module>
    __import__('pkg_resources').run_script('pangolin==2.0.7', 'pangolearn.py')
  File "/home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.7-py3.6.egg/EGG-INFO/scripts/pangolearn.py", line 110, in <module>
    referenceSeq = findReferenceSeq()
  File "/home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.7-py3.6.egg/EGG-INFO/scripts/pangolearn.py", line 36, in findReferenceSeq
    with open(referenceFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangolin-2.0.7-py3.6.egg/EGG-INFO/scripts/../data/reference.fasta'
[Wed Sep 30 10:13:52 2020]
Error in rule pangolearn:
    jobid: 2
    output: /tmp/tmpjulfodk_/lineage_report.pass_qc.csv
    shell:
        
        pangolearn.py --header-file /home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib --model-file /home/gabriel/miniconda3/envs/pangolin/lib/python3.6/site-packages/pangoLEARN/data/decisionTree_v1.joblib --fasta /tmp/tmpjulfodk_/post_qc_query.aligned.fasta -o /tmp/tmpjulfodk_/lineage_report.pass_qc.csv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
-----------------------------------------------------------------------------------------------------------
Patched this line "referenceFile = os.path.join(dirname, '../data/reference.fasta')" in pangolearn.py with the absolute path to reference.fasta and it works fine now.

It could be an error on my environment. But just in case.

**Comment by aineniamh** [comment]
Thanks for pointing that out! 

I've updated to 2.0.8, which has the reference file being passed as a command line arg to pangolearn.py now, as we had the absolute file path to reference available in the rest of the tool, just not in this script.
