### ISSUE TITLE
Support PuLP 2.x ?

### ISSUE THREAD

**Issue by tseemann** [cov-lineages/pangolin#98]
Thanks for the continued work on Pangolin 
Especially the pangoLEARN speed impriovements.

PuLP was upgrade from 1.6.10 to 2.x recentlyh
Pangolin no longer works

Yes i know one should use virutal envs
BUT
was wondering if you were going to upgrade?

Becasue snakemake 5.25 depends on 2.x now.

**Comment by aineniamh** [comment]
Okay, I'll look into this. I hadn't explicitly been doing anything with PuLP, but a quick fix might be if I added `PuLP>=2` to the dependancies in the setup.py for installation. 

Did you get any particular error with the new PuLP version?

**Comment by aineniamh** [comment]
Hi @tseemann, I've just tagged release [v2.0.8](https://github.com/cov-lineages/pangolin/releases/tag/v2.0.8), which has `PuLP>=2 `in the setup.py install instructions. Hope this solves the issue you've been having, if not I can revisit!
