### ISSUE TITLE
pangoLEARN 0 snakemake not  using threads

### ISSUE THREAD

**Issue by tseemann** [cov-lineages/pangolin#99]
Since I switched to pangoLEARN i noticed `pangolin -t 64` is not used.

It only every runs 1 process, giving `minimap2` etc 4 cores but only one running at a time.

And it batches the sequ4ences 1000 at a time.

Is this a `snakemake` bug?

**Comment by aineniamh** [comment]
Hi @tseemann, yes this isn't a snakemake bug, the pangolearn.py script just takes in everything at once currently. I've had a chat with @emilyscher and we'll move towards batching outside of pangolearn.py (the batching was added in by @ArtPoon) to reincorporate multithreading properly into pangolearn. 

With the speedups that Emily brought in, the multithreading didn't seem to be as necessary (was assigning 80K sequences in a couple of hours!), but I think that it's something I'd like to add back in, so I'll mark it as enhancement!

**Comment by rmcolq** [comment]
Closing as stale - feel free to reopen if this is still causing a problem
